export { inventoryRoutes } from './routes/inventoryRoutes'
export { catalogService } from './services/CatalogService'
export { catalogFilters, catalogSortFilter, catalogGroupingFilter } from './searchFilters'
export { useCatalogAccess } from './hooks/useCatalogAccess'
export type { Product } from './schemas/catalog'
