import { Globe, Building2, ShieldCheck, UsersRound, Target, Package, ShoppingCart, Truck, Warehouse, Receipt, Landmark, FolderKanban, CalendarDays, Plug, ListOrdered } from 'lucide-react'
export const settingsSections = [
  { slug: 'references', title: 'Référentiels', group: 'Socle commun', icon: Globe, description: 'Pays, langues et devises partagés par Horizon.', topics: ['Pays', 'Langues', 'Devises'], available: true },
  { slug: 'sequences', title: 'Séquences', group: 'Socle commun', icon: ListOrdered, description: 'Formats et compteurs des numéros de pièces.', topics: ['Numéro de départ', 'Prochain numéro', 'Préfixes et suffixes'], available: true },
  { slug: 'organisation', title: 'Organisation', group: 'Socle commun', icon: Building2, description: 'Identité de votre entreprise et préférences générales.', topics: ['Identité et logo', 'Coordonnées', 'Fuseau horaire et formats'], available: false },
  { slug: 'users', title: 'Utilisateurs et accès', group: 'Socle commun', icon: ShieldCheck, description: 'Profils ERP, comptes et accréditations métier.', topics: ['Utilisateurs', 'Profils ERP', 'Modules et périmètres', 'Couleurs des tags'], available: true },
  { slug: 'contacts', title: 'Contacts', group: 'Modules métier', icon: UsersRound, description: 'Qualification des contacts et relations commerciales.', topics: ['Sources des contacts', 'Tags et qualification', 'Préférences de relation'], available: false },
  { slug: 'crm', title: 'CRM', group: 'Modules métier', icon: Target, description: 'Étapes et présentation du suivi commercial.', topics: ['Étapes commerciales', 'Ordre du Kanban', 'Couleurs des étapes', 'Types de marché'], available: true },
  { slug: 'catalogue', title: 'Catalogue', group: 'Modules métier', icon: Package, description: 'Structuration des produits, services et tarifs.', topics: ['Catégories et unités', 'Taxes', 'Tarification'], available: false },
  { slug: 'ventes', title: 'Devis', group: 'Modules métier', icon: ShoppingCart, description: 'Présentation et valeurs par défaut des devis.', topics: ['Colonnes des devis', 'Valeurs par défaut', 'Conditions générales de vente'], available: true },
  { slug: 'achats', title: 'Achats', group: 'Modules métier', icon: Truck, description: 'Règles de préparation et suivi des achats.', topics: ['Numérotation des commandes', 'Conditions fournisseurs', 'Approvisionnement'], available: false },
  { slug: 'stock', title: 'Stock', group: 'Modules métier', icon: Warehouse, description: 'Entrepôts, emplacements et suivi des mouvements.', topics: ['Entrepôts et emplacements', 'Types de mouvements', 'Inventaires'], available: false },
  { slug: 'facturation', title: 'Facturation', group: 'Modules métier', icon: Receipt, description: 'Factures, règlements et documents de facturation.', topics: ['Numérotation', 'Conditions de paiement', 'Modèles et mentions'], available: false },
  { slug: 'comptabilite', title: 'Comptabilité', group: 'Modules métier', icon: Landmark, description: 'Référentiels comptables et suivi analytique.', topics: ['Journaux et comptes', 'Axes analytiques', 'Devises et exports'], available: false },
  { slug: 'projets', title: 'Projets', group: 'Modules métier', icon: FolderKanban, description: 'Organisation des affaires et du suivi opérationnel.', topics: ['Types de projets', 'Étapes et modèles', 'Budgets'], available: false },
  { slug: 'planning', title: 'Planning et temps', group: 'Modules métier', icon: CalendarDays, description: 'Calendriers de travail et catégories de temps.', topics: ['Calendriers', 'Types d’affectation', 'Profils de coût'], available: false },
  { slug: 'integrations', title: 'Intégrations', group: 'Connexions', icon: Plug, description: 'Services externes et connexions à Horizon.', topics: ['Recherche d’entreprises (État)', 'Sage et SUPER PDP', 'Messagerie et génération PDF'], available: false },
] as const
export const settingsGroups = ['Socle commun', 'Modules métier', 'Connexions'] as const
export const settingsSectionPath = (slug: string) => ['references', 'crm', 'sequences', 'users', 'ventes'].includes(slug) ? `/settings/${slug}` : `/settings/modules/${slug}`
