import { flexRender, getCoreRowModel, useReactTable, type ColumnDef, type OnChangeFn, type SortingState } from '@tanstack/react-table'
import { Link } from 'react-router'
import { ArrowDown, ArrowUp } from 'lucide-react'

export function HDataTable<T>({ data, columns, sorting = [], onSortingChange, getRowLink, getRowAction, resizable = false }: { data: T[]; columns: ColumnDef<T>[]; resizable?: boolean; sorting?: SortingState; onSortingChange?: OnChangeFn<SortingState>; getRowLink?: (record: T) => { href: string; label: string; state?: unknown }; getRowAction?: (record: T) => { label: string; onClick: () => void } }) {
  // React Compiler is not enabled; keep the required TanStack Table v8 hook uncompiled.
  // eslint-disable-next-line react-hooks/incompatible-library
  const table = useReactTable({ data, columns, getCoreRowModel: getCoreRowModel(), manualSorting: true, state: { sorting }, ...(onSortingChange ? { onSortingChange } : {}), enableSorting: Boolean(onSortingChange), enableMultiSort: false, enableColumnResizing: resizable, columnResizeMode: 'onChange' })
  return <div className="data-table-scroll"><table className="h-data-table" data-resizable={resizable || undefined}>{resizable && <colgroup>{table.getVisibleLeafColumns().map((column) => <col key={column.id} style={{ width: `${column.getSize() / table.getTotalSize() * 100}%` }} />)}</colgroup>}<thead>{table.getHeaderGroups().map((group) => <tr key={group.id}>{group.headers.map((header) => <th key={header.id} scope="col" aria-sort={header.column.getIsSorted() === 'asc' ? 'ascending' : header.column.getIsSorted() === 'desc' ? 'descending' : undefined}>
    {header.column.getCanSort() ? <button type="button" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}{header.column.getIsSorted() === 'asc' && <ArrowUp size={12} />}{header.column.getIsSorted() === 'desc' && <ArrowDown size={12} />}</button> : flexRender(header.column.columnDef.header, header.getContext())}
    {resizable && header.column.getCanResize() && <button type="button" className="h-table-column-resizer" aria-label={`Redimensionner ${typeof header.column.columnDef.header === 'string' ? header.column.columnDef.header : header.id}`} title="Glisser pour ajuster la largeur" onMouseDown={header.getResizeHandler()} onTouchStart={header.getResizeHandler()} onDoubleClick={() => header.column.resetSize()} onKeyDown={(event) => { if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') return; event.preventDefault(); table.setColumnSizing((sizes) => ({ ...sizes, [header.column.id]: Math.max(header.column.columnDef.minSize || 20, Math.min(header.column.columnDef.maxSize || 600, header.column.getSize() + (event.key === 'ArrowRight' ? 10 : -10))) })) }} />}
  </th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map((row) => {
    const link = getRowLink?.(row.original)
    const action = getRowAction?.(row.original)
    return <tr key={row.id} className={link || action ? 'h-data-table-clickable-row' : undefined}>{row.getVisibleCells().map((cell, index) => <td key={cell.id}>{index === 0 && (link ? <Link className="h-data-table-row-link" to={link.href} state={link.state} aria-label={link.label} /> : action ? <button type="button" className="h-data-table-row-link" aria-label={action.label} onClick={action.onClick} /> : null)}{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>
  })}</tbody></table></div>
}
