import { HFieldLabel } from '../../../shared/ui/HFieldLabel'
import { useState } from 'react'
import { Link } from 'react-router'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Building2, Network, UserRound } from 'lucide-react'
import { HDialog } from '../../../shared/ui/HDialog'
import { HSectionHeading } from '../../../shared/ui/HSectionHeading'
import { HInput } from '../../../shared/ui/HInput'
import { HButton } from '../../../shared/ui/HButton'
import { HSaveButton } from '../../../shared/ui/HSaveButton'
import { HCombobox } from '../../../shared/ui/HCombobox'
import { hrService } from '../services/HrService'
import { emptyEmployee, employeeInputSchema, employeeName, employmentTypes, typeLabels, employeeStatuses, statusLabels, type Employee, type EmployeeInput } from '../schemas/employees'
import { EmployeeAvatar } from './EmployeeAvatar'
export function EmployeeEditor({ record, employees, teams, writable, organisation, admin, onClose }: { record?: Employee; employees: Employee[]; teams: { id: string; name: string; active: boolean }[]; writable: boolean; organisation: boolean; admin: boolean; onClose: () => void }) {
  const [initial] = useState<EmployeeInput>(() => record ? { ...employeeInputSchema.parse(record), start_date: record.start_date.slice(0, 10), end_date: record.end_date.slice(0, 10) } : emptyEmployee)
  const [input, setInput] = useState(initial)
  const [photo, setPhoto] = useState<File>()
  const [removePhoto, setRemovePhoto] = useState(false)
  const [validation, setValidation] = useState('')
  const client = useQueryClient()
  const save = useMutation({ mutationFn: () => hrService.save(input, record, photo, removePhoto), onSuccess: async () => { await client.invalidateQueries({ queryKey: ['hr'] }); await client.invalidateQueries({ queryKey: ['access'] }); onClose() } })
  const dirty = JSON.stringify(input) !== JSON.stringify(initial) || Boolean(photo) || removePhoto
  const descendants = new Set<string>(record ? [record.id] : [])
  for (let index = 0; index < employees.length; index++) for (const person of employees) if (descendants.has(person.manager)) descendants.add(person.id)
  const text = (key: 'first_name' | 'last_name' | 'professional_email' | 'professional_phone' | 'job_title' | 'start_date' | 'end_date', label: string, type = 'text') => <label><HFieldLabel required={key === 'first_name' || key === 'last_name'}>{label}</HFieldLabel><HInput type={type} required={key === 'first_name' || key === 'last_name'} value={input[key]} onChange={(event) => setInput({ ...input, [key]: event.target.value })} /></label>
  return <HDialog open onOpenChange={(open) => { if (!open && !save.isPending) onClose() }} title={record ? employeeName(record) : 'Nouvel employé'} description="Une ressource peut être planifiée et apparaître dans l’organisation sans compte Horizon."><form className="hr-employee-editor" onSubmit={(event) => { event.preventDefault(); const result = employeeInputSchema.safeParse(input); if (!result.success) { setValidation('Vérifiez l’identité et les coordonnées.'); return }; setValidation(''); if (dirty && writable && !save.isPending) save.mutate() }}><fieldset disabled={!writable || save.isPending} className="access-fieldset"><HSectionHeading icon={UserRound} title="Identité et coordonnées" /><div className="contact-form-grid">{text('first_name', 'Prénom')}{text('last_name', 'Nom')}{text('job_title', 'Intitulé du poste') }<label><HFieldLabel required>Type de ressource</HFieldLabel><HCombobox label="Type de ressource" required showCodes={false} value={input.employment_type} onChange={(value) => setInput({ ...input, employment_type: employeeInputSchema.shape.employment_type.parse(value) })} options={employmentTypes.map((value) => ({ value, label: typeLabels[value] }))} /></label>{text('professional_email', 'E-mail professionnel', 'email')}{text('professional_phone', 'Téléphone professionnel') }<div className="hr-photo-field">{record && !removePhoto && <EmployeeAvatar employee={record} />}<label>Photo<input type="file" aria-label="Photo de l’employé" accept="image/png,image/jpeg,image/webp" onChange={(event) => { setPhoto(event.target.files?.[0]); setRemovePhoto(false) }} /></label>{photo && <small>{photo.name}</small>}{record?.avatar && <HButton variant="ghost" size="small" onClick={() => { setRemovePhoto(true); setPhoto(undefined) }}>Retirer</HButton>}</div></div></fieldset>
    <fieldset disabled={!writable || save.isPending} className="access-fieldset"><HSectionHeading icon={Network} title="Organisation" description="Le poste reste descriptif. Direction encadre managers et collaborateurs. Les responsabilités et les droits ERP sont indépendants." /><div className="contact-form-grid"><label>Équipe<HCombobox label="Équipe de l’employé" value={input.team} disabled={!organisation} showCodes={false} options={teams.filter((item) => item.active || item.id === input.team).map((item) => ({ value: item.id, label: item.name }))} onChange={(team) => setInput({ ...input, team })} /></label><label>Responsable principal<HCombobox label="Responsable principal" value={input.manager} disabled={!organisation} showCodes={false} options={employees.filter((item) => item.status === 'active' && (item.is_manager || item.is_direction) && (!input.is_direction || item.is_direction) && !descendants.has(item.id)).map((item) => ({ value: item.id, label: employeeName(item) }))} onChange={(manager) => setInput({ ...input, manager })} /></label><label><HFieldLabel required>Responsabilité</HFieldLabel><HCombobox label="Responsabilité organisationnelle" required showCodes={false} disabled={!organisation} value={input.is_direction ? "direction" : input.is_manager ? "manager" : "employee"} options={[{ value: "employee", label: "Collaborateur" }, { value: "manager", label: "Manager" }, { value: "direction", label: "Direction" }]} onChange={(value) => setInput({ ...input, is_manager: value === "manager", is_direction: value === "direction" })} /></label><label><HFieldLabel required>Statut</HFieldLabel><HCombobox label="Statut de l’employé" required showCodes={false} disabled={!organisation} value={input.status} onChange={(value) => setInput({ ...input, status: employeeInputSchema.shape.status.parse(value) })} options={employeeStatuses.map((value) => ({ value, label: statusLabels[value] }))} /></label>{text('start_date', 'Date de début', 'date')}{text('end_date', 'Date de fin', 'date')}</div></fieldset>
    {admin && <div className="hr-account-link"><Building2 size={15} /><span>{record?.has_account ? `Compte Horizon ${record.account_active ? 'actif' : 'désactivé'}` : 'Aucun compte Horizon lié'}</span><HButton asChild size="small"><Link to={record?.account_id ? `/settings/users?user=${record.account_id}` : `/settings/users`}>Gérer les accès</Link></HButton></div>}{validation && <p role="alert" className="field-error">{validation}</p>}{save.error && <p role="alert" className="field-error">{save.error.message}</p>}<div className="contact-form-actions"><HButton disabled={save.isPending} onClick={onClose}>{writable ? 'Annuler' : 'Fermer'}</HButton>{writable && <HSaveButton hasChanges={dirty} pending={save.isPending}>Enregistrer</HSaveButton>}</div></form></HDialog>
}
