import { test, expect, type Page } from '@playwright/test'
const password = 'Local-Horizon-test-only-2026!'
async function login(page: Page, email: string) {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail', { exact: true }).fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
}
test('Accès et Employés : équipe, hiérarchie, photo protégée, compte Viewer et organigramme', async ({ page }) => {
  await login(page, 'erp-admin@local.invalid')
  await page.goto('/hr')
  await page.getByRole('tab', { name: 'Équipes', exact: true }).click()
  await expect(page.getByRole('searchbox', { name: 'Rechercher une équipe', exact: true })).toBeVisible()
  await expect(page.locator('.page-breadcrumb-record-actions').getByRole('button', { name: 'Nouvelle équipe', exact: true })).toBeVisible()
  await expect(page.getByRole('tabpanel').getByRole('heading', { name: /Équipes/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Nouvelle équipe', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await expect(dialog.locator('label .h-required-mark')).toHaveCount(1)
  await expect(dialog.locator('label .h-required-mark')).toHaveCSS('color', 'rgb(233, 0, 114)')
  await expect(dialog.getByLabel('Nom de l’équipe', { exact: true })).toHaveAttribute('required', '')
  await expect(dialog.getByLabel('Code', { exact: true })).toHaveCount(0)
  await expect(dialog.getByText('Active', { exact: true })).toHaveCount(0)
  await expect(dialog.getByRole('button', { name: 'Actions de la fiche', exact: true })).toHaveCount(0)
  await expect(dialog.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.screenshot({ path: '/private/tmp/horizon-new-team-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-new-team-mobile.png' })
  await page.setViewportSize({ width: 1280, height: 720 })
  await dialog.getByRole('button', { name: 'Annuler', exact: true }).click()
  await page.getByRole('button', { name: 'Passer en mode sombre' }).click()
  await page.getByRole('button', { name: 'Nouvelle équipe', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-new-team-dark.png' })
  await page.getByRole('dialog').getByRole('button', { name: 'Annuler', exact: true }).click()
  await page.getByRole('button', { name: 'Passer en mode clair' }).click()
  await page.getByRole('button', { name: 'Nouvelle équipe', exact: true }).click()
  await dialog.getByLabel('Nom de l’équipe', { exact: true }).fill('Bureau d’études')
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('tab', { name: 'Employés', exact: true }).click()
  await page.getByRole('button', { name: 'Nouvel employé' }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Prénom', { exact: true }).fill('Alice')
  await dialog.getByLabel('Nom', { exact: true }).fill('Direction')
  await dialog.getByRole('combobox', { name: 'Responsabilité organisationnelle', exact: true }).click()
  await page.getByRole('option', { name: 'Direction', exact: true }).click()
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: 'Alice Direction' })).toContainText('Sans compte')
  await page.getByRole('button', { name: 'Nouvel employé' }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Prénom', { exact: true }).fill('Marie')
  await dialog.getByLabel('Nom', { exact: true }).fill('Martin')
  await dialog.getByLabel('Intitulé du poste', { exact: true }).fill('Responsable bureau d’études')
  await dialog.getByRole('combobox', { name: 'Responsabilité organisationnelle', exact: true }).click()
  await page.getByRole('option', { name: 'Manager', exact: true }).click()
  await dialog.getByRole('combobox', { name: 'Responsable principal', exact: true }).click()
  await page.getByRole('option', { name: 'Alice Direction', exact: true }).click()
  await dialog.getByRole('combobox', { name: 'Équipe de l’employé', exact: true }).click()
  await page.getByRole('option', { name: 'Bureau d’études', exact: true }).click()
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: 'Nouvel employé' }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Prénom', { exact: true }).fill('Paul')
  await dialog.getByLabel('Nom', { exact: true }).fill('Durand')
  await dialog.getByRole('combobox', { name: 'Responsable principal', exact: true }).click()
  await page.getByRole('option', { name: 'Marie Martin', exact: true }).click()
  await dialog.getByLabel('Photo de l’employé').setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') })
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  const row = page.getByRole('row').filter({ hasText: 'Paul Durand' })
  await expect(row).toContainText('Sans compte')
  await expect(row.locator('img')).toBeVisible()
  await page.getByRole('tab', { name: 'Équipes', exact: true }).click()
  const teamRow = page.getByRole('row').filter({ has: page.getByRole('button', { name: 'Ouvrir l’équipe Bureau d’études', exact: true }) })
  await expect(teamRow.getByRole('button', { name: 'Modifier Bureau d’études', exact: true })).toHaveCount(0)
  await teamRow.click()

  dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Ajouter : Managers de l’équipe', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Marie Martin', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Alice Direction', exact: true }).check()
  await page.keyboard.press('Escape')
  await page.screenshot({ path: '/private/tmp/horizon-team-editor.png' })
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: 'Bureau d’études' })).toContainText('Marie Martin')
  await expect(page.getByRole('row').filter({ hasText: 'Bureau d’études' })).toContainText('Alice Direction')
  await page.screenshot({ path: '/private/tmp/horizon-teams.png', fullPage: true })
  await page.getByRole('button', { name: 'Ouvrir l’équipe Bureau d’études', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Nom de l’équipe', { exact: true }).fill('Nom non enregistré')
  const actions = dialog.getByRole('button', { name: 'Actions de la fiche', exact: true })
  await expect(dialog.locator('.dialog-heading').getByRole('button', { name: 'Actions de la fiche', exact: true })).toBeVisible()
  await expect(actions).toBeEnabled()
  await actions.click()
  await page.getByRole('menuitem', { name: 'Archiver', exact: true }).click()
  const confirmation = page.getByRole('alertdialog')
  await confirmation.getByRole('textbox').fill('ARCHIVER')
  await confirmation.getByRole('button', { name: 'Archiver', exact: true }).click()
  await expect(confirmation).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: 'Bureau d’études' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Filtres de recherche', exact: true }).click()
  await page.getByRole('radio', { name: 'Archivées', exact: true }).locator('..').click()
  await page.getByRole('button', { name: 'Terminé', exact: true }).click()
  await page.getByRole('button', { name: 'Ouvrir l’équipe Bureau d’études', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Actions de la fiche', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Réactiver', exact: true }).click()
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('tab', { name: 'Employés', exact: true }).click()
  await page.getByRole('button', { name: 'Filtres de recherche', exact: true }).click()
  let panel = page.getByRole('dialog', { name: 'Filtres de recherche', exact: true })
  await expect(panel.locator('.search-options-columns > section')).toHaveCount(2)
  await panel.getByRole('radio', { name: 'Responsabilité', exact: true }).locator('..').click()
  await panel.getByRole('combobox', { name: 'Trier les employés', exact: true }).click()
  await page.getByRole('option', { name: 'Nom : Z → A', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Filtres de recherche, 2 actifs', exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-employees-filters.png' })
  await panel.getByRole('button', { name: 'Terminé', exact: true }).click()
  await expect(page.locator('.record-group')).toHaveCount(3)
  await expect(page.locator('.record-group > header')).toContainText(['Collaborateur', 'Direction', 'Manager'])
  await page.getByRole('button', { name: 'Filtres de recherche, 2 actifs', exact: true }).click()
  await page.getByRole('radio', { name: 'Équipe', exact: true }).locator('..').click()
  await page.getByRole('button', { name: 'Terminé', exact: true }).click()
  const unassigned = page.locator('.record-group').filter({ has: page.getByRole('heading', { name: 'Sans équipe', exact: true }) })
  await expect(unassigned.locator('tbody .h-data-table-record-name')).toHaveText(['Paul Durand', 'Alice Direction'])
  await page.getByRole('button', { name: 'Filtres de recherche, 2 actifs', exact: true }).click()
  await page.getByRole('radio', { name: 'Responsabilité', exact: true }).locator('..').click()
  await page.getByRole('button', { name: 'Terminé', exact: true }).click()
  await page.reload()
  await expect(page.locator('.record-group')).toHaveCount(3)
  await page.getByRole('button', { name: 'Filtres de recherche, 2 actifs', exact: true }).click()
  await page.getByRole('button', { name: 'Réinitialiser', exact: true }).click()
  await page.getByRole('button', { name: 'Terminé', exact: true }).click()
  await expect(page.locator('.record-group')).toHaveCount(0)
  const employeeSearch = page.getByRole('searchbox', { name: 'Rechercher un employé', exact: true })
  await expect(employeeSearch).toHaveCount(1)
  expect(await employeeSearch.locator('xpath=ancestor::header').count()).toBe(1)
  await employeeSearch.fill('Marie')
  await page.getByRole('button', { name: 'Filtres de recherche', exact: true }).click()
  await page.getByRole('radio', { name: 'Bureau d’études', exact: true }).locator('..').click()
  await expect(page.getByRole('radio', { name: 'Bureau d’études', exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Terminé', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ouvrir la fiche de Paul Durand', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Organigramme', exact: true }).click()
  await expect(employeeSearch).toHaveValue('Marie')
  await expect(page.locator('.hr-org-card')).toHaveCount(1)
  await page.reload()
  await expect(employeeSearch).toHaveValue('Marie')
  await expect(page.locator('.hr-org-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Marie Martin', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Annuler', exact: true }).click()
  await expect(employeeSearch).toHaveValue('Marie')
  await page.getByRole('button', { name: 'Filtres de recherche, 1 actif', exact: true }).click()
  await page.getByRole('button', { name: 'Réinitialiser', exact: true }).click()
  await expect(employeeSearch).toHaveValue('Marie')
  await page.getByRole('button', { name: 'Terminé', exact: true }).click()
  await employeeSearch.fill('')
  await page.getByRole('button', { name: 'Organigramme', exact: true }).click()
  await expect(page.locator('.hr-org-card')).toHaveCount(3)
  await page.getByRole('button', { name: 'Replier Marie Martin', exact: true }).click()
  await expect(page.locator('.hr-org-card')).toHaveCount(2)
  await page.getByRole('button', { name: 'Déplier Marie Martin', exact: true }).click()
  await expect(page.locator('.hr-org-card').filter({ hasText: 'Alice Direction' })).toContainText('Direction · 1')
  await page.getByRole('button', { name: 'Replier Alice Direction', exact: true }).click()
  await expect(page.locator('.hr-org-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Déplier Alice Direction', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-hr-organigramme.png', fullPage: true })
  await page.getByRole('button', { name: 'Passer en mode sombre' }).click()
  await page.screenshot({ path: '/private/tmp/horizon-hr-organigramme-dark.png', fullPage: true })
  await page.getByRole('button', { name: 'Passer en mode clair' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-hr-organigramme-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.goto('/settings/users')
  await expect(page.getByRole('heading', { name: 'Utilisateurs et accès', exact: true })).toBeVisible()
  await expect(page.locator('.page-breadcrumb-record-actions').getByRole('button', { name: 'Nouvel utilisateur', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Nouvel utilisateur', exact: true }).click()
  dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await dialog.getByLabel('Nom affiché', { exact: true }).fill('Paul Durand')
  await dialog.getByLabel('E-mail de connexion', { exact: true }).fill('hr-viewer@local.invalid')
  await dialog.getByLabel('Mot de passe initial', { exact: true }).fill(password)
  await dialog.getByRole('combobox', { name: 'Employé lié', exact: true }).click()
  await page.getByRole('option', { name: 'Paul Durand', exact: true }).click()
  await dialog.getByRole('combobox', { name: 'Profil ERP', exact: true }).click()
  await page.getByRole('option', { name: 'Viewer', exact: true }).click()
  await dialog.getByRole('checkbox', { name: 'Employés · Consulter', exact: true }).check()
  await dialog.getByRole('combobox', { name: 'Périmètre Employés', exact: true }).click()
  await page.getByRole('option', { name: 'Soi-même', exact: true }).click()
  await expect(dialog.getByRole('checkbox', { name: 'Employés · Contribuer', exact: true })).toBeDisabled()
  await page.screenshot({ path: '/private/tmp/horizon-access-editor.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '/private/tmp/horizon-access-editor-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1280, height: 720 })
  await expect(dialog.getByRole('heading', { name: 'Nouvel utilisateur', exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: 'hr-viewer@local.invalid' })).toContainText('Viewer')
  await page.getByRole('button', { name: 'Filtres de recherche', exact: true }).click()
  panel = page.getByRole('dialog', { name: 'Filtres de recherche', exact: true })
  await expect(panel.locator('.search-options-columns > section')).toHaveCount(2)
  await panel.getByRole('radio', { name: 'Profil ERP', exact: true }).locator('..').click()
  await panel.getByRole('combobox', { name: 'Trier les utilisateurs', exact: true }).click()
  await page.getByRole('option', { name: 'E-mail : Z → A', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-users-filters.png' })
  await panel.getByRole('button', { name: 'Terminé', exact: true }).click()
  await expect(page.locator('.record-group').filter({ hasText: 'hr-viewer@local.invalid' }).locator('header')).toContainText('Viewer')
  const userEmails = await page.locator('.record-group').filter({ has: page.getByRole('heading', { name: 'User', exact: true }) }).locator('tbody td:first-child small').allTextContents()
  expect(userEmails.length).toBeGreaterThan(1)
  expect(userEmails).toEqual([...userEmails].sort((a, b) => b.localeCompare(a, 'fr', { sensitivity: 'base', numeric: true })))
  await page.screenshot({ path: '/private/tmp/horizon-users-grouped.png', fullPage: true })
  await page.getByRole('button', { name: 'Filtres de recherche, 2 actifs', exact: true }).click()
  await page.getByRole('button', { name: 'Réinitialiser', exact: true }).click()
  await page.getByRole('button', { name: 'Terminé', exact: true }).click()
  const userSearch = page.getByRole('searchbox', { name: 'Rechercher un utilisateur', exact: true })
  await expect(userSearch).toHaveCount(1)
  expect(await userSearch.locator('xpath=ancestor::header').count()).toBe(1)
  await userSearch.fill('Paul')
  await page.getByRole('button', { name: 'Filtres de recherche', exact: true }).click()
  await page.getByRole('radio', { name: 'Viewer', exact: true }).locator('..').click()
  await expect(page.getByRole('radio', { name: 'Viewer', exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Terminé', exact: true }).click()
  await page.reload()
  await expect(userSearch).toHaveValue('Paul')
  await expect(page.getByRole('row').filter({ hasText: 'hr-viewer@local.invalid' })).toBeVisible()
  await page.getByRole('button', { name: 'Modifier Paul Durand', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Annuler', exact: true }).click()
  await expect(userSearch).toHaveValue('Paul')
  await expect(page).toHaveURL(/profile=viewer/)
  await page.getByRole('button', { name: 'Retirer le filtre Profil ERP : Viewer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Retirer le filtre Profil ERP : Viewer', exact: true })).toHaveCount(0)
  await userSearch.fill('')
  await expect(page).not.toHaveURL(/profile=viewer/)
  await page.screenshot({ path: '/private/tmp/horizon-access-users.png', fullPage: true })
  await page.getByRole('tab', { name: 'Tags', exact: true }).click()
  await expect(page.getByRole('searchbox', { name: 'Rechercher un tag', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Filtres de recherche', exact: true })).toHaveCount(0)
  await expect(page.locator('tbody tr')).toHaveCount(7)
  for (const [label, color] of [['Direction', 'Vert'], ['Admin', 'Orange'], ['Collaborateur', 'Framboise']] as const) {
    await page.getByRole('button', { name: `Modifier ${label}`, exact: true }).click()
    const colors = page.getByRole('dialog')
    await expect(colors.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
    await expect(colors.getByRole('radio')).toHaveCount(24)
    await expect(colors.getByLabel('Couleur personnalisée', { exact: true })).toHaveCount(1)
    await colors.getByRole('radio', { name: color, exact: true }).check()
    await colors.getByRole('button', { name: 'Enregistrer', exact: true }).click()
    await expect(colors).toHaveCount(0)
  }
  await page.getByRole('button', { name: 'Modifier Collaborateur', exact: true }).click()
  await expect(page.getByRole('radio', { name: 'Framboise', exact: true })).toBeChecked()
  await page.getByLabel('Couleur personnalisée', { exact: true }).evaluate((element) => {
    const input = element as HTMLInputElement
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set?.call(input, '#127a8b')
    input.dispatchEvent(new Event('input', { bubbles: true }))
    input.dispatchEvent(new Event('change', { bubbles: true }))
  })
  await expect(page.locator('.h-custom-color')).toHaveAttribute('data-selected', 'true')
  await page.screenshot({ path: '/private/tmp/horizon-tag-color-picker.png' })
  await page.getByRole('dialog').getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'Collaborateur', exact: true }) }).locator('.h-tag')).toHaveCSS('color', 'rgb(18, 122, 139)')
  await expect(page.getByRole('tab', { name: 'Tags', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'Direction', exact: true }) }).locator('.h-tag')).toHaveAttribute('data-tone', 'green')
  await page.screenshot({ path: '/private/tmp/horizon-identity-tags.png', fullPage: true })
  await page.getByRole('tab', { name: 'Utilisateurs', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: 'erp-admin@local.invalid' }).locator('.h-tag').first()).toHaveAttribute('data-tone', 'amber')
  await page.goto('/hr')
  const employeeRows = page.locator('.h-data-table tbody tr')
  await expect(employeeRows).toHaveCount(3)
  const backgrounds = await employeeRows.evaluateAll((rows) => rows.map((row) => getComputedStyle(row).backgroundColor))
  expect(backgrounds[0]).not.toEqual(backgrounds[1])
  await expect(page.getByRole('row').filter({ has: page.getByRole('button', { name: 'Ouvrir la fiche de Alice Direction', exact: true }) }).locator('.h-tag')).toHaveAttribute('data-tone', 'green')
  await page.getByRole('button', { name: 'Organigramme', exact: true }).click()
  await expect(page.locator('.hr-org-card').filter({ has: page.getByRole('button', { name: 'Alice Direction', exact: true }) }).locator('.h-tag')).toHaveAttribute('data-tone', 'green')

  await page.getByRole('button', { name: 'Menu utilisateur' }).click()
  await page.getByRole('menuitem', { name: 'Se déconnecter' }).click()
  await login(page, 'hr-viewer@local.invalid')
  await page.goto('/hr')
  await expect(page.getByRole('button', { name: 'Ouvrir la fiche de Paul Durand', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ouvrir la fiche de Marie Martin', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Nouvel employé' })).toHaveCount(0)
  await expect(page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('link', { name: 'Paramètres' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Ouvrir la fiche de Paul Durand', exact: true }).click()
  dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('Prénom', { exact: true })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: 'Enregistrer', exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Fermer', exact: true }).last().click()
  await page.getByRole('tab', { name: 'Équipes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Nouvelle équipe', exact: true })).toHaveCount(0)
  const readonlyTeam = page.getByRole('button', { name: 'Ouvrir l’équipe Bureau d’études', exact: true })
  await readonlyTeam.focus()
  await page.keyboard.press('Enter')
  dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('Nom de l’équipe', { exact: true })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: 'Actions de la fiche', exact: true })).toHaveCount(0)
  await expect(dialog.getByRole('button', { name: 'Enregistrer', exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Fermer', exact: true }).last().click()
  await page.goto('/settings')
  await expect(page.getByText('Le paramétrage est réservé à Admin et Superuser.')).toBeVisible()
})
