import { expect, test, type Locator } from '@playwright/test'

async function expectSquareWhiteFrame(frame: Locator, size: number) {
  await expect(frame).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  const bounds = await frame.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds?.width).toBe(size)
  expect(bounds?.height).toBe(size)
}

const password = 'Local-Horizon-test-only-2026!'
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64')
async function login(page: import('@playwright/test').Page, identity: string) {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail').fill(identity)
  await page.getByLabel('Mot de passe').fill(password)
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
}

test('société, rôles, adresse, personne et archivage sur un vrai PocketBase', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts')
  await page.getByRole('link', { name: 'Nouvelle société' }).click()
  const saveButton = page.getByRole('button', { name: 'Enregistrer', exact: true })
  await expect(saveButton).toBeDisabled()
  await expect(saveButton).toHaveClass(/h-button--secondary/)
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Acme e2e')
  await expect(saveButton).toBeEnabled()
  await expect(saveButton).toHaveClass(/h-button--primary/)
  await page.getByLabel('Raison sociale', { exact: true }).fill('Acme Engineering')
  await page.getByLabel('E-mail', { exact: true }).fill('contact@acme.invalid')
  await page.getByLabel('SIREN', { exact: true }).fill('123456789')
  await page.getByLabel('SIRET', { exact: true }).fill('12345678900001')
  await page.getByRole('combobox', { name: 'Devise', exact: true }).click()
  await page.getByRole('combobox', { name: 'Rechercher : Devise', exact: true }).fill('eur')
  await page.getByRole('option', { name: 'Euro EUR', exact: true }).click()
  await expect(page.getByLabel('Devise préférée')).toHaveCount(0)
  await page.getByLabel('Logo', { exact: true }).setInputFiles({ name: 'logo.png', mimeType: 'image/png', buffer: png })
  await expect(page.getByRole('heading', { name: 'Adresse du siège', exact: true })).toBeVisible()
  await page.getByLabel('Adresse', { exact: true }).fill('12 rue des Ateliers')
  await page.getByLabel('Ville', { exact: true }).fill('Paris')
  await page.getByRole('combobox', { name: 'Pays', exact: true }).click()
  await page.getByRole('option', { name: 'France FR', exact: true }).click()
  await page.getByLabel('Code postal', { exact: true }).fill('75001')
  await expect(page.getByRole('img', { name: 'Aperçu du nouvel logo' })).toBeVisible()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Acme e2e', exact: true })).toBeVisible()
  await expect(saveButton).toBeDisabled()
  await page.getByLabel('Ville', { exact: true }).fill('Lyon')
  await expect(saveButton).toBeEnabled()
  await page.getByLabel('Ville', { exact: true }).fill('Paris')
  await expect(saveButton).toBeDisabled()
  await page.getByRole('button', { name: 'Retirer l’image actuelle', exact: true }).click()
  await expect(saveButton).toBeEnabled()
  await page.getByRole('button', { name: 'Conserver l’image actuelle', exact: true }).click()
  await expect(saveButton).toBeDisabled()
  let roleWrites = 0
  page.on('request', (request) => {
    if (request.url().includes('/api/collections/contacts_company_roles/records') && ['POST', 'PATCH', 'DELETE'].includes(request.method())) roleWrites++
  })
  await page.getByRole('checkbox', { name: 'Client', exact: true }).check()
  await expect(saveButton).toBeEnabled()
  await page.getByRole('checkbox', { name: 'Client', exact: true }).uncheck()
  await expect(saveButton).toBeDisabled()
  await page.getByRole('checkbox', { name: 'Client', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Fournisseur', exact: true }).check()
  expect(roleWrites).toBe(0)
  await page.reload()
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).not.toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Fournisseur', exact: true })).not.toBeChecked()
  await page.getByRole('checkbox', { name: 'Client', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Fournisseur', exact: true }).check()
  await saveButton.click()
  await expect(saveButton).toBeDisabled()
  expect(roleWrites).toBe(2)
  await page.reload()
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Fournisseur', exact: true })).toBeChecked()
  await page.getByRole('checkbox', { name: 'Fournisseur', exact: true }).uncheck()
  await saveButton.click()
  await expect(saveButton).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('checkbox', { name: 'Fournisseur', exact: true })).not.toBeChecked()
  await page.getByRole('checkbox', { name: 'Fournisseur', exact: true }).check()
  await saveButton.click()
  await expect(saveButton).toBeDisabled()
  await expect(page.getByLabel('Adresse', { exact: true })).toHaveValue('12 rue des Ateliers')
  await expect(page.getByRole('heading', { name: 'Adresse du siège', exact: true })).toBeVisible()
  await expect(page.getByText('Ajouter des images à la galerie', { exact: false })).toHaveCount(0)
  await page.screenshot({ path: '/private/tmp/horizon-company.png', fullPage: true })
  await page.getByRole('tab', { name: 'Relations', exact: true }).click()
  await page.getByRole('link', { name: 'Ajouter un contact' }).click()
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Acme e2e')
  await page.getByLabel('Prénom', { exact: true }).fill('Alice')
  await page.getByLabel('Nom', { exact: true }).fill('Martin')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Acme e2e', exact: true }).click()
  await page.getByLabel('Avatar', { exact: true }).setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: png })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Alice Martin', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Ouvrir la société Acme e2e', exact: true }).click()
  await page.getByRole('tab', { name: 'Relations', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Contacts associés', exact: false })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Alice Martin', exact: true })).toBeVisible()
  await page.goto('/contacts/people')
  await expect(page.getByRole('link', { name: 'Alice Martin', exact: true })).toBeVisible()
  const companyBadge = page.locator('.contact-directory-card').filter({ has: page.getByRole('link', { name: 'Alice Martin', exact: true }) }).locator('.contact-company-badge')
  await expect(companyBadge).toHaveCSS('width', '26px')
  await expect(companyBadge).toHaveCSS('object-fit', 'contain')
  await page.screenshot({ path: '/private/tmp/horizon-people.png', fullPage: true })
  await page.getByRole('button', { name: 'Vue liste', exact: true }).click()
  await expect(page.getByRole('row').filter({ has: page.getByRole('link', { name: 'Alice Martin', exact: true }) }).locator('.contact-company-badge')).toHaveCSS('width', '16px')
  await page.getByRole('link', { name: 'Alice Martin', exact: true }).click()
  await expect(saveButton).toBeDisabled()
  await page.getByLabel('Fonction', { exact: true }).fill('Responsable BE')
  await expect(saveButton).toBeEnabled()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByLabel('Fonction', { exact: true })).toHaveValue('Responsable BE')
  await expect(saveButton).toBeDisabled()
  await page.screenshot({ path: '/private/tmp/horizon-person-modern.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-person-modern-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  page.on('dialog', (dialog) => dialog.accept())
  const archiveTrigger = page.getByRole('button', { name: 'Actions de la fiche', exact: true })
  async function openArchive() { await archiveTrigger.click(); await page.getByRole('menuitem', { name: 'Archiver', exact: true }).click() }
  let archiveRequests = 0
  page.on('request', (request) => {
    if (request.method() === 'PATCH' && request.url().includes('/api/collections/contacts_people/records/')) archiveRequests++
  })
  await openArchive()
  const confirmationDialog = page.getByRole('alertdialog', { name: 'Confirmer l’archivage', exact: true })
  const confirmationInput = confirmationDialog.getByRole('textbox', { name: 'Saisissez ARCHIVER pour confirmer', exact: true })
  const archiveConfirm = confirmationDialog.getByRole('button', { name: 'Archiver', exact: true })
  await expect(confirmationInput).toBeFocused()
  await expect(confirmationDialog).toContainText('Alice Martin')
  await expect(archiveConfirm).toBeDisabled()
  await confirmationInput.press('Enter')
  for (const text of ['archiver', 'ARCHIVE', 'ARCHIVER ']) {
    await confirmationInput.fill(text)
    await expect(archiveConfirm).toBeDisabled()
  }
  await confirmationInput.fill('ARCHIVER')
  await expect(archiveConfirm).toBeEnabled()
  expect(archiveRequests).toBe(0)
  await confirmationDialog.getByRole('button', { name: 'Annuler', exact: true }).click()
  await expect(confirmationDialog).toBeHidden()
  await expect(archiveTrigger).toBeFocused()
  await openArchive()
  await expect(confirmationInput).toHaveValue('')
  await confirmationInput.press('Escape')
  await expect(confirmationDialog).toBeHidden()
  await openArchive()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await confirmationInput.fill('ARCHIVER')
  await expect(archiveConfirm).toBeEnabled()
  await expect(archiveConfirm).toHaveCSS('background-color', 'rgb(194, 65, 12)')
  await page.screenshot({ path: '/private/tmp/horizon-archive-confirmation-mobile.png', fullPage: true })
  const personPath = new URL(page.url()).pathname
  let rejectedArchive = false
  await page.route(`**/api/collections/contacts_people/records/${personPath.split('/').at(-1)}`, async (route) => {
    if (!rejectedArchive && route.request().method() === 'PATCH') {
      rejectedArchive = true
      await route.fulfill({ status: 403, json: { message: 'Archivage refusé pour ce test.' } })
    } else await route.continue()
  })
  await archiveConfirm.click()
  await expect(confirmationDialog.getByRole('alert')).toContainText('Cette action n’est pas autorisée.')
  await expect(archiveConfirm).toBeEnabled()
  await archiveConfirm.click()
  await expect(confirmationDialog).toBeHidden()
  await expect(page.locator('.contact-record-toolbar').getByText('Archivé', { exact: true })).toBeVisible()
  expect(archiveRequests).toBe(2)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/contacts/people')
  await expect(page.getByRole('link', { name: 'Alice Martin', exact: true })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'État des fiches', exact: true }).click()
  await page.getByRole('option', { name: 'Archivés', exact: true }).click()
  await page.getByRole('link', { name: 'Alice Martin', exact: true }).click()
  await page.getByRole('button', { name: 'Actions de la fiche', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Réactiver', exact: true }).click()
  await expect(page.locator('.contact-record-toolbar').getByText('Actif', { exact: true })).toBeVisible()
})

test('lecteur en lecture seule, utilisateur sans permission bloqué', async ({ page }) => {
  await login(page, 'reader@local.invalid')
  await page.goto('/contacts')
  await expect(page.getByRole('heading', { name: 'Contacts', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Nouvelle société' })).toHaveCount(0)
  await page.goto('/contacts/companies/new')
  await expect(page.getByRole('alert')).toHaveText('Vous ne disposez pas des permissions nécessaires.')
  await page.getByRole('button', { name: 'Menu utilisateur' }).click()
  await page.getByRole('menuitem', { name: 'Se déconnecter' }).click()
  await login(page, 'other@local.invalid')
  await page.goto('/contacts')
  await expect(page.getByRole('heading', { name: 'Accès aux contacts non autorisé' })).toBeVisible()
  await expect(page.locator('table')).toHaveCount(0)
})

test('validation, recherche et densité mobile', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByLabel('E-mail', { exact: true }).fill('validation@local.invalid')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByText('Saisissez un nom.')).toBeVisible()
  await page.goto('/contacts')
  await page.getByLabel('Rechercher dans les contacts').fill('inexistant-e2e')
  await expect(page.getByRole('heading', { name: 'Aucun résultat' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-contacts-mobile.png', fullPage: true })
})


test('référentiels administrables, choix clavier et consultation sans écriture', async ({ page }) => {
  await login(page, 'references@local.invalid')
  await page.goto('/settings/references')
  await page.getByRole('button', { name: 'Ajouter une valeur', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByLabel('Code', { exact: true }).fill('NO')
  await page.getByLabel('Libellé', { exact: true }).fill('Norvège')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Modifier NO', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Modifier NO', exact: true }).click()
  await expect(page.getByLabel('Code', { exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByLabel('Libellé', { exact: true }).fill('Norvège modifiée')
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeEnabled()
  await page.getByLabel('Libellé', { exact: true }).fill('Norvège')
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByLabel('Actif', { exact: true }).uncheck()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: 'Norvège' })).toContainText('Inactif')
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Référentiels clavier')
  await page.getByRole('combobox', { name: 'Langue', exact: true }).click()
  const search = page.getByRole('combobox', { name: 'Rechercher : Langue', exact: true })
  await search.fill('francais')
  await search.press('ArrowDown')
  await search.press('Enter')
  await expect(page.getByRole('combobox', { name: 'Langue', exact: true })).toHaveText('Français')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await page.getByRole('combobox', { name: 'Pays', exact: true }).click()
  await page.getByRole('combobox', { name: 'Rechercher : Pays', exact: true }).fill('Norvège')
  await expect(page.getByRole('option', { name: 'Norvège NO', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Menu utilisateur' }).click()
  await page.getByRole('menuitem', { name: 'Se déconnecter' }).click()
  await login(page, 'reader@local.invalid')
  await page.goto('/settings/references')
  await expect(page.getByRole('cell', { name: 'Norvège', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ajouter une valeur', exact: true })).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('ancien backend : édition bloquée sans sauvegarde silencieuse', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.route('**/api/horizon/company-lookup/status', (route) => route.fulfill({ status: 404, contentType: 'application/json', body: JSON.stringify({ message: 'Not found.', status: 404, data: {} }) }))
  let writes = 0
  page.on('request', (request) => { if (request.method() === 'POST' && request.url().includes('/collections/contacts_companies/records')) writes++ })
  await page.goto('/contacts/companies/new')
  await expect(page.getByRole('alert')).toContainText('Mise à jour PocketBase requise')
  await expect(page.getByLabel('Nom usuel *', { exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toHaveCount(0)
  expect(writes).toBe(0)
})

test('une ancienne requête retardée ne masque pas le contact nouvellement associé', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Société requête retardée')
  let notifyStarted!: () => void
  let release!: () => void
  const started = new Promise<void>((resolve) => { notifyStarted = resolve })
  const pending = new Promise<void>((resolve) => { release = resolve })
  let held = false
  await page.route(/api\/collections\/contacts_people\/records\?/, async (route) => {
    if (held || !new URL(route.request().url()).searchParams.get('filter')?.includes('company =')) return route.continue()
    held = true
    const response = await route.fetch()
    notifyStarted()
    await pending
    await route.fulfill({ response })
  })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await started
  await page.getByRole('tab', { name: 'Relations', exact: true }).click()
  await expect(page.getByRole('status', { name: 'Chargement des contacts associés', exact: true })).toBeVisible()
  await expect(page.getByText('Chargement des contacts…', { exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Ajouter un contact' }).click()
  await page.getByLabel('Prénom', { exact: true }).fill('Contact')
  await page.getByLabel('Nom', { exact: true }).fill('Retardé')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Contact Retardé', exact: true })).toBeVisible()
  release()
  await page.getByRole('link', { name: 'Ouvrir la société Société requête retardée', exact: true }).click()
  await page.getByRole('tab', { name: 'Relations', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Contact Retardé', exact: true })).toBeVisible()
})


test('adresse refusée : le formulaire reste renseigné et la société n’est pas créée deux fois', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Société adresse à reprendre')
  await page.getByLabel('Adresse', { exact: true }).fill('24 avenue de Test')
  await page.getByLabel('Ville', { exact: true }).fill('Paris')
  await page.getByRole('combobox', { name: 'Pays', exact: true }).click()
  await page.getByRole('option', { name: 'France FR', exact: true }).click()
  let companyCreations = 0
  page.on('request', (request) => { if (request.method() === 'POST' && request.url().includes('/collections/contacts_companies/records')) companyCreations++ })
  await page.route('**/api/collections/contacts_addresses/records', async (route) => {
    if (route.request().method() === 'POST') await route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ message: 'Address refused.', status: 400, data: {} }) })
    else await route.continue()
  })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('La société est enregistrée, mais son adresse ne l’est pas')
  await expect(page.getByLabel('Adresse', { exact: true })).toHaveValue('24 avenue de Test')
  await page.unroute('**/api/collections/contacts_addresses/records')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/companies\/(?!new)[a-z0-9]+$/)
  await expect(page.getByLabel('Adresse', { exact: true })).toHaveValue('24 avenue de Test')
  expect(companyCreations).toBe(1)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '/private/tmp/horizon-company-modern.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-company-modern-mobile.png', fullPage: true })
})

test('cartes et liste : mêmes fiches, recherche conservée et en-tête compact', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Atelier Présentation')
  await page.getByLabel('Raison sociale', { exact: true }).fill('Atelier Présentation SAS')
  await page.getByLabel('E-mail', { exact: true }).fill('bonjour@atelier.invalid')
  await page.getByLabel('Téléphone', { exact: true }).fill('01 23 45 67 89')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/companies\/(?!new).+/)
  await page.getByRole('checkbox', { name: 'Client', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Prospect', exact: true })).toHaveCount(0)
  await expect(page.getByRole('checkbox', { name: 'Partenaire', exact: true })).toHaveCount(0)
  await expect(page.getByRole('checkbox', { name: 'Autre', exact: true })).toHaveCount(0)
  await page.getByRole('checkbox', { name: 'Fournisseur', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Fournisseur', exact: true })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('checkbox', { name: 'Fournisseur', exact: true })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeChecked()
  const relations = await page.getByRole('heading', { name: 'Relation commerciale', exact: true }).boundingBox()
  const shortcuts = await page.getByRole('navigation', { name: 'Objets métier de la société', exact: true }).boundingBox()
  const identity = await page.getByRole('heading', { name: 'Identité', exact: true }).boundingBox()
  expect(relations!.y).toBeGreaterThan(identity!.y)
  expect(shortcuts!.y).toBeLessThan(identity!.y)
  await page.screenshot({ path: '/private/tmp/horizon-company-compact.png', fullPage: true })
  await page.getByRole('tab', { name: 'Relations', exact: true }).click()
  await page.getByRole('link', { name: 'Ajouter un contact', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Nouveau contact', exact: true })).toBeVisible()
  expect((await page.getByLabel('Prénom', { exact: true }).boundingBox())!.width).toBeGreaterThan(120)
  expect((await page.locator('.contact-identity-panel').boundingBox())!.width).toBeGreaterThan(500)
  await expect(page.getByLabel('Rechercher une société', { exact: true })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('combobox', { name: 'Rechercher : Société', exact: true }).fill('Atelier Présentation')
  await page.getByRole('option', { name: 'Atelier Présentation', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Atelier Présentation')
  await page.screenshot({ path: '/private/tmp/horizon-new-person-reference.png', fullPage: true })
  await page.getByLabel('Prénom', { exact: true }).fill('Camille')
  await page.getByLabel('Nom', { exact: true }).fill('Présentation')
  await page.getByLabel('Fonction', { exact: true }).fill('Direction commerciale')
  await page.getByLabel('E-mail', { exact: true }).fill('camille@atelier.invalid')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Relations commerciales de Atelier Présentation', exact: true })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeChecked()
  await expect(page.getByRole('navigation', { name: 'Objets métier de la société associée', exact: true })).toBeVisible()

  for (const [path, name] of [['/contacts', 'Atelier Présentation'], ['/contacts/people', 'Camille Présentation']] as const) {
    await page.goto(path)
    await expect(page.getByRole('button', { name: 'Vue cartes', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('link', { name, exact: true })).toBeVisible()
    await page.setViewportSize({ width: 1440, height: 1000 })
    const kind = path === '/contacts' ? 'companies' : 'people'
    await page.screenshot({ path: `/private/tmp/horizon-${kind}-cards.png`, fullPage: true })
    await page.getByLabel('Rechercher dans les contacts').fill(name)
    await expect(page.getByText('1 résultat(s)', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Vue liste', exact: true }).click()
    await expect(page.getByRole('table')).toBeVisible()
    await expect(page.getByLabel('Rechercher dans les contacts')).toHaveValue(name)
    await expect(page.getByRole('row').filter({ has: page.getByRole('link', { name, exact: true }) })).toBeVisible()
    await page.getByLabel('Rechercher dans les contacts').fill('')
    await page.screenshot({ path: `/private/tmp/horizon-${kind}-list.png`, fullPage: true })
    await page.reload()
    await expect(page.getByRole('button', { name: 'Vue liste', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await page.setViewportSize({ width: 390, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'Vue cartes', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Vue cartes', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByLabel('Fiches en cartes', { exact: true })).toBeVisible()
    await expect(page.getByRole('link', { name, exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: `/private/tmp/horizon-${kind}-cards-mobile.png`, fullPage: true })
  }
})

test('nouvelle charte : logo horizontal entier, synthèse réelle et onglets clavier', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  const logo = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 240; canvas.height = 60
    const context = canvas.getContext('2d')
    if (!context) throw new Error('Canvas indisponible')
    context.fillStyle = '#fff'; context.fillRect(0, 0, 240, 60)
    context.fillStyle = '#e90072'; context.fillRect(0, 0, 18, 60)
    context.fillStyle = '#091c3a'; context.fillRect(222, 0, 18, 60)
    context.font = 'bold 27px sans-serif'; context.fillText('ASTER', 70, 40)
    return canvas.toDataURL('image/png').split(',')[1] ?? ''
  })
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Aster Studio')
  await page.getByLabel('E-mail', { exact: true }).fill('bonjour@aster.invalid')
  await page.getByLabel('Téléphone', { exact: true }).fill('01 80 00 00 00')
  await page.getByLabel('Adresse', { exact: true }).fill('10 rue du Studio')
  await page.getByLabel('Ville', { exact: true }).fill('Paris')
  await page.getByRole('combobox', { name: 'Pays', exact: true }).click()
  await page.getByRole('option', { name: 'France FR', exact: true }).click()
  await page.getByLabel('Logo', { exact: true }).setInputFiles({ name: 'aster-horizontal.png', mimeType: 'image/png', buffer: Buffer.from(logo, 'base64') })
  await expect(page.getByRole('img', { name: 'Aperçu du nouvel logo' })).toHaveCSS('object-fit', 'contain')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Aster Studio', exact: true })).toBeVisible()
  await expect(page.locator('.contact-photo-control--companies img')).toBeVisible()
  await expect(page.locator('.contact-photo-control--companies img')).toHaveCSS('object-fit', 'contain')
  await expectSquareWhiteFrame(page.locator('.contact-photo-control--companies .contact-image-preview'), 128)
  await page.getByRole('checkbox', { name: 'Client', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeChecked()
  await expect(page.getByText('Enregistrement du rôle…', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '/private/tmp/horizon-redesign-record.png', fullPage: true })
  await page.getByRole('tab', { name: 'Informations', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: 'Relations', exact: true })).toBeFocused()
  await expect(page.getByRole('heading', { name: 'Contacts associés (0)', exact: true })).toBeVisible()
  await expect(page.getByLabel('Nom usuel *', { exact: true })).toBeHidden()
  await page.getByRole('tab', { name: 'Notes', exact: true }).click()
  await page.getByRole('textbox', { name: 'Notes', exact: true }).fill('Suivi commercial du studio.')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByText('Note enregistrée', { exact: true })).toHaveCount(1)
  await page.getByRole('tab', { name: 'Notes', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Notes', exact: true })).toHaveValue('Suivi commercial du studio.')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('tab', { name: 'Informations', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-redesign-record-mobile.png', fullPage: true })
  await page.goto('/contacts')
  const clients = page.getByRole('group', { name: 'Clients actifs', exact: true }).locator('strong')
  await expect(clients).toHaveText(/^[1-9]/)
  await page.getByLabel('Rechercher dans les contacts').fill('Aster')
  const card = page.locator('.contact-directory-card').filter({ has: page.getByRole('link', { name: 'Aster Studio', exact: true }) })
  await expect(card.locator('img.contact-logo-image')).toBeVisible()
  await expect(card.locator('img.contact-logo-image')).toHaveCSS('object-fit', 'contain')
  await expectSquareWhiteFrame(card.locator('.contact-avatar--company'), 64)
  await expect(card.getByText('Paris, France', { exact: true })).toBeVisible()
  const portrait = await card.locator('.contact-card-portrait').boundingBox()
  const heading = await card.locator('.contact-card-title').boundingBox()
  const coordinates = await card.locator('.contact-card-coordinates').boundingBox()
  expect(portrait!.x + portrait!.width).toBeLessThan(heading!.x)
  expect(coordinates!.x).toBe(heading!.x)
  await page.screenshot({ path: '/private/tmp/horizon-redesign-cards-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Vue liste', exact: true }).click()
  const row = page.getByRole('row').filter({ has: page.getByRole('link', { name: 'Aster Studio', exact: true }) })
  await expect(row.locator('img.contact-logo-image')).toBeVisible()
  await expect(row.locator('img.contact-logo-image')).toHaveCSS('object-fit', 'contain')
  await expectSquareWhiteFrame(row.locator('.contact-avatar--company'), 36)
  await page.getByLabel('Rechercher dans les contacts').fill('')
  await expect(page.getByRole('link', { name: 'Aster Studio', exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-redesign-list.png', fullPage: true })
})

test('paramètres organisés par domaine, référentiels accessibles et combobox intégrée', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/settings')
  await expect(page.locator('.settings-main').getByRole('heading', { name: 'Vue d’ensemble', exact: true })).toBeVisible()
  await expect(page.locator('.content-footer')).toHaveCount(0)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '/private/tmp/horizon-settings-overview.png', fullPage: true })
  await page.getByLabel('Rechercher dans les paramètres').fill('pipeline')
  await page.locator('.settings-main').getByRole('link').filter({ has: page.getByRole('heading', { name: 'CRM', exact: true }) }).click()
  await expect(page).toHaveURL('/settings/modules/crm')
  await expect(page.getByRole('heading', { name: 'Pipelines', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toHaveCount(0)
  await page.locator('.settings-navigation').getByRole('link', { name: 'Référentiels', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ajouter une valeur', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Langues', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Langues', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('cell', { name: 'Français', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-settings-mobile.png', fullPage: true })
  await page.goto('/contacts/companies/new')
  const country = page.getByRole('combobox', { name: 'Pays', exact: true })
  await country.click()
  const triggerBounds = await country.boundingBox()
  const chevronBounds = await country.locator('.h-combobox-chevron').boundingBox()
  expect(Math.abs(triggerBounds!.y + triggerBounds!.height / 2 - chevronBounds!.y - chevronBounds!.height / 2)).toBeLessThan(1)
  await page.getByRole('combobox', { name: 'Rechercher : Pays', exact: true }).fill('france')
  await expect(page.getByRole('option', { name: 'France FR', exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-combobox-menu-mobile.png', fullPage: true })
  await page.getByRole('option', { name: 'France FR', exact: true }).click()
  await expect(country).toHaveText('France')
  await expect(country).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('une seule recherche contextuelle, persistante entre les vues et après rechargement', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts?view=list')
  const search = page.getByRole('searchbox', { name: 'Rechercher dans les contacts' })
  await expect(search).toHaveCount(1)
  await expect(page.locator('.contact-toolbar input[type="search"]')).toHaveCount(0)
  await page.keyboard.press('Control+k')
  await expect(search).toBeFocused()
  await search.fill('Recherche introuvable 98654')
  await expect(page).toHaveURL(/q=Recherche/)
  await expect(page.getByRole('heading', { name: 'Aucun résultat', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Vue cartes' }).click()
  await expect(search).toHaveValue('Recherche introuvable 98654')
  await page.reload()
  await expect(search).toHaveValue('Recherche introuvable 98654')
  await expect(page.getByRole('heading', { name: 'Aucun résultat', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Effacer la recherche' }).click()
  await expect(search).toHaveValue('')
  await expect(search).toBeFocused()
  await expect(page).not.toHaveURL(/q=/)
  await page.getByRole('navigation', { name: 'Référentiel Contacts' }).getByRole('link', { name: 'Personnes' }).click()
  await expect(search).toHaveAttribute('placeholder', 'Rechercher une personne, une société…')
  await page.keyboard.press('Control+k')
  await expect(search).toBeFocused()
})

test('surface des cartes et lignes cliquable sans détourner les coordonnées', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Surface cliquable')
  await page.getByLabel('E-mail', { exact: true }).fill('surface@local.invalid')
  await page.getByLabel('Téléphone', { exact: true }).fill('0123456789')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/companies\/(?!new).+/)
  const destination = page.url()
  await page.goto('/contacts?q=Surface+cliquable&view=cards')
  const card = page.locator('.contact-directory-card').filter({ hasText: 'Surface cliquable' })
  await expect(card).toBeVisible()
  await page.evaluate(() => document.querySelector('a[href="mailto:surface@local.invalid"]')?.addEventListener('click', (event) => event.preventDefault(), { once: true }))
  await card.getByRole('link', { name: 'surface@local.invalid' }).click()
  await expect(page).toHaveURL(/view=cards/)
  await expect(card.locator('a[href="tel:0123456789"]')).toBeVisible()
  const bounds = await card.boundingBox()
  await card.click({ position: { x: bounds!.width - 6, y: bounds!.height - 6 } })
  await expect(page).toHaveURL(destination)
  await page.goto('/contacts?q=Surface+cliquable&view=list')
  const row = page.getByRole('row').filter({ hasText: 'Surface cliquable' })
  const cellBounds = await row.getByRole('cell', { name: 'Actif', exact: true }).boundingBox()
  const rowBounds = await row.boundingBox()
  await row.click({ position: { x: cellBounds!.x - rowBounds!.x + cellBounds!.width / 2, y: cellBounds!.height / 2 } })
  await expect(page).toHaveURL(destination)
  await page.goto('/contacts?q=Surface+cliquable&view=list')
  const link = page.getByRole('link', { name: 'Ouvrir la fiche de Surface cliquable', exact: true })
  await link.focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(destination)
})

test('relations disponibles dès la création et reprise sans doublon si un rôle est refusé', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  let companyCreates = 0
  page.on('request', (request) => {
    if (request.method() === 'POST' && new URL(request.url()).pathname === '/api/collections/contacts_companies/records') companyCreates++
  })
  await page.goto('/contacts/companies/new')
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Fournisseur', exact: true })).toBeVisible()
  await expectSquareWhiteFrame(page.getByLabel('Aperçu logo', { exact: true }), 128)
  await page.setViewportSize({ width: 1440, height: 1000 })
  const creationPanelClasses = await page.locator('.contact-main-column > .contact-panel').evaluateAll((panels) => panels.map((panel) => panel.className))
  const creationIdentity = await page.locator('.contact-identity-panel').boundingBox()
  await page.screenshot({ path: '/private/tmp/horizon-new-company-integrated.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Fournisseur', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-new-company-integrated-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('checkbox', { name: 'Client', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Fournisseur', exact: true }).check()
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Relations à la création')
  await page.getByLabel('Adresse', { exact: true }).fill('5 rue Test')
  await page.getByLabel('Ville', { exact: true }).fill('Paris')
  await page.getByRole('combobox', { name: 'Pays', exact: true }).click()
  await page.getByRole('option', { name: 'France FR', exact: true }).click()
  let rejected = false
  await page.route('**/api/collections/contacts_company_roles/records', async (route) => {
    if (route.request().method() === 'POST' && route.request().postDataJSON()?.role === 'supplier' && !rejected) {
      rejected = true
      await route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ status: 400, message: 'Role rejected', data: {} }) })
    } else await route.continue()
  })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('relations commerciales')
  await expect(page).toHaveURL('/contacts/companies/new')
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Fournisseur', exact: true })).toBeChecked()
  await expect(page.getByLabel('Adresse', { exact: true })).toHaveValue('5 rue Test')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/companies\/(?!new).+/)
  expect(companyCreates).toBe(1)
  await page.reload()
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Fournisseur', exact: true })).toBeChecked()
  await expect(page.getByLabel('Adresse', { exact: true })).toHaveValue('5 rue Test')
  expect(await page.locator('.contact-main-column > .contact-panel').evaluateAll((panels) => panels.map((panel) => panel.className))).toEqual(creationPanelClasses)
  const savedIdentity = await page.locator('.contact-identity-panel').boundingBox()
  expect(savedIdentity!.width).toBe(creationIdentity!.width)
  expect(savedIdentity!.height).toBe(creationIdentity!.height)
  await expectSquareWhiteFrame(page.getByLabel('Aperçu logo', { exact: true }), 128)
  await page.screenshot({ path: '/private/tmp/horizon-company-unified.png', fullPage: true })
})


test('recherche entreprises de l’État : création et report sans écriture avant Enregistrer', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  const publicRequests: string[] = []
  const relayRequests: string[] = []
  page.on('request', (request) => {
    if (/company-lookup\/(search|preview|apply)/.test(request.url())) relayRequests.push(request.url())
  })
  await page.route('https://recherche-entreprises.api.gouv.fr/search?*', (route) => {
    publicRequests.push(route.request().url())
    expect(route.request().headers().authorization).toBeUndefined()
    return route.fulfill({ json: { results: [{
      siren: '123456789', tva: ['FR99123456789'], nom_complet: 'Entreprise proposée', nom_raison_sociale: 'Entreprise proposée SAS', statut_diffusion: 'O',
      siege: { siret: '12345678900001', numero_voie: '8', type_voie: 'rue', libelle_voie: 'des Tests', code_postal: '75001', libelle_commune: 'Paris', adresse: '8 rue des Tests 75001 Paris', statut_diffusion_etablissement: 'O' },
    }] } })
  })
  await page.goto('/contacts/companies/new')
  let writes = 0
  page.on('request', (request) => {
    if (request.url().includes('/api/') && ['POST', 'PATCH', 'DELETE'].includes(request.method())) writes++
  })
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Entreprise recherchée')
  await page.getByLabel('Téléphone', { exact: true }).fill('01 23 45 67 89')
  await page.getByLabel('Numéro de TVA', { exact: true }).fill('FR00123456789')
  await expect(page.locator('.contact-record-actions').getByRole('button', { name: 'Recherche informations', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Recherche informations', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Recherche informations', exact: true })
  await expect(dialog.getByRole('textbox', { name: 'Nom, SIREN ou SIRET', exact: true })).toHaveValue('Entreprise recherchée')
  await dialog.getByRole('textbox', { name: 'Nom, SIREN ou SIRET', exact: true }).fill('12345678900001')
  await dialog.getByRole('textbox', { name: 'Nom, SIREN ou SIRET', exact: true }).press('Enter')
  await dialog.getByRole('button', { name: /Entreprise proposée SIRET/ }).click()
  await expect(dialog.getByRole('checkbox', { name: 'Reprendre Raison sociale', exact: true })).toBeChecked()
  await expect(dialog.getByRole('checkbox', { name: 'Reprendre l’adresse', exact: true })).toBeChecked()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect((await dialog.getByRole('textbox', { name: 'Nom, SIREN ou SIRET', exact: true }).boundingBox())!.height).toBeGreaterThanOrEqual(34)
  await expect(dialog.getByRole('button', { name: 'Remplir le formulaire', exact: true })).toBeEnabled()
  await expect(dialog.getByRole('button', { name: 'Remplir le formulaire', exact: true })).toHaveCSS('background-color', 'rgb(233, 0, 114)')
  await page.screenshot({ path: '/private/tmp/horizon-company-search-mobile.png' })
  await dialog.getByRole('button', { name: 'Remplir le formulaire', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByLabel('Nom usuel *', { exact: true })).toHaveValue('Entreprise proposée')
  await expect(page.getByLabel('Raison sociale', { exact: true })).toHaveValue('Entreprise proposée SAS')
  await expect(page.getByLabel('Adresse', { exact: true })).toHaveValue('8 rue des Tests')
  await expect(page.getByLabel('Téléphone', { exact: true })).toHaveValue('01 23 45 67 89')
  await expect(page.getByLabel('Numéro de TVA', { exact: true })).toHaveValue('FR99123456789')
  expect(writes).toBe(0)
  expect(publicRequests).toHaveLength(2)
  expect(publicRequests.every((url) => new URL(url).searchParams.get('q') === '12345678900001')).toBe(true)
  expect(relayRequests).toEqual([])
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '/private/tmp/horizon-company-gouv.png', fullPage: true })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  expect(writes).toBe(2)
  await page.reload()
  await expect(page.getByLabel('Raison sociale', { exact: true })).toHaveValue('Entreprise proposée SAS')
  await expect(page.getByLabel('Adresse', { exact: true })).toHaveValue('8 rue des Tests')
  await expect(page.getByRole('tab', { name: 'Enrichissement', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Recherche informations', exact: true }).click()
  await expect(dialog.getByRole('textbox', { name: 'Nom, SIREN ou SIRET', exact: true })).toHaveValue('12345678900001')
  await dialog.getByRole('button', { name: 'Annuler', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
})


test('un contact change de société uniquement après Enregistrer', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  const companyPaths: string[] = []
  for (const name of ['Société départ mobilité', 'Société arrivée mobilité']) {
    await page.goto('/contacts/companies/new')
    await page.getByLabel('Nom usuel *', { exact: true }).fill(name)
    await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
    await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
    companyPaths.push(new URL(page.url()).pathname)
  }
  await page.goto(`/contacts/people/new?company=${companyPaths[0]!.split('/').at(-1)}`)
  await page.getByLabel('Prénom', { exact: true }).fill('Contact')
  await page.getByLabel('Nom', { exact: true }).fill('Mobilité')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Contact Mobilité', exact: true })).toBeVisible()
  let writes = 0
  page.on('request', (request) => {
    if (request.url().includes('/api/collections/contacts_people/records/') && request.method() === 'PATCH') writes++
  })
  async function chooseArrivalCompany() {
    await page.getByRole('combobox', { name: 'Société', exact: true }).click()
    await page.getByRole('combobox', { name: 'Rechercher : Société', exact: true }).fill('Société arrivée mobilité')
    await page.getByRole('option', { name: 'Société arrivée mobilité', exact: true }).click()
  }
  await chooseArrivalCompany()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeEnabled()
  expect(writes).toBe(0)
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Société départ mobilité')
  await chooseArrivalCompany()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  expect(writes).toBe(1)
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Société arrivée mobilité')
  await page.goto(companyPaths[0]!)
  await page.getByRole('tab', { name: 'Relations', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Contacts associés (0)', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Contact Mobilité', exact: true })).toHaveCount(0)
  await page.goto(companyPaths[1]!)
  await page.getByRole('tab', { name: 'Relations', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Contact Mobilité', exact: true })).toBeVisible()
})

test('menu engrenage : duplication en brouillon et suppression confirmée protégée', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Société source duplication')
  await page.getByLabel('SIREN', { exact: true }).fill('123456789')
  await page.getByLabel('SIRET', { exact: true }).fill('12345678900001')
  await page.getByLabel('Adresse', { exact: true }).fill('10 rue Originale')
  await page.getByLabel('Ville', { exact: true }).fill('Paris')
  await page.getByRole('combobox', { name: 'Pays', exact: true }).click()
  await page.getByRole('option', { name: 'France FR', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Client', exact: true }).check()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Société source duplication', exact: true })).toBeVisible()
  const sourcePath = new URL(page.url()).pathname
  const gear = page.getByRole('button', { name: 'Actions de la fiche', exact: true })
  const save = page.getByRole('button', { name: 'Enregistrer', exact: true })
  expect((await gear.boundingBox())!.x).toBeGreaterThan((await save.boundingBox())!.x)
  await expect(page.getByRole('button', { name: 'Archiver', exact: true })).toHaveCount(0)
  let writes = 0
  page.on('request', (request) => { if (/\/api\/collections\/contacts_/.test(request.url()) && ['POST', 'PATCH', 'DELETE'].includes(request.method())) writes++ })
  await gear.click()
  await page.getByRole('menuitem', { name: 'Dupliquer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/companies\/new\?duplicate=/)
  await expect(page.getByLabel('Nom usuel *', { exact: true })).toHaveValue('Société source duplication (copie)')
  await expect(page.getByLabel('SIREN', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('SIRET', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Adresse', { exact: true })).toHaveValue('10 rue Originale')
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeChecked()
  expect(writes).toBe(0)
  await expect(save).toBeEnabled()
  await save.click()
  await expect(page.getByRole('heading', { name: 'Société source duplication (copie)', exact: true })).toBeVisible()
  expect(new URL(page.url()).pathname).not.toBe(sourcePath)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await gear.click()
  await page.getByRole('menuitem', { name: 'Supprimer', exact: true }).click()
  const dialog = page.getByRole('alertdialog', { name: 'Confirmer la suppression', exact: true })
  const input = dialog.getByRole('textbox', { name: 'Saisissez SUPPRIMER pour confirmer', exact: true })
  const confirm = dialog.getByRole('button', { name: 'Supprimer', exact: true })
  await expect(input).toBeFocused()
  for (const word of ['supprimer', 'SUPPRIME', 'SUPPRIMER ']) { await input.fill(word); await expect(confirm).toBeDisabled() }
  await input.fill('SUPPRIMER')
  await expect(confirm).toHaveCSS('background-color', 'rgb(220, 38, 38)')
  await page.screenshot({ path: '/private/tmp/horizon-delete-confirmation.png' })
  const beforeDelete = writes
  await dialog.getByRole('button', { name: 'Annuler', exact: true }).click()
  await expect(gear).toBeFocused()
  expect(writes).toBe(beforeDelete)
  await gear.click()
  await page.getByRole('menuitem', { name: 'Supprimer', exact: true }).click()
  await expect(input).toHaveValue('')
  await input.fill('SUPPRIMER')
  await confirm.click()
  await expect(page).toHaveURL('/contacts')
  await page.goto(sourcePath)
  await expect(page.getByLabel('Adresse', { exact: true })).toHaveValue('10 rue Originale')
  await page.goto(`/contacts/people/new?company=${sourcePath.split('/').at(-1)}`)
  await page.getByLabel('Nom', { exact: true }).fill('Contact lié protection')
  await save.click()
  await expect(page.getByRole('heading', { name: 'Contact lié protection', exact: true })).toBeVisible()
  await page.goto(sourcePath)
  await gear.click()
  await page.getByRole('menuitem', { name: 'Supprimer', exact: true }).click()
  await input.fill('SUPPRIMER')
  await confirm.click()
  await expect(dialog.getByRole('alert')).toContainText('pièces liées existent')
  await expect(page).toHaveURL(sourcePath)
  await dialog.getByRole('button', { name: 'Annuler', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Société source duplication', exact: true })).toBeVisible()
})

test('comptabilité : défauts, LEI et comptes sauvegardés explicitement avec reprise sans doublon', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  await expect(page.getByRole('combobox', { name: 'Langue', exact: true })).toHaveText('Français')
  await expect(page.getByRole('combobox', { name: 'Devise', exact: true })).toHaveText('Euro')
  await expect(page.getByLabel('Identifiant fiscal', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Numéro RCS', { exact: true })).toHaveCount(0)
  let writes = 0
  let creates = 0
  page.on('request', (request) => {
    if (request.url().includes('/api/collections/') && ['POST', 'PATCH', 'DELETE'].includes(request.method())) writes++
    if (request.url().endsWith('/api/collections/contacts_companies/records') && request.method() === 'POST') creates++
  })
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Comptabilité explicite')
  await page.getByLabel('LEI', { exact: true }).fill('506700ge1g29325qx363')
  await page.getByRole('checkbox', { name: 'Client', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Fournisseur', exact: true }).check()
  await page.getByRole('tab', { name: 'Comptabilité', exact: true }).click()
  await page.getByLabel('Compte client', { exact: true }).fill('411100')
  await page.getByLabel('Compte fournisseur', { exact: true }).fill('401100')
  await page.getByLabel('Adresse électronique de facturation', { exact: true }).fill('0225:123456789')
  await page.getByLabel('Plateforme agréée du tiers', { exact: true }).fill('Plateforme partenaire')
  await page.getByLabel('E-mail de facturation', { exact: true }).fill('facturation@local.invalid')
  await page.getByLabel('Code service destinataire', { exact: true }).fill('SERVICE01')
  await page.getByRole('combobox', { name: 'Préparation', exact: true }).click()
  await page.getByRole('option', { name: 'Informations renseignées', exact: true }).click()
  expect(writes).toBe(0)
  let rejected = false
  await page.route('**/api/collections/accounting_third_party_accounts/records', async (route) => {
    if (route.request().method() === 'POST' && route.request().postDataJSON()?.type === 'supplier' && !rejected) {
      rejected = true
      await route.fulfill({ status: 400, json: { message: 'Account rejected', data: {} } })
    } else await route.continue()
  })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('ses comptes ne le sont pas tous')
  await expect(page.getByLabel('Compte client', { exact: true })).toHaveValue('411100')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Comptabilité explicite', exact: true })).toBeVisible()
  expect(creates).toBe(1)
  await expect(page.getByRole('tab')).toHaveText(['Informations', 'Relations', 'Comptabilité', 'Notes'])
  await page.reload()
  await expect(page.getByLabel('LEI', { exact: true })).toHaveValue('506700GE1G29325QX363')
  await page.getByRole('tab', { name: 'Comptabilité', exact: true }).click()
  await expect(page.getByLabel('Compte client', { exact: true })).toHaveValue('411100')
  await expect(page.getByLabel('Compte fournisseur', { exact: true })).toHaveValue('401100')
  await expect(page.getByRole('combobox', { name: 'Préparation', exact: true })).toHaveText('Informations renseignées')
  await expect(page.getByLabel('Adresse électronique de facturation', { exact: true })).toHaveValue('0225:123456789')
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  const savedWrites = writes
  await page.getByLabel('Compte client', { exact: true }).fill('411200')
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeEnabled()
  expect(writes).toBe(savedWrites)
  await page.reload()
  await page.getByRole('tab', { name: 'Comptabilité', exact: true }).click()
  await expect(page.getByLabel('Compte client', { exact: true })).toHaveValue('411100')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-company-accounting-mobile.png', fullPage: true })
})

test('logos : recherche, sélection et aperçu sans écriture avant Enregistrer', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel *', { exact: true }).fill('TF1')
  let writes = 0
  page.on('request', (request) => {
    if (request.url().includes('/api/collections/') && ['POST', 'PATCH', 'DELETE'].includes(request.method())) writes++
  })
  await page.route('https://commons.wikimedia.org/w/api.php?**', async (route) => {
    await route.fulfill({ json: { query: { pages: [{ pageid: 1, index: 1, title: 'File:Logo TF1.svg', imageinfo: [{ url: 'https://upload.wikimedia.org/logo.svg', thumburl: 'https://thumb.wikimedia.org/test-logo.png', descriptionurl: 'https://commons.wikimedia.org/wiki/File:Logo_TF1.svg', mime: 'image/svg+xml', thumbmime: 'image/png', width: 400, height: 120 }] }] } } })
  })
  const logoPng = Buffer.from(await page.evaluate(async () => { const canvas = document.createElement('canvas'); canvas.width = 160; canvas.height = 60; const context = canvas.getContext('2d')!; context.fillStyle = '#091c3a'; context.fillRect(0, 0, 160, 60); context.fillStyle = '#ffffff'; context.font = 'bold 36px sans-serif'; context.fillText('TF1', 36, 43); return Array.from(new Uint8Array(await (await new Promise<Blob>((resolve) => canvas.toBlob((blob) => resolve(blob!), 'image/png'))).arrayBuffer())) }))
  await page.route('https://thumb.wikimedia.org/test-logo.png', (route) => route.fulfill({ body: logoPng, contentType: 'image/png', headers: { 'Access-Control-Allow-Origin': '*' } }))
  await page.getByRole('button', { name: 'Rechercher un logo', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Rechercher un logo', exact: true })
  await expect(dialog.getByLabel('Mots-clés du logo')).toHaveValue('TF1 logo')
  await expect(dialog.getByRole('button', { name: 'Utiliser ce logo', exact: true })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Rechercher', exact: true }).click()
  await dialog.getByRole('button', { name: 'Choisir Logo TF1.svg', exact: true }).click()
  await expect(dialog.getByRole('img', { name: 'Aperçu du logo sélectionné' })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-logo-search.png' })
  expect(writes).toBe(0)
  await dialog.getByRole('button', { name: 'Annuler', exact: true }).click()
  await expect(page.getByRole('img', { name: 'Aperçu du nouvel logo' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Rechercher un logo', exact: true }).click()
  await dialog.getByRole('button', { name: 'Rechercher', exact: true }).click()
  await dialog.getByRole('button', { name: 'Choisir Logo TF1.svg', exact: true }).click()
  await dialog.getByRole('button', { name: 'Utiliser ce logo', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('img', { name: 'Aperçu du nouvel logo' })).toBeVisible()
  expect(writes).toBe(0)
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'TF1', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.contact-image-preview img')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Rechercher un logo', exact: true }).click()
  await expect(dialog).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-logo-search-mobile.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('cloche : compteur réel, panneau et lecture réservée au destinataire', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  const bell = page.getByRole('button', { name: 'Notifications, 1 non lue', exact: true })
  await expect(bell).toBeVisible()
  await bell.click()
  await expect(page.getByText('Notification de recette', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-notifications.png' })
  await page.getByRole('button', { name: 'Marquer comme lue : Notification de recette', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Notifications', exact: true })).toBeVisible()
  await expect(page.getByText('0 non lues', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Notifications', exact: true })).toBeVisible()
})

test('fil complet : modifications groupées, document, mention, tâche et notifications', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  await expect(page.getByRole('region', { name: 'Fil d’activité' })).toHaveCount(0)
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Studio Horizon')
  await page.getByRole('checkbox', { name: 'Client', exact: true }).check()
  await page.getByLabel('Adresse', { exact: true }).fill('12 rue des Ateliers')
  await page.getByLabel('Ville', { exact: true }).fill('Paris')
  await page.getByRole('combobox', { name: 'Pays', exact: true }).click()
  await page.getByRole('option', { name: 'France FR', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Studio Horizon', exact: true })).toBeVisible()
  const sourceUrl = page.url()
  const panel = page.getByRole('region', { name: 'Fil d’activité' })
  await expect(panel.locator('.activity-timeline > li')).toHaveCount(1)
  await panel.locator('.activity-changes summary').click()
  await expect(panel.getByText('Relation Client', { exact: true })).toBeVisible()
  await expect(panel.getByText('Adresse · Ville', { exact: true })).toBeVisible()
  await page.getByLabel('Téléphone', { exact: true }).fill('01 42 00 00 00')
  await expect(panel.locator('.activity-timeline > li')).toHaveCount(1)
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(panel.locator('.activity-timeline > li')).toHaveCount(2)
  let writes = 0
  page.on('request', (request) => {
    if (request.url().includes('/api/collections/') && ['POST', 'PATCH', 'DELETE'].includes(request.method())) writes++
  })
  await panel.getByLabel('Message du fil').fill('Compte rendu : installation validée. Préparer la prochaine visite.')
  await panel.getByRole('button', { name: 'Mentionner', exact: true }).click()
  await panel.getByLabel('Rechercher une personne à mentionner').fill('Alice')
  await panel.locator('.activity-user-options').getByRole('button', { name: /Alice Martin/ }).click()
  await panel.getByLabel('Pièces jointes du fil').setInputFiles({ name: 'cadrage.txt', mimeType: 'text/plain', buffer: Buffer.from('Note interne pour la prochaine visite.') })
  await expect(panel.locator('.activity-draft-files')).toContainText('cadrage.txt')
  expect(writes).toBe(0)
  await panel.getByRole('button', { name: 'Publier', exact: true }).click()
  await expect(panel.locator('.activity-message').filter({ hasText: 'Compte rendu' })).toHaveCount(1)
  await expect(panel.locator('.activity-message--comment')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(panel.getByRole('link', { name: /cadrage.txt/ })).toBeVisible()
  await expect(panel.getByLabel('Message du fil')).toHaveValue('')
  await panel.getByRole('button', { name: 'Créer une tâche à partir de cette note', exact: true }).click()
  await panel.getByLabel('Titre de la tâche', { exact: true }).fill('Préparer le rendez-vous')
  await panel.locator('.activity-task-fields').getByRole('button', { name: 'Responsable', exact: true }).click()
  await panel.getByLabel('Rechercher un responsable').fill('Alice')
  await panel.locator('.activity-user-options').getByRole('button', { name: /Alice Martin/ }).click()
  await panel.getByLabel('Échéance de la tâche').fill('2026-10-15')
  await panel.getByRole('button', { name: 'Créer la tâche', exact: true }).click()
  await expect(panel.locator('.activity-task').getByText('Préparer le rendez-vous', { exact: true })).toBeVisible()
  await panel.getByRole('button', { name: 'Terminer', exact: true }).click()
  await expect(panel.getByRole('combobox', { name: 'État de la tâche : Préparer le rendez-vous' })).toHaveText('Terminée')
  await panel.getByRole('button', { name: 'Documents', exact: true }).click()
  await expect(panel.locator('.activity-timeline > li')).toHaveCount(1)
  await panel.getByRole('button', { name: 'Tout', exact: true }).click()
  await expect(panel.locator('.activity-timeline > li')).toHaveCount(5)
  await panel.scrollIntoViewIfNeeded()
  await panel.screenshot({ path: '/private/tmp/horizon-activity-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await panel.evaluate((element) => element.scrollIntoView({ block: 'start', behavior: 'instant' }))
  await panel.screenshot({ path: '/private/tmp/horizon-activity-mobile-full.png', animations: 'disabled' })
  await panel.evaluate((element) => element.scrollIntoView({ block: 'start', behavior: 'instant' }))
  await page.screenshot({ path: '/private/tmp/horizon-activity-mobile.png', animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const reader = await page.context().newPage()
  await login(reader, 'activity@local.invalid')
  await reader.getByRole('button', { name: /Notifications, .* non lue/ }).click()
  await expect(reader.getByText('Utilisateur test vous a mentionné', { exact: true })).toBeVisible()
  await reader.getByRole('link', { name: 'Voir la fiche', exact: true }).first().click()
  await expect(reader).toHaveURL(sourceUrl + '#activity')
  const readerPanel = reader.getByRole('region', { name: 'Fil d’activité' })
  await expect(readerPanel.getByLabel('Message du fil')).toHaveCount(0)
  await expect(readerPanel.locator('.activity-timeline > li')).toHaveCount(5)
  await expect(readerPanel.getByRole('combobox', { name: 'État de la tâche : Préparer le rendez-vous' })).toBeDisabled()
  await expect(readerPanel.getByRole('button', { name: 'Supprimer la pièce jointe cadrage.txt' })).toHaveCount(0)
  await reader.close()
  await panel.getByRole('button', { name: 'Supprimer la pièce jointe cadrage.txt' }).click()
  const confirmation = page.getByRole('alertdialog', { name: 'Confirmer la suppression' })
  await expect(confirmation.getByRole('button', { name: 'Supprimer', exact: true })).toBeDisabled()
  await confirmation.getByRole('button', { name: 'Annuler', exact: true }).click()
  await expect(panel.getByRole('link', { name: /cadrage.txt/ })).toBeVisible()
  await panel.getByRole('button', { name: 'Supprimer la pièce jointe cadrage.txt' }).click()
  await confirmation.getByRole('textbox').fill('SUPPRIMER')
  await confirmation.getByRole('button', { name: 'Supprimer', exact: true }).click()
  await expect(confirmation).toHaveCount(0)
  await expect(panel.getByRole('link', { name: /cadrage.txt/ })).toHaveCount(0)
  await expect(panel.getByText('Pièce jointe supprimée : cadrage.txt', { exact: true })).toBeVisible()
  await expect(panel.locator('.activity-message--comment')).toContainText('Compte rendu : installation validée.')
  await page.reload()
  await expect(panel.getByRole('link', { name: /cadrage.txt/ })).toHaveCount(0)
  await expect(panel.getByText('Pièce jointe supprimée : cadrage.txt', { exact: true })).toBeVisible()
})
