import { expect, test } from '@playwright/test'

const password = 'Local-Horizon-test-only-2026!'
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64')
async function login(page: import('@playwright/test').Page, identity: string) {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail').fill(identity)
  await page.getByLabel('Mot de passe').fill(password)
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
}

test('société, rôles, adresse, personne et archivage sur un vrai PocketBase', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts')
  await page.getByRole('link', { name: 'Nouvelle société' }).click()
  await page.getByLabel('Nom usuel *', { exact: true }).fill('Acme e2e')
  await page.getByLabel('Raison sociale', { exact: true }).fill('Acme Engineering')
  await page.getByLabel('E-mail', { exact: true }).fill('contact@acme.invalid')
  await page.getByLabel('Logo', { exact: true }).setInputFiles({ name: 'logo.png', mimeType: 'image/png', buffer: png })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Acme e2e', exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Client', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Client', exact: true })).toBeChecked()
  await page.getByRole('checkbox', { name: 'Fournisseur', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Fournisseur', exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Ajouter une adresse' }).click()
  await page.getByLabel('Adresse', { exact: true }).fill('12 rue des Ateliers')
  await page.getByLabel('Ville', { exact: true }).fill('Paris')
  await page.getByLabel('Code pays', { exact: true }).fill('FR')
  await page.getByLabel('Code postal', { exact: true }).fill('75001')
  await page.getByRole('button', { name: 'Enregistrer l’adresse' }).click()
  await expect(page.getByText('12 rue des Ateliers', { exact: false })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-company.png', fullPage: true })
  await page.goto('/contacts/people/new')
  await page.getByLabel('Prénom', { exact: true }).fill('Alice')
  await page.getByLabel('Nom', { exact: true }).fill('Martin')
  await page.getByLabel('Société', { exact: true }).selectOption({ label: 'Acme e2e' })
  await page.getByLabel('Avatar', { exact: true }).setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: png })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Alice Martin', exact: true })).toBeVisible()
  await page.goto('/contacts/people')
  await expect(page.getByRole('link', { name: 'Alice Martin', exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-people.png', fullPage: true })
  await page.getByRole('link', { name: 'Alice Martin', exact: true }).click()
  await page.getByLabel('Fonction', { exact: true }).fill('Responsable BE')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByLabel('Fonction', { exact: true })).toHaveValue('Responsable BE')
  page.on('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Archiver', exact: true }).click()
  await expect(page.getByText('Archivé', { exact: true })).toBeVisible()
  await page.goto('/contacts/people')
  await expect(page.getByRole('link', { name: 'Alice Martin', exact: true })).toHaveCount(0)
  await page.getByLabel('État des fiches').selectOption('archived')
  await page.getByRole('link', { name: 'Alice Martin', exact: true }).click()
  await page.getByRole('button', { name: 'Réactiver', exact: true }).click()
  await expect(page.getByText('Actif', { exact: true })).toBeVisible()
})

test('lecteur en lecture seule, utilisateur sans permission bloqué', async ({ page }) => {
  await login(page, 'reader@local.invalid')
  await page.goto('/contacts')
  await expect(page.getByRole('heading', { name: 'Contacts', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Nouvelle société' })).toHaveCount(0)
  await page.goto('/contacts/companies/new')
  await expect(page.getByRole('alert')).toHaveText('Vous ne disposez pas des permissions nécessaires.')
  await page.getByRole('button', { name: 'Se déconnecter' }).click()
  await login(page, 'other@local.invalid')
  await page.goto('/contacts')
  await expect(page.getByRole('heading', { name: 'Accès aux contacts non autorisé' })).toBeVisible()
  await expect(page.locator('table')).toHaveCount(0)
})

test('validation, recherche et densité mobile', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/contacts/companies/new')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByText('Saisissez un nom.')).toBeVisible()
  await page.goto('/contacts')
  await page.getByLabel('Rechercher dans les contacts').fill('inexistant-e2e')
  await expect(page.getByRole('heading', { name: 'Aucun résultat' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-contacts-mobile.png', fullPage: true })
})
