import { test, expect } from '@playwright/test'
import type { Page, Locator } from '@playwright/test'
async function login(page: Page, email = 'crm@local.invalid') {
  await page.goto('/login')
  await page.getByLabel('E-mail').fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill('Local-Horizon-test-only-2026!')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
}
test('CRM : création explicite, compte affaire, commentaire, Kanban automatique et recherche', async ({ page }) => {
  await login(page)
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel', { exact: true }).fill('Client du CRM')
  await page.getByLabel('Logo', { exact: true }).setInputFiles({ name: 'client-logo.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/companies\/(?!new)/)
  await page.goto('/crm')
  await expect(page.getByRole('heading', { name: 'CRM', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Nouvelle opportunité' }).click()
  const save = page.getByRole('button', { name: 'Enregistrer', exact: true })
  await expect(save).toBeDisabled()
  let writes = 0
  page.on('request', (request) => { if (request.url().includes('/horizon/crm/') && request.method() === 'POST') writes++ })
  await page.getByLabel('Titre', { exact: true }).fill('Studio Horizon')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client du CRM', exact: true }).click()
  await page.getByLabel('Montant estimé', { exact: true }).fill('12000')
  await page.getByLabel('Coût estimé', { exact: true }).fill('7000')
  await page.getByLabel('Probabilité (%)', { exact: true }).fill('30')
  await page.getByRole('button', { name: 'Ajouter : Types de marché', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Broadcast', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Corporate', exact: true }).check()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Retirer Broadcast', exact: true }).click()
  await page.getByRole('button', { name: 'Ajouter : Types de marché', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Broadcast', exact: true }).check()
  await page.keyboard.press('Escape')
  await page.getByRole('tab', { name: 'Description', exact: true }).click()
  const description = page.getByRole('textbox', { name: 'Contexte et besoins', exact: true })
  await description.fill('Besoins du studio')
  await description.press('ControlOrMeta+A')
  await page.getByRole('button', { name: 'Gras', exact: true }).click()
  await page.getByRole('button', { name: 'Liste numérotée', exact: true }).click()
  await page.getByRole('tab', { name: 'Informations', exact: true }).click()
  await page.getByRole('button', { name: 'Effacer : Société', exact: true }).click()
  await save.click()
  await expect(page.getByText('Vérifiez les champs du formulaire.', { exact: true })).toBeVisible()
  expect(writes).toBe(0)
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client du CRM', exact: true }).click()
  expect(writes).toBe(0)
  await save.click()
  await expect(page).toHaveURL(/\/crm\/opportunities\/(?!new)/)
  const recordUrl = page.url()
  await expect(save).toBeDisabled()
  await page.getByRole('tab', { name: 'Description', exact: true }).click()
  await expect(description.locator('ol strong')).toHaveText('Besoins du studio')
  await page.screenshot({ path: '/private/tmp/horizon-crm-description.png', fullPage: true })
  await page.getByRole('tab', { name: 'Informations', exact: true }).click()
  await expect(page.getByRole('group', { name: 'Types de marché', exact: true })).toContainText('Corporate')
  await expect(page.getByRole('group', { name: 'Types de marché', exact: true })).toContainText('Broadcast')
  await expect(page.locator('.crm-record-summary')).toContainText('Compte analytique')
  await expect(page.locator('.crm-record-summary')).toContainText('12 000')
  const number = await page.getByLabel('Numéro', { exact: true }).inputValue()
  await page.getByRole('textbox', { name: 'Message du fil' }).fill('Une note CRM')
  await page.getByLabel('Pièces jointes du fil').setInputFiles({ name: 'crm_note.txt', mimeType: 'text/plain', buffer: Buffer.from('Document de cadrage CRM') })
  await page.getByRole('button', { name: 'Publier', exact: true }).click()
  await expect(page.getByText('Une note CRM', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: /crm_note.txt/ })).toBeVisible()
  await page.getByRole('button', { name: 'Supprimer la pièce jointe crm_note.txt', exact: true }).click()
  const confirmation = page.getByRole('alertdialog', { name: 'Confirmer la suppression' })
  await confirmation.getByRole('textbox').fill('SUPPRIMER')
  await confirmation.getByRole('button', { name: 'Supprimer', exact: true }).click()
  await expect(page.getByRole('link', { name: /crm_note.txt/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Publier', exact: true })).toBeDisabled()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: '/private/tmp/horizon-crm-record.png', fullPage: true })
  await page.getByRole('navigation', { name: 'Fil d’Ariane' }).getByRole('link', { name: 'CRM', exact: true }).click()
  const card = page.locator('.crm-kanban .crm-opportunity-card').filter({ hasText: 'Studio Horizon' })
  await expect(card).toBeVisible()
  async function startDrag(target: Locator) {
    await expect(page.locator('.crm-drag-overlay')).not.toBeVisible()
    await card.scrollIntoViewIfNeeded()
    await card.click({ trial: true })
    const start = await card.boundingBox()
    const end = await target.boundingBox()
    if (!start || !end) throw new Error('Kanban non visible')
    await page.mouse.move(start.x + 40, start.y + 70)
    await page.mouse.down()
    await page.mouse.move(start.x + 55, start.y + 70, { steps: 5 })
    await page.mouse.move(end.x + Math.min(100, end.width / 2), end.y + 140, { steps: 25 })
    await expect(page.locator('.crm-drag-overlay')).toBeVisible()
    await expect(target.getByRole('button').first()).toHaveAttribute('aria-expanded', 'true')
    const destination = await target.boundingBox()
    if (!destination) throw new Error('Destination non visible')
    await page.mouse.move(destination.x + 100, destination.y + 140, { steps: 5 })
    await expect(target.locator('.crm-opportunity-card').filter({ hasText: 'Studio Horizon' })).toBeVisible()
  }
  await expect(card.locator('.crm-responsible-avatar')).toHaveAttribute('title', 'Responsable : Utilisateur test')
  await expect(card.getByRole('button')).toHaveCount(0)
  await expect(card.locator('.crm-company-logo img')).toBeVisible()
  await expect(card.locator('.crm-company-logo img')).toHaveCSS('object-fit', 'contain')
  const before = writes
  await startDrag(page.getByRole('region', { name: 'Étape Qualifié' }))
  const firstMove = page.waitForResponse((response) => response.url().endsWith('/horizon/crm/stages') && response.request().method() === 'POST')
  await page.mouse.up()
  expect((await firstMove).status()).toBe(200)
  await expect(page.getByRole('region', { name: 'Étape Qualifié' }).locator('.crm-opportunity-card').filter({ hasText: 'Studio Horizon' })).toBeVisible()
  const qualified = page.getByRole('region', { name: 'Étape Qualifié' })
  await expect(qualified.locator('.crm-column-total')).toContainText('12 000')
  await qualified.getByRole('button', { name: 'Replier Qualifié', exact: true }).click()
  await expect(qualified.locator('.crm-opportunity-card')).toHaveCount(0)
  await expect(qualified.locator('.crm-column-total')).toContainText('12 000')
  await page.screenshot({ path: '/private/tmp/horizon-crm-column-collapsed.png', fullPage: true })
  await qualified.getByRole('button', { name: 'Déplier Qualifié', exact: true }).click()
  await expect(card).toBeVisible()
  expect(writes).toBe(before + 1)
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toHaveCount(0)
  await page.getByRole('region', { name: 'Étape Nouveau' }).getByRole('button', { name: 'Replier Nouveau', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('region', { name: 'Étape Nouveau' }).getByRole('button', { name: 'Déplier Nouveau', exact: true })).toBeVisible()
  await page.getByRole('region', { name: 'Étape Nouveau' }).getByRole('button', { name: 'Déplier Nouveau', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Étape Qualifié' }).locator('.crm-opportunity-card').filter({ hasText: 'Studio Horizon' })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-crm-kanban.png', fullPage: true })
  await page.getByRole('link', { name: 'Nouvelle opportunité' }).click()
  await page.getByLabel('Titre', { exact: true }).fill('Seconde carte Kanban')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client du CRM', exact: true }).click()
  await page.getByRole('combobox', { name: 'Étape commerciale', exact: true }).click()
  await page.getByRole('option', { name: 'Gagné', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/opportunities\/(?!new)/)
  await page.getByRole('navigation', { name: 'Fil d’Ariane' }).getByRole('link', { name: 'CRM', exact: true }).click()
  const won = page.getByRole('region', { name: 'Étape Gagné' })
  await expect(won.locator('.crm-opportunity-card')).toHaveCount(1)
  const beforeDrag = writes
  async function beginDrag() { await startDrag(won) }
  await beginDrag()
  await page.screenshot({ path: '/private/tmp/horizon-crm-drag.png', fullPage: true })
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await expect(page.locator('.crm-drag-overlay')).not.toBeVisible()
  await expect(qualified.locator('.crm-opportunity-card').filter({ hasText: 'Studio Horizon' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toHaveCount(0)
  expect(writes).toBe(beforeDrag)
  await beginDrag()
  const dropped = page.waitForResponse((response) => response.url().endsWith('/horizon/crm/stages') && response.request().method() === 'POST')
  await page.mouse.up()
  expect((await dropped).status()).toBe(200)
  await expect(won.locator('.crm-opportunity-card')).toHaveCount(2)
  await expect(won.locator('.crm-opportunity-card .h-badge')).toHaveCount(0)
  expect(writes).toBe(beforeDrag + 1)
  await expect(page.locator('.crm-sortable-card[data-dragging=true]')).toHaveCount(0)
  await page.reload()
  await expect(won.locator('.crm-opportunity-card').filter({ hasText: 'Studio Horizon' })).toBeVisible()
  // A rejected concurrent move must restore the last saved position, with a visible error.
  await page.route('**/api/horizon/crm/stages', (route) => route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ status: 409, message: 'Cette opportunité a été modifiée par un collègue.', data: {} }) }))
  await startDrag(qualified)
  await page.mouse.up()
  await expect(page.getByRole('alert').filter({ hasText: 'Déplacement non enregistré' })).toBeVisible()
  await expect(won.locator('.crm-opportunity-card')).toHaveCount(2)
  await page.unroute('**/api/horizon/crm/stages')
  await startDrag(qualified)
  const restored = page.waitForResponse((response) => response.url().endsWith('/horizon/crm/stages') && response.request().method() === 'POST')
  await page.mouse.up()
  expect((await restored).status()).toBe(200)
  await expect(qualified.locator('.crm-opportunity-card').filter({ hasText: 'Studio Horizon' })).toBeVisible()
  await won.getByRole('button', { name: 'Replier Gagné', exact: true }).click()
  await beginDrag()
  // Hover unfolds before releasing the pointer; the opened state is retained.
  await expect(won.getByRole('button', { name: 'Replier Gagné', exact: true })).toBeVisible()
  const expanded = await won.boundingBox()
  if (!expanded) throw new Error('Destination non visible')
  await page.mouse.move(expanded.x + 100, expanded.y + 140, { steps: 10 })
  const unfoldedDrop = page.waitForResponse((response) => response.url().endsWith('/horizon/crm/stages') && response.request().method() === 'POST')
  await page.mouse.up()
  expect((await unfoldedDrop).status()).toBe(200)
  await expect(won.locator('.crm-opportunity-card')).toHaveCount(2)
  await page.reload()
  await expect(won.getByRole('button', { name: 'Replier Gagné', exact: true })).toBeVisible()
  await expect(won.locator('.crm-opportunity-card')).toHaveCount(2)
  await page.getByRole('searchbox', { name: 'Rechercher dans les opportunités' }).fill('Studio Horizon')
  await expect(card).toBeVisible()
  await page.getByRole('searchbox', { name: 'Rechercher dans les opportunités' }).fill('Absent de la recherche')
  await expect(card).toHaveCount(0)
  await page.getByRole('button', { name: 'Effacer la recherche' }).click()
  await page.getByRole('button', { name: 'Liste', exact: true }).click()
  const studioRow = page.getByRole('row').filter({ hasText: 'Studio Horizon' })
  await expect(studioRow.getByRole('cell').first()).toHaveText(number)
  await expect(studioRow.locator('.h-tag').filter({ hasText: 'Gagné' })).toHaveAttribute('data-tone', 'green')
  await expect(studioRow.locator('.h-tag').filter({ hasText: 'Broadcast' })).toHaveCount(1)
  await expect(studioRow.locator('.h-tag').filter({ hasText: 'Corporate' })).toHaveCount(1)
  await expect(studioRow.locator('.crm-responsible-avatar')).toBeVisible()
  await expect(studioRow.locator('.crm-company-logo img')).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Code' })).toBeVisible()
  await page.getByRole('columnheader', { name: 'Code' }).click()
  await expect(page).toHaveURL(/sort=opportunity_number/)
  await page.getByRole('columnheader', { name: 'Code' }).click()
  await expect(page).toHaveURL(/sort=-opportunity_number/)
  await page.getByRole('link', { name: 'Ouvrir l’opportunité Studio Horizon' }).click()
  await expect(page).toHaveURL(recordUrl)
  await expect(page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('link', { name: 'CRM', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-crm-record-mobile.png', fullPage: true })
  await page.goto('/crm')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-crm-kanban-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await expect(card).toHaveCSS('background-color', 'rgb(22, 34, 54)')
  await expect(page.getByRole('button', { name: 'Kanban', exact: true })).toHaveCSS('background-color', 'rgb(22, 34, 54)')
  await page.screenshot({ path: '/private/tmp/horizon-crm-kanban-dark.png', fullPage: true })
})
test('CRM : lecture seule et module inaccessible sans permission', async ({ page }) => {
  await login(page, 'crm-reader@local.invalid')
  await page.goto('/crm')
  await expect(page.getByRole('heading', { name: 'CRM', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Nouvelle opportunité' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toHaveCount(0)
  await page.goto('/crm/opportunities/new')
  await expect(page.getByLabel('Titre', { exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Menu utilisateur' }).click()
  await page.getByRole('menuitem', { name: 'Se déconnecter' }).click()
  await login(page, 'writer@local.invalid')
  await page.goto('/crm')
  await expect(page.getByText('Vous ne disposez pas de la permission de consulter les opportunités.')).toBeVisible()
})

test('CRM : étapes configurables dans les paramètres communs', async ({ page }) => {
  await login(page, 'references@local.invalid')
  await page.goto('/settings/crm?tab=stages')
  await expect(page.getByRole('button', { name: 'Ajouter une étape' })).toHaveCount(0)
  await expect(page.locator('tbody tr')).toHaveCount(6)
  await page.getByRole('button', { name: 'Modifier new', exact: true }).click()
  await expect(page.getByLabel('Actif', { exact: true })).toHaveCount(0)
  await page.getByLabel('Libellé', { exact: true }).fill('Nouveau CRM')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Nouveau CRM', exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Modifier new', exact: true }).click()
  await page.getByLabel('Libellé', { exact: true }).fill('Nouveau')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Nouveau', exact: true }).first()).toBeVisible()
})

test('CRM : paramètres dédiés, couleurs cohérentes et vue de départ partagée', async ({ page }) => {
  await login(page, 'crm-admin@local.invalid')
  await page.goto('/settings/references')
  await expect(page.getByRole('button', { name: 'Étapes CRM', exact: true })).toHaveCount(0)
  await page.getByRole('navigation', { name: 'Navigation des paramètres' }).getByRole('link', { name: 'CRM', exact: true }).click()
  await expect(page).toHaveURL(/\/settings\/crm$/)
  await page.getByRole('radio', { name: /Liste/ }).check()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.goto('/crm')
  await expect(page.getByRole('button', { name: 'Liste', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Kanban', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Étape Nouveau' })).toBeVisible()
  await page.getByRole('button', { name: 'Configurer Nouveau', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Configurer Nouveau', exact: true })
  await dialog.getByRole('radio', { name: 'Orange', exact: true }).check()
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('region', { name: 'Étape Nouveau' })).toHaveAttribute('data-tone', 'amber')
  await page.goto('/settings/crm?tab=stages')
  await expect(page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'new', exact: true }) }).locator('.h-tag')).toHaveAttribute('data-tone', 'amber')
  await page.getByRole('button', { name: 'Modifier new', exact: true }).click()
  await page.getByLabel('Couleur personnalisée', { exact: true }).evaluate((element) => {
    const input = element as HTMLInputElement
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set?.call(input, '#127a8b')
    input.dispatchEvent(new Event('input', { bubbles: true }))
    input.dispatchEvent(new Event('change', { bubbles: true }))
  })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'new', exact: true }) }).locator('.h-tag')).toHaveCSS('color', 'rgb(18, 122, 139)')
  await page.goto('/crm?view=kanban')
  await expect(page.getByRole('region', { name: 'Étape Nouveau' })).toHaveCSS('border-top-color', 'rgb(18, 122, 139)')
  await page.goto('/settings/crm?tab=stages')
  await page.getByRole('button', { name: 'Modifier new', exact: true }).click()
  await page.getByRole('radio', { name: 'Bleu', exact: true }).check()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await page.getByRole('tab', { name: 'Types de marché', exact: true }).click()
  await page.getByRole('button', { name: 'Modifier broadcast', exact: true }).click()
  await page.getByRole('radio', { name: 'Vert', exact: true }).check()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'broadcast', exact: true }) }).locator('.h-tag')).toHaveAttribute('data-tone', 'green')
  await page.getByRole('button', { name: 'Modifier broadcast', exact: true }).click()
  await page.getByRole('radio', { name: 'Violet', exact: true }).check()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await page.getByRole('tab', { name: 'Présentation', exact: true }).click()
  await page.getByRole('radio', { name: /Kanban/ }).check()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.screenshot({ path: '/private/tmp/horizon-crm-settings.png', fullPage: true })
})

test('CRM : séquences configurables, aperçu et sauvegarde explicite', async ({ page }) => {
  await login(page, 'crm-admin@local.invalid')
  await page.goto('/settings/sequences')
  await expect(page.getByRole('cell', { name: 'Opportunités CRM', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Modifier Opportunités CRM', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Séquence · Opportunités CRM' })
  await expect(dialog.getByRole('heading', { name: 'Compteur', exact: true })).toBeVisible()
  await expect(dialog.getByRole('heading', { name: 'Format du numéro', exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-sequence-editor-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await expect(dialog.locator('.dialog-form-footer').getByRole('button', { name: 'Enregistrer', exact: true })).toBeVisible()
  await dialog.getByLabel('Suffixe', { exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/private/tmp/horizon-sequence-editor-mobile.png' })
  await page.setViewportSize({ width: 1280, height: 720 })
  await expect(dialog.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  if (await dialog.locator('.settings-sequence-notice').count()) await expect(dialog.getByLabel('Numéro de départ', { exact: true })).toBeDisabled()
  else await expect(dialog.getByLabel('Numéro de départ', { exact: true })).toBeEnabled()
  const next = Number(await dialog.getByLabel('Prochaine valeur', { exact: true }).inputValue()) + 10
  await dialog.getByLabel('Prochaine valeur', { exact: true }).fill(String(next))
  await expect(dialog.locator('.settings-sequence-preview')).toContainText(String(next).padStart(5, '0'))
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  await expect(page.getByRole('cell', { name: String(next).padStart(5, '0'), exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-settings-sequences.png', fullPage: true })
})


test('CRM : tri transverse visible sans regroupement et réinitialisation', async ({ page }) => {
  await login(page)
  await page.goto('/crm')
  await page.getByRole('button', { name: 'Filtres de recherche', exact: true }).click()
  const panel = page.getByRole('dialog', { name: 'Filtres de recherche', exact: true })
  await expect(panel.locator('.search-options-columns > section')).toHaveCount(2)
  await panel.getByRole('combobox', { name: 'Trier par', exact: true }).click()
  await page.getByRole('option', { name: 'Titre', exact: true }).click()
  await expect(page).toHaveURL(/sort=title/)
  await expect(page.getByRole('button', { name: 'Filtres de recherche, 1 actif', exact: true })).toBeVisible()
  await expect(panel.getByRole('button', { name: 'Réinitialiser', exact: true })).toBeEnabled()
  await panel.getByRole('button', { name: 'Réinitialiser', exact: true }).click()
  await expect(page).not.toHaveURL(/sort=/)
})
