import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { runInNewContext } from 'node:vm'
import { test, expect } from '@playwright/test'
import { defaultLayout, newBlock, printableWidth } from '../../src/modules/documents/schemas/templates'
async function login(page: import('@playwright/test').Page, email = 'erp-admin@local.invalid') {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail', { exact: true }).fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill('Local-Horizon-test-only-2026!')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
}
async function expandTools(page: import('@playwright/test').Page) {
  await expect(page.locator('.studio-library')).toBeVisible()
  for (const section of await page.locator('.studio-section').all()) {
    if (await section.isVisible() && await section.getAttribute('open') === null) { await section.locator('summary').click(); await expect(section).toHaveAttribute('open', '') }
  }
}
test('Studio : création, position au pixel, titres, publication et relecture', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 })
  await login(page)
  await page.goto('/settings/documents')
  await page.getByRole('link', { name: 'Nouveau modèle' }).click()
  await expandTools(page)
  await page.getByLabel('Nom du modèle', { exact: true }).fill('Modèle studio recette')
  await page.getByRole('button', { name: 'Sélectionner Champ lié' }).first().click()
  await expandTools(page)
  await page.getByLabel('Largeur (px)', { exact: true }).fill('500')
  await page.getByLabel('X (px)', { exact: true }).fill('20')
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expandTools(page)
  await page.getByLabel('Taille du texte (px)', { exact: true }).first().fill('16')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/settings\/documents\/(?!new)/)
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Publier', exact: true }).click()
  await page.getByRole('dialog', { name: 'Publier le modèle' }).getByRole('button', { name: 'Confirmer', exact: true }).click()
  await expect(page.locator('.page-header')).toContainText('Version publiée 1')
  await page.reload()
  await page.getByRole('button', { name: 'Sélectionner Champ lié' }).first().click()
  await expandTools(page)
  await expect(page.getByLabel('X (px)', { exact: true })).toHaveValue('20')
  await expect(page.getByLabel('Largeur (px)', { exact: true })).toHaveValue('500')
  await page.screenshot({ path: '/private/tmp/horizon-document-studio.png', fullPage: true })
  // Drag coordinates stay in layout pixels despite the 75% zoom.
  const handle = page.getByRole('button', { name: 'Déplacer le bloc', exact: true }), box = (await handle.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 15, box.y + box.height / 2 + 3, { steps: 3 }); await page.mouse.up()
  await expect(page.getByLabel('X (px)', { exact: true })).toHaveValue('40')
  await page.getByRole('button', { name: 'Annuler les modifications', exact: true }).click()
  await expect(page.getByLabel('X (px)', { exact: true })).toHaveValue('20')
  await expandTools(page)
  const library = page.locator('.studio-library').getByRole('button', { name: 'Texte', exact: true })
  const source = (await library.boundingBox())!, target = (await page.locator('.studio-canvas-scroll').boundingBox())!
  await page.mouse.move(source.x + 25, source.y + 12); await page.mouse.down()
  await page.mouse.move(target.x + 80, target.y + 180, { steps: 8 }); await page.mouse.up()
  await expect(page.getByRole('button', { name: 'Sélectionner Texte', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expandTools(page)
  await page.getByRole('checkbox', { name: 'Remise %', exact: true }).check()
  await page.getByLabel('Largeur Description', { exact: true }).fill('65')
  await expect(page.locator('.studio-column-fields').getByText('100 %', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
})
test('Studio : blocs côte à côte, logo, provenance des champs et typographie', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 })
  await login(page)
  await page.goto('/settings/documents/new')
  await expandTools(page)
  await page.getByRole('button', { name: 'Sélectionner Champ lié' }).nth(1).click()
  await expandTools(page)
  await page.getByRole('combobox', { name: 'Disposition du bloc', exact: true }).click()
  await page.getByRole('option', { name: 'Même ligne que le bloc précédent', exact: true }).click()
  const row = page.locator('.studio-flow-row').first()
  await expect(row.locator('.studio-block')).toHaveCount(2)
  const first = (await row.locator('.studio-block').first().boundingBox())!, second = (await row.locator('.studio-block').last().boundingBox())!
  expect(Math.abs(first.y - second.y)).toBeLessThan(1)
  expect(second.x).toBeGreaterThan(first.x + first.width)
  await page.getByRole('combobox', { name: 'Champ lié', exact: true }).click()
  await page.getByRole('option', { name: 'Adresse complète', exact: true }).click()
  await page.getByRole('button', { name: 'Gras', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Gras', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('combobox', { name: 'Police du texte', exact: true }).click()
  await page.getByRole('option', { name: 'Noto Serif', exact: true }).click()
  await page.getByRole('button', { name: 'Augmenter le zoom', exact: true }).click()
  await expect(page.locator('.studio-zoom output')).toHaveText('85 %')
  await page.getByRole('button', { name: 'Réduire le zoom', exact: true }).click()
  await expect(page.locator('.studio-zoom output')).toHaveText('75 %')
  await page.locator('.studio-library').getByRole('button', { name: 'Logo / image', exact: true }).click()
  await expandTools(page)
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Importer un logo', exact: true }).click()
  const png = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 300; canvas.height = 150; const context = canvas.getContext('2d')!; context.fillStyle = '#7B3FC7'; context.fillRect(0, 0, 300, 150); return canvas.toDataURL('image/png').split(',')[1]! })
  await (await chooser).setFiles({ name: 'logo.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') })
  await expect(page.getByAltText('Logo importé', { exact: true })).toBeVisible()
  await expect(page.getByAltText('Logo du modèle', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Largeur (px)', { exact: true })).toHaveValue('300')
  await expect(page.getByLabel('Hauteur min. (px)', { exact: true })).toHaveValue('150')
  await page.getByLabel('Largeur (px)', { exact: true }).fill('200')
  await expect(page.getByLabel('Hauteur min. (px)', { exact: true })).toHaveValue('100')
  const resize = (await page.getByRole('button', { name: 'Redimensionner le bloc', exact: true }).boundingBox())!
  await page.mouse.move(resize.x + resize.width / 2, resize.y + resize.height / 2); await page.mouse.down(); await page.mouse.move(resize.x + resize.width / 2 + 75, resize.y + resize.height / 2, { steps: 5 }); await page.mouse.up()
  await expect(page.getByLabel('Largeur (px)', { exact: true })).toHaveValue('300')
  await expect(page.getByLabel('Hauteur min. (px)', { exact: true })).toHaveValue('150')
  const picture = (await page.getByAltText('Logo du modèle', { exact: true }).boundingBox())!
  const imageBlock = (await page.getByRole('button', { name: 'Sélectionner Logo / image', exact: true }).boundingBox())!
  expect(imageBlock.width / imageBlock.height).toBeCloseTo(2, 1)
  expect(picture.width / picture.height).toBeCloseTo(2, 1)
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expandTools(page)
  await expect(page.getByRole('combobox', { name: 'Source du tableau', exact: true })).toHaveText('Ventes · Lignes du devis')
  await page.screenshot({ path: '/private/tmp/horizon-studio-D02.png', fullPage: true })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.locator('.studio-flow-row').first().locator('.studio-block')).toHaveCount(2)
  await expect(page.getByAltText('Logo du modèle', { exact: true })).toBeVisible()
})
test('Studio : texte enrichi visible, duplication locale, ancrage, poignée et zoom adapté', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 })
  await login(page)
  await page.goto('/settings/documents/new')
  await expandTools(page)
  await page.locator('.studio-library').getByRole('button', { name: 'Texte', exact: true }).click()
  await expandTools(page)
  const editor = page.getByRole('textbox', { name: 'Texte du bloc', exact: true })
  await editor.fill('Texte bien formaté')
  await editor.press('ControlOrMeta+A')
  await page.getByRole('button', { name: 'Gras', exact: true }).click()
  await expect(page.locator('.studio-block strong').filter({ hasText: 'Texte bien formaté' })).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Gras', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: 'Dupliquer le bloc', exact: true }).click()
  const textBlocks = page.getByRole('button', { name: 'Sélectionner Texte', exact: true })
  await expect(textBlocks).toHaveCount(2)
  const original = (await textBlocks.first().boundingBox())!, duplicate = (await textBlocks.last().boundingBox())!
  expect(duplicate.y).toBeGreaterThan(original.y)
  await page.getByLabel('Largeur (px)', { exact: true }).fill('200')
  await page.getByRole('button', { name: 'Coller à droite', exact: true }).click()
  await expect(page.getByLabel('X (px)', { exact: true })).toHaveValue('503')
  await page.getByRole('button', { name: 'Coller en haut', exact: true }).click()
  await expect(page.locator('.studio-body-zone .studio-block').first()).toContainText('Texte bien formaté')
  const grip = page.getByRole('button', { name: 'Déplacer le bloc', exact: true }), from = (await grip.boundingBox())!
  const target = (await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).boundingBox())!
  await page.mouse.move(from.x + 10, from.y + 10); await page.mouse.down()
  await page.mouse.move(from.x - 10, target.y + target.height + 8, { steps: 8 }); await page.mouse.up()
  const ordered = await page.locator('.studio-body-zone .studio-block').allTextContents()
  expect(ordered.findIndex((text) => text.includes('Texte bien formaté'))).toBeGreaterThan(ordered.findIndex((text) => text.includes('Lignes du devis')))
  await page.getByRole('button', { name: 'Adapter la page à l’écran', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Adapter la page à l’écran', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(async () => (await page.locator('.studio-page').boundingBox())!.height).toBeLessThan((await page.locator('.studio-canvas-scroll').boundingBox())!.height)
  const sheet = (await page.locator('.studio-page').boundingBox())!, stage = (await page.locator('.studio-canvas-scroll').boundingBox())!
  expect(sheet.width).toBeLessThan(stage.width)
  expect(sheet.height).toBeLessThan(stage.height)
  await page.screenshot({ path: '/private/tmp/horizon-studio-D03.png', fullPage: true })
  await page.getByRole('button', { name: 'Retirer ce bloc', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Supprimer ce bloc', exact: true })).toBeVisible()
})
test('Studio : bibliothèque générique, anciens textes gras et trois niveaux de titres', async ({ page }) => {
  await login(page)
  const token = await page.evaluate(() => sessionStorage.getItem('horizon.auth.token')!)
  const model = defaultLayout(), text = newBlock('text', printableWidth(model)); text.text = 'Ancien texte gras'; text.style.bold = true; model.blocks.push(text)
  model.blocks.push(newBlock('totals', printableWidth(model)), newBlock('terms', printableWidth(model)))
  const response = await page.request.post('http://127.0.0.1:18090/api/horizon/documents/templates/save', { headers: { Authorization: token }, data: { name: 'Texte ancien et titres', content_json: model } })
  expect(response.status()).toBe(200)
  const record = await response.json()
  await page.goto(`/settings/documents/${record.id}`)
  await expandTools(page)
  const library = page.locator('.studio-library')
  await expect(library.getByRole('button', { name: 'Tableau', exact: true })).toBeVisible()
  await expect(library.getByRole('button', { name: 'Totaux', exact: true })).toHaveCount(0)
  await expect(library.getByRole('button', { name: 'Conditions de vente', exact: true })).toHaveCount(0)
  await expect(page.getByText('Titre niveau 1', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Sélectionner Texte', exact: true }).click()
  await expandTools(page)
  const editor = page.getByRole('textbox', { name: 'Texte du bloc', exact: true })
  await expect(page.locator('.studio-block strong').filter({ hasText: 'Ancien texte gras' })).toHaveCount(1)
  await editor.press('ControlOrMeta+A')
  await page.getByRole('button', { name: 'Gras', exact: true }).click()
  await expect(page.locator('.studio-block strong').filter({ hasText: 'Ancien texte gras' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Gras', exact: true })).toHaveAttribute('aria-pressed', 'false')
  for (const level of [1, 2, 3]) {
    await page.getByRole('combobox', { name: 'Style de paragraphe', exact: true }).click()
    await page.getByRole('option', { name: `Titre ${level}`, exact: true }).click()
    await expect(page.locator(`.studio-block h${level}`)).toHaveText('Ancien texte gras')
  }
  await page.getByRole('combobox', { name: 'Style de paragraphe', exact: true }).click()
  await page.getByRole('option', { name: 'Texte normal', exact: true }).click()
  await expect(page.locator('.studio-block p')).toHaveText('Ancien texte gras')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D04.png', fullPage: true })
  await page.reload()
  await expect(page.locator('.studio-block strong').filter({ hasText: 'Ancien texte gras' })).toHaveCount(0)
  const saved = await page.request.get(`http://127.0.0.1:18090/api/horizon/documents/templates/${record.id}`, { headers: { Authorization: token } })
  expect(saved.status()).toBe(200)
  expect((await saved.json()).content_json.blocks.every((block: { kind: string }) => block.kind !== 'totals' && block.kind !== 'terms')).toBe(true)
})
test('Devis : aperçu réel, modèle publié et téléchargement PDF', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  const token = await page.evaluate(() => sessionStorage.getItem('horizon.auth.token')!)
  const headers = { Authorization: token }, root = 'http://127.0.0.1:18090/api/'
  async function post(path: string, data: unknown) { const response = await page.request.post(root + path, { headers, data }); expect(response.status()).toBe(200); return response.json() }
  const auth = await post('collections/core_users/auth-refresh', {})
  const company = await post('collections/contacts_companies/records', { name: 'Client PDF réel', active: true })
  const stages = await (await page.request.get(root + 'collections/crm_stages/records?filter=active%3Dtrue&sort=sort_order', { headers })).json()
  const opportunity = await post('horizon/crm/save', { creation_key: crypto.randomUUID(), input: { title: 'Affaire PDF', company: company.id, contact: '', owner: auth.record.id, stage: stages.items[0].id, estimated_value: 1000, estimated_cost: 0, currency: 'EUR', probability: 30, expected_date: '', description: '', status: 'open' } })
  const quote = await post('horizon/sales/quotes/save', { creation_key: crypto.randomUUID(), input: { opportunity: opportunity.id, title: 'Proposition PDF', quote_date: '2026-10-08', valid_until: '2026-11-07', lines: [{ kind: 'section', description: 'Équipements', show_total: true }, { kind: 'item', description: 'Prestation visible dans le document', quantity: 2, unit: 'u', unit_price: 125, unit_cost: 50 }] } })
  const model = defaultLayout(); model.background = { color: '#E8EDF4', image: '', opacity: 0.35, fit: 'contain' }; const header = newBlock('text', 180); header.zone = 'header'; header.x = printableWidth(model) - 180; header.y = 8; header.text = 'CVS en tête'; header.style.font = 'Open Sans'; header.style.size = 18; header.style.bold = true; model.blocks.push(header)
  const draft = await post('horizon/documents/templates/save', { name: 'Modèle PDF recette', content_json: model })
  await post('horizon/documents/templates/publish', { id: draft.id, updated: draft.updated })
  await page.goto(`/sales/quotes/${quote.id}`)
  let pdfAvailable = false
  await page.route('**/api/horizon/documents/preview', (route) => route.request().postDataJSON().format === 'pdf' ? pdfAvailable ? route.fulfill({ status: 200, contentType: 'application/pdf', headers: { 'Content-Disposition': "attachment; filename*=UTF-8''Devis_00001-1_CVS.pdf", 'Access-Control-Expose-Headers': 'Content-Disposition' }, body: '%PDF-1.7\nlocal browser test\n%%EOF' }) : route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ status: 503, message: 'La génération PDF n’est pas configurée sur le serveur.', data: {} }) }) : route.continue())
  await page.getByRole('button', { name: 'PDF', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Aperçu du devis', exact: true })
  expect((await dialog.boundingBox())!.height).toBe(936)
  await expect(dialog.getByRole('combobox', { name: 'Devis de l’aperçu', exact: true })).toHaveCount(0)
  const selectorBounds = (await dialog.getByRole('combobox', { name: 'Modèle du devis', exact: true }).boundingBox())!
  const htmlButtonBounds = (await dialog.getByRole('button', { name: 'Aperçu HTML', exact: true }).boundingBox())!
  expect(selectorBounds.width).toBeLessThanOrEqual(340)
  expect(htmlButtonBounds.height).toBe(selectorBounds.height)
  expect(htmlButtonBounds.y).toBe(selectorBounds.y)
  await expect(dialog.getByRole('button', { name: 'Télécharger PDF', exact: true })).toHaveClass(/h-button--primary/)
  const models = await (await page.request.get(root + 'horizon/documents/templates', { headers })).json()
  const usableModels = models.items.filter((item: { current_version: string; status?: string }) => item.current_version && item.status !== 'archived')
  if (usableModels.length === 1) await expect(dialog.getByRole('combobox', { name: 'Modèle du devis', exact: true })).toContainText('Modèle PDF recette')
  else { await dialog.getByRole('combobox', { name: 'Modèle du devis', exact: true }).click(); await page.getByRole('option', { name: 'Modèle PDF recette · v1', exact: true }).click() }
  await expect(dialog.locator('iframe[title="Aperçu du devis enregistré"]')).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Aperçu HTML', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(dialog.getByRole('alert')).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Aperçu PDF', exact: true }).click()
  await expect(dialog.getByRole('alert')).toHaveText('La génération PDF n’est pas configurée sur le serveur.')
  await dialog.getByRole('button', { name: 'Aperçu HTML', exact: true }).click()
  await expect(dialog.locator('iframe[title="Aperçu du devis enregistré"]')).toBeVisible()
  await expect(dialog.getByRole('alert')).toHaveCount(0)
  pdfAvailable = true
  await dialog.getByRole('button', { name: 'Aperçu PDF', exact: true }).click()
  await expect(dialog.locator('iframe[title="Aperçu PDF paginé"]')).toBeVisible()
  expect((await dialog.locator('iframe[title="Aperçu PDF paginé"]').boundingBox())!.height).toBeGreaterThan(700)
  await expect(dialog.getByRole('button', { name: 'Aperçu PDF', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await dialog.getByRole('button', { name: 'Aperçu HTML', exact: true }).click()
  await expect(page.frameLocator('iframe[title="Aperçu du devis enregistré"]').getByText('Prestation visible dans le document')).toBeVisible()
  await expect(page.frameLocator('iframe[title="Aperçu du devis enregistré"]').locator(`[data-block-id="${model.blocks.find((block) => block.field === 'quote.total')!.id}"]`)).toHaveText('Total TTC : 300,00 €')
  const previewBounds = (await dialog.boundingBox())!, frameBounds = (await dialog.locator('iframe').boundingBox())!
  expect(previewBounds.width).toBeGreaterThan(1300)
  expect(previewBounds.height).toBe(936)
  expect(previewBounds.x).toBeGreaterThanOrEqual(248)
  expect(frameBounds.height).toBeGreaterThan(700)
  const frame = page.frameLocator('iframe[title="Aperçu du devis enregistré"]')
  await expect(frame.locator('.document-paper-background')).toHaveCSS('opacity', '0.35')
  await expect(frame.locator(`[data-block-id="${model.blocks[0]!.id}"]`)).toHaveCSS('opacity', '1')
  await expect(frame.locator(`[data-block-id="${header.id}"]`)).toHaveCSS('position', 'absolute')
  await expect(frame.locator(`[data-block-id="${header.id}"]`)).toHaveCSS('left', `${header.x}px`)
  await expect(frame.locator(`[data-block-id="${header.id}"]`)).toHaveCSS('top', '8px')
  await expect(frame.locator(`[data-block-id="${model.blocks[0]!.id}"]`)).toHaveCSS('font-size', '24px')
  await expect(frame.locator(`[data-block-id="${model.blocks[0]!.id}"]`)).toHaveCSS('color', 'rgb(123, 63, 199)')
  await expect(frame.getByText('Équipements', { exact: true }).locator('..')).toHaveCSS('color', 'rgb(123, 63, 199)')
  await page.screenshot({ path: '/private/tmp/horizon-document-preview.png', fullPage: true })
  // PDF transport is covered against a local converter in the backend suite.
  // Here assert the browser can download the binary response without JSON decoding.
  const download = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Télécharger PDF', exact: true }).click()
  expect((await download).suggestedFilename()).toBe('Devis_00001-1_CVS.pdf')
  await page.goto(`/settings/documents/${draft.id}`)
  await expandTools(page)
  await page.getByRole('button', { name: 'Aperçu / PDF', exact: true }).click()
  await page.getByRole('combobox', { name: 'Devis de l’aperçu', exact: true }).click()
  await page.getByRole('option', { name: `${quote.quote_number} · Client PDF réel · Proposition PDF`, exact: true }).click()
  await page.getByRole('button', { name: 'Ouvrir la fiche : Devis de l’aperçu', exact: true }).click()
  const sourceDialog = page.getByRole('dialog', { name: 'Fiche devis', exact: true })
  await expect(sourceDialog.getByLabel('Titre du devis', { exact: true })).toHaveValue('Proposition PDF')
  await sourceDialog.getByLabel('Titre du devis', { exact: true }).fill('Proposition PDF modifiée')
  await sourceDialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(sourceDialog).toHaveCount(0)
  await expect(page).toHaveURL(`/settings/documents/${draft.id}`)
  await expect(page.getByRole('dialog', { name: 'Aperçu du devis', exact: true })).toBeVisible()
})
test('Studio : un utilisateur métier ne peut pas administrer les modèles', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/settings/documents/new')
  await expect(page.getByText('La gestion des modèles est réservée aux administrateurs et superusers habilités.')).toBeVisible()
})

test('Studio : fonds, panneaux ajustables et texte à hauteur évolutive', async ({ page }) => {
  await login(page)
  const token = await page.evaluate(() => sessionStorage.getItem('horizon.auth.token')!)
  const response = await page.request.post('http://127.0.0.1:18090/api/horizon/documents/templates/save', { headers: { Authorization: token }, data: { name: 'Fond et panneaux', content_json: defaultLayout() } })
  expect(response.status()).toBe(200)
  const record = await response.json()
  await page.goto(`/settings/documents/${record.id}`)
  await expandTools(page)
  await page.getByLabel('Couleur du fond', { exact: true }).fill('#e8edf4')
  await page.getByRole('spinbutton', { name: 'Opacité du fond de page (%)', exact: true }).fill('35')
  const backdrop = page.locator('.studio-paper-background')
  await expect(backdrop).toHaveCSS('opacity', '0.35')
  const backgroundFile = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Ajouter une image', exact: true }).click()
  const png = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 16; canvas.height = 8; const context = canvas.getContext('2d')!; context.fillStyle = '#7b3fc7'; context.fillRect(0, 0, 16, 8); return canvas.toDataURL().split(',')[1]! })
  await (await backgroundFile).setFiles({ name: 'fond.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') })
  await expect(backdrop.locator('img')).toHaveCSS('object-fit', 'contain')
  await page.getByRole('combobox', { name: 'Ajustement de l’image de fond', exact: true }).click()
  await page.getByRole('option', { name: 'Remplir la page', exact: true }).click()
  await expect(backdrop.locator('img')).toHaveCSS('object-fit', 'cover')
  for (const [name, offset] of [['Largeur de la bibliothèque', 30], ['Largeur des propriétés', -45]] as const) {
    const separator = page.getByRole('separator', { name, exact: true })
    const before = Number(await separator.getAttribute('aria-valuenow')), bounds = (await separator.boundingBox())!
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + 100)
    await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + offset, bounds.y + 100); await page.mouse.up()
    expect(Number(await separator.getAttribute('aria-valuenow'))).toBeGreaterThan(before)
  }
  const widths = await page.locator('.studio-workspace').evaluate((element) => ({ left: element.style.getPropertyValue('--studio-library-width'), right: element.style.getPropertyValue('--studio-properties-width') }))
  await page.locator('.studio-library').getByRole('button', { name: 'Texte', exact: true }).click()
  await expandTools(page)
  const editor = page.getByRole('textbox', { name: 'Texte du bloc', exact: true })
  await editor.fill('Court')
  const initialHeight = (await editor.boundingBox())!.height
  expect(initialHeight).toBeLessThan(75)
  await editor.fill('Un\nDeux\nTrois\nQuatre\nCinq\nSix')
  expect((await editor.boundingBox())!.height).toBeGreaterThan(initialHeight)
  await page.getByLabel('Couleur du fond du bloc', { exact: true }).fill('#7b3fc7')
  await page.getByRole('spinbutton', { name: 'Opacité du fond (%)', exact: true }).fill('50')
  await expect(page.locator('.studio-block[data-selected=true]')).toHaveCSS('background-color', 'rgba(123, 63, 199, 0.5)')
  await expect(page.locator('.studio-block[data-selected=true]')).toHaveCSS('opacity', '1')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Adapter la page à l’écran', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D05.png', fullPage: true })
  await page.reload()
  await expect(backdrop).toHaveCSS('opacity', '0.35')
  await expect(backdrop.locator('img')).toHaveCSS('object-fit', 'cover')
  expect(await page.locator('.studio-workspace').evaluate((element) => ({ left: element.style.getPropertyValue('--studio-library-width'), right: element.style.getPropertyValue('--studio-properties-width') }))).toEqual(widths)
  const saved = await page.request.get(`http://127.0.0.1:18090/api/horizon/documents/templates/${record.id}`, { headers: { Authorization: token } })
  expect((await saved.json()).content_json.background.opacity).toBe(0.35)
  await page.getByRole('separator', { name: 'Largeur des propriétés', exact: true }).press('Home')
  await expect(page.getByRole('separator', { name: 'Largeur des propriétés', exact: true })).toHaveAttribute('aria-valuenow', '340')
  await page.getByRole('button', { name: 'Retirer le fond de page', exact: true }).click()
  await expect(backdrop).toHaveCount(0)
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('.studio-page')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.screenshot({ path: '/private/tmp/horizon-studio-D05-dark.png', fullPage: true })
  await page.setViewportSize({ width: 900, height: 900 })
  await expect(page.getByRole('separator', { name: 'Largeur des propriétés', exact: true })).toBeHidden()
  await expect(page.getByRole('button', { name: 'Page', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-studio-D05-responsive.png', fullPage: true })
})

test('Studio : groupes repliables, couleurs compactes et opacité au clavier', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  const token = await page.evaluate(() => sessionStorage.getItem('horizon.auth.token')!)
  const response = await page.request.post('http://127.0.0.1:18090/api/horizon/documents/templates/save', { headers: { Authorization: token }, data: { name: 'Groupes du studio', content_json: defaultLayout() } })
  expect(response.status()).toBe(200)
  await page.goto(`/settings/documents/${(await response.json()).id}`)
  await expandTools(page)
  const library = page.locator('details[data-section=library]'), layers = page.locator('details[data-section=layers]')
  const pageBackground = page.locator('details[data-section=page-background]')
  await page.getByRole('textbox', { name: 'Code hexadécimal : Couleur du fond', exact: true }).fill('#eff2f7')
  await expect(page.getByLabel('Couleur du fond', { exact: true })).toHaveValue('#eff2f7')
  const slider = page.getByRole('slider', { name: 'Opacité du fond de page', exact: true })
  await page.getByRole('spinbutton', { name: 'Opacité du fond de page (%)', exact: true }).fill('35'); await slider.press('ArrowRight')
  await expect(page.getByRole('spinbutton', { name: 'Opacité du fond de page (%)', exact: true })).toHaveValue('36')
  await page.getByRole('spinbutton', { name: 'Opacité du fond de page (%)', exact: true }).fill('100')
  await page.screenshot({ path: '/private/tmp/horizon-opacity-value.png', fullPage: true })
  await page.getByRole('spinbutton', { name: 'Opacité du fond de page (%)', exact: true }).fill('36')
  await pageBackground.locator('summary').click()
  await expect(slider).toBeHidden()
  await pageBackground.locator('summary').click()
  await expect(slider).toHaveValue('36')
  await page.locator('details[data-section=page-format]').locator('summary').click()
  await library.getByRole('button', { name: 'Texte', exact: true }).click()
  await expandTools(page)
  const editor = page.getByRole('textbox', { name: 'Texte du bloc', exact: true })
  await editor.fill('Contenu conservé quand on replie')
  const appearance = page.locator('details[data-section=appearance]'), content = page.locator('details[data-section=text-content]')
  const hex = page.getByRole('textbox', { name: 'Code hexadécimal : Couleur du texte', exact: true })
  await hex.fill('#7b3fc7')
  await expect(page.locator('.studio-block[data-selected=true]')).toHaveCSS('color', 'rgb(123, 63, 199)')
  await hex.fill('#1'); await expect(hex).toHaveAttribute('aria-invalid', 'true')
  await appearance.locator('summary').click()
  await expect(hex).toBeHidden()
  await content.locator('summary').click(); await expect(editor).toBeHidden()
  await content.locator('summary').click(); await expect(editor).toHaveText('Contenu conservé quand on replie')
  await library.locator('summary').click(); await expect(library.getByRole('button', { name: 'Texte', exact: true })).toBeHidden()
  await expect(layers.locator('.studio-layer')).toHaveCount(10)
  await layers.locator('summary').click(); await expect(layers.locator('.studio-layer').first()).toBeHidden()
  await layers.locator('summary').click()
  await page.getByRole('button', { name: 'Adapter la page à l’écran', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D06.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(library.getByRole('button', { name: 'Texte', exact: true })).toBeHidden()
  await expect(layers.locator('.studio-layer')).toHaveCount(10)
  await expect(page.locator('details[data-section=page-format]')).not.toHaveAttribute('open', '')
  await page.getByRole('button', { name: 'Sélectionner Texte', exact: true }).click()
  await expect(hex).toBeHidden()
  await appearance.locator('summary').click()
  await expect(hex).toHaveValue('#7B3FC7')
  await expect(editor).toHaveText('Contenu conservé quand on replie')
  await page.getByRole('button', { name: 'Page', exact: true }).click()
  await expect(page.locator('details[data-section=page-format]')).not.toHaveAttribute('open', '')
  await page.getByRole('button', { name: 'Bloc', exact: true }).click()
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D06-dark.png', fullPage: true, animations: 'disabled' })
})


test('Studio : sections fermées, titres réservés au tableau et statut à droite', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  await page.goto('/settings/documents/new')
  await expect(page.locator('.studio-section')).not.toHaveCount(0)
  await expect(page.locator('.studio-section[open]')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Titres', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Sélectionner Champ lié' }).first().click()
  await expect(page.locator('[data-section=table-headings]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  const titles = page.locator('[data-section=table-headings]')
  await expect(titles).not.toHaveAttribute('open', '')
  await titles.locator('summary').click()
  await titles.getByLabel('Taille du texte (px)', { exact: true }).fill('17')
  await expect(page.locator('.studio-model-status')).toContainText('Brouillon')
  await expect(page.locator('.studio-model-status').getByRole('button', { name: 'Publier', exact: true })).toBeVisible()
  const ribbon = (await page.locator('.page-header').boundingBox())!
  const name = (await page.getByLabel('Nom du modèle', { exact: true }).boundingBox())!
  expect(Math.abs(name.x + name.width / 2 - (ribbon.x + ribbon.width / 2))).toBeLessThan(2)
  await page.getByLabel('Nom du modèle', { exact: true }).fill('Tableaux indépendants')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/settings\/documents\/(?!new)/)
  await expect(page.locator('.studio-model-status').getByRole('button', { name: 'Archiver le modèle', exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expect(titles.getByLabel('Taille du texte (px)', { exact: true })).toHaveValue('17')
  await page.screenshot({ path: '/private/tmp/horizon-studio-D07.png', fullPage: true })
  await page.setViewportSize({ width: 1000, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-studio-D07-responsive.png', fullPage: true })
})

test('Studio : colonnes sur une ligne, largeur, ordre et bandeau compact sombre', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  await page.goto('/settings/documents/new')
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  const data = page.locator('[data-section=table-data]')
  await data.locator('summary').click()
  const row = data.locator('.studio-column-row').filter({ has: page.getByRole('checkbox', { name: 'Description', exact: true }) })
  const checkbox = (await row.getByRole('checkbox').boundingBox())!
  const name = (await row.getByLabel('Libellé Description', { exact: true }).boundingBox())!
  const width = (await row.getByLabel('Largeur Description', { exact: true }).boundingBox())!
  const arrows = (await row.locator('.studio-column-order').boundingBox())!
  for (const box of [name, width, arrows]) expect(Math.abs(box.y + box.height / 2 - checkbox.y - checkbox.height / 2)).toBeLessThan(2)
  expect(checkbox.x).toBeLessThan(name.x)
  expect(name.x + name.width).toBeLessThan(width.x)
  expect(width.x + width.width).toBeLessThan(arrows.x)
  expect((await row.boundingBox())!.height).toBeLessThan(39)
  await row.getByLabel('Libellé Description', { exact: true }).fill('Désignation')
  await row.getByLabel('Largeur Description', { exact: true }).fill('60')
  await expect(data.locator('.studio-column-total')).toContainText('100 %')
  await row.getByRole('button', { name: 'Reculer Description', exact: true }).click()
  await expect(data.locator('.studio-column-row').first().getByRole('checkbox')).toHaveAccessibleName('Marque')
  await data.getByRole('checkbox', { name: 'Remise %', exact: true }).check()
  await expect(data.getByLabel('Largeur Remise %', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/settings\/documents\/(?!new)/)
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expect(data.getByLabel('Libellé Description', { exact: true })).toHaveValue('Désignation')
  await expect(page.locator('.studio-model-status').getByRole('button', { name: 'Publier', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D08-dark.png', fullPage: true })
  await page.getByRole('button', { name: 'Passer en mode clair', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D08-light.png', fullPage: true })
  const resizer = page.getByRole('separator', { name: 'Largeur des propriétés', exact: true })
  await resizer.focus(); await resizer.press('ArrowLeft')
  await page.setViewportSize({ width: 1200, height: 900 })
  await page.screenshot({ path: '/private/tmp/horizon-studio-D08-narrow.png', fullPage: true })
  await expect.poll(async () => (await page.locator('.studio-workspace').boundingBox())!.x + (await page.locator('.studio-workspace').boundingBox())!.width).toBeLessThanOrEqual(1200)
})

test('Studio : couleurs et texte de l’en-tête du tableau, sauvegarde et aperçu', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  await page.goto('/settings/documents/new')
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  const titles = page.locator('[data-section=table-headings]')
  await titles.locator('summary').click()
  await titles.getByRole('button', { name: 'En-tête', exact: true }).click()
  await titles.getByRole('textbox', { name: 'Code hexadécimal : Couleur du texte', exact: true }).fill('#FFFFFF')
  await titles.getByRole('textbox', { name: 'Code hexadécimal : Couleur du fond du bloc', exact: true }).fill('#091C3A')
  await titles.getByLabel('Taille du texte (px)', { exact: true }).fill('14')
  await titles.getByRole('button', { name: 'Centrer le texte', exact: true }).click()
  const header = page.locator('.studio-block .lines th').first()
  await expect(header).toHaveCSS('color', 'rgb(255, 255, 255)')
  await expect(header).toHaveCSS('background-color', 'rgb(9, 28, 58)')
  await expect(header).toHaveCSS('font-size', '14px')
  await expect(header).toHaveCSS('text-align', 'center')
  await titles.getByRole('button', { name: 'Titre 1', exact: true }).click()
  await expect(titles.getByLabel('Taille du texte (px)', { exact: true })).not.toHaveValue('14')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/settings\/documents\/(?!new)/)
  await page.reload()
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await titles.getByRole('button', { name: 'En-tête', exact: true }).click()
  await expect(titles.getByLabel('Taille du texte (px)', { exact: true })).toHaveValue('14')
  await expect(header).toHaveCSS('color', 'rgb(255, 255, 255)')
  await page.screenshot({ path: '/private/tmp/horizon-studio-D09-header.png', fullPage: true })
  const token = await page.evaluate(() => sessionStorage.getItem('horizon.auth.token')!)
  const response = await page.request.get(`http://127.0.0.1:18090/api/horizon/documents/templates/${page.url().split('/').at(-1)}`, { headers: { Authorization: token } })
  expect(response.status()).toBe(200)
  expect((await response.json()).content_json.blocks.find((block: { kind: string }) => block.kind === 'table').tableHeader.color).toBe('#FFFFFF')
})

test('Studio : styles Ligne et Note indépendants et conservés', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  await page.goto('/settings/documents/new')
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  const styles = page.locator('[data-section=table-headings]')
  await styles.locator('summary').click()
  await styles.getByRole('button', { name: 'Ligne', exact: true }).click()
  await styles.getByRole('textbox', { name: 'Code hexadécimal : Couleur du texte', exact: true }).fill('#7B3FC7')
  await styles.getByLabel('Taille du texte (px)', { exact: true }).fill('13')
  await expect(page.locator('.studio-block .lines td')).toHaveCSS('color', 'rgb(123, 63, 199)')
  await expect(page.locator('.studio-block .lines td')).toHaveCSS('font-size', '13px')
  await styles.getByRole('button', { name: 'Note', exact: true }).click()
  await expect(styles.getByRole('button', { name: 'Italique', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await styles.getByRole('textbox', { name: 'Code hexadécimal : Couleur du texte', exact: true }).fill('#E07800')
  await styles.getByLabel('Taille du texte (px)', { exact: true }).fill('15')
  await styles.getByRole('button', { name: 'Ligne', exact: true }).click()
  await expect(styles.getByLabel('Taille du texte (px)', { exact: true })).toHaveValue('13')
  await styles.getByRole('button', { name: 'En-tête', exact: true }).click()
  await expect(styles.getByLabel('Taille du texte (px)', { exact: true })).toHaveValue('11')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/settings\/documents\/(?!new)/)
  await page.reload()
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await styles.getByRole('button', { name: 'Note', exact: true }).click()
  await expect(styles.getByLabel('Taille du texte (px)', { exact: true })).toHaveValue('15')
  await styles.getByRole('button', { name: 'Ligne', exact: true }).click()
  await expect(styles.getByLabel('Taille du texte (px)', { exact: true })).toHaveValue('13')
  await page.screenshot({ path: '/private/tmp/horizon-studio-D10-lines.png', fullPage: true })
})

test('Studio : pictogrammes des blocs et poignée à droite pour réordonner', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  await page.goto('/settings/documents/new')
  const layers = page.locator('[data-section=layers]')
  await layers.locator('summary').click()
  const first = layers.locator('.studio-layer').first(), second = layers.locator('.studio-layer').nth(1)
  await expect(first.locator('.studio-layer-select>svg')).toHaveCount(1)
  const row = (await first.boundingBox())!, handle = (await first.locator('.studio-layer-handle').boundingBox())!
  expect(row.x + row.width - handle.x - handle.width).toBeLessThan(2)
  const firstName = await first.locator('.studio-layer-label').innerText(), secondName = await second.locator('.studio-layer-label').innerText()
  await first.locator('.studio-layer-select').click()
  await expect(page.locator('.studio-properties>.h-section-heading svg')).not.toHaveCount(0)
  const target = (await second.boundingBox())!
  await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2)
  await page.mouse.down()
  await page.mouse.move(handle.x + handle.width / 2, target.y + target.height - 3, { steps: 12 })
  await page.mouse.up()
  await expect(layers.locator('.studio-layer-label').first()).toHaveText(secondName)
  await expect(layers.locator('.studio-layer-label').nth(1)).toHaveText(firstName)
  await expect(page).toHaveURL('/settings/documents/new')
  await page.mouse.move(900, 110)
  await expect.poll(async () => { const second = (await layers.locator('.studio-layer').nth(1).boundingBox())!, third = (await layers.locator('.studio-layer').nth(2).boundingBox())!; return second.y + second.height <= third.y + 1 }).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-studio-D11-blocks.png', fullPage: true, animations: 'disabled' })
})

test('Studio : sélection commune et pictogrammes de sections en clair et sombre', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  await page.goto('/settings/documents/new')
  await page.locator('[data-section=layers]>summary').click()
  await page.locator('[data-section=library]>summary').click()
  await page.getByRole('button', { name: 'Sélectionner Champ lié' }).first().click()
  const layer = page.locator('.studio-layer[data-selected=true]'), canvas = page.locator('.studio-block[data-selected=true]'), properties = page.locator('.studio-properties>.h-section-heading')
  async function verifySelection() {
    const accent = await canvas.evaluate((element) => getComputedStyle(element).outlineColor)
    await expect(layer).toHaveCSS('color', accent)
    await expect(properties.locator('.h-section-heading-title h2')).toHaveCSS('color', accent)
    const background = await layer.evaluate((element) => getComputedStyle(element).backgroundColor)
    await expect(properties).toHaveCSS('background-color', background)
    await expect(layer).toHaveCSS('box-shadow', 'none')
    await expect(page.locator('[data-section=library] .h-button[data-selected=true]')).toHaveCount(0)
    const tool = page.locator('[data-section=library]').getByRole('button', { name: 'Texte', exact: true })
    await tool.hover()
    await expect(tool).toHaveCSS('color', accent)
    await expect(tool).toHaveCSS('background-color', background)
    await page.mouse.move(900, 110)
    for (const section of await page.locator('.studio-section:visible').all()) {
      await expect(section.locator('summary .h-section-heading-title>svg')).toHaveCount(1)
    }
  }
  await verifySelection()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D13-light.png', fullPage: true })
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await verifySelection()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D13-dark.png', fullPage: true })
  await page.getByRole('button', { name: 'Page', exact: true }).click()
  for (const id of ['page-format', 'page-background']) await expect(page.locator(`[data-section=${id}] summary .h-section-heading-title>svg`)).toHaveCount(1)
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await verifySelection()
})

test('Studio : repères de marge alignés au papier, au zoom et en paysage', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  await page.goto('/settings/documents/new')
  const guides = page.locator('.studio-margin-guides')
  await expect(guides.locator('[data-corner]')).toHaveCount(4)
  await expect(guides).toHaveCSS('pointer-events', 'none')
  async function verifyMargins() {
    await expect.poll(() => page.locator('.studio-page').evaluate((paper) => {
      const guide = paper.querySelector('.studio-margin-guides')!, rect = paper.getBoundingClientRect(), inner = guide.getBoundingClientRect()
      const style = getComputedStyle(paper), margin = parseFloat(style.paddingLeft) * parseFloat(style.zoom)
      return Math.max(Math.abs(inner.left - rect.left - margin), Math.abs(rect.right - inner.right - margin), Math.abs(inner.top - rect.top - margin), Math.abs(rect.bottom - inner.bottom - margin))
    })).toBeLessThan(1)
  }
  await expect(page.locator('.studio-page-dimension-width')).toHaveText('210 mm')
  await expect(page.locator('.studio-page-dimension-height')).toHaveText('297 mm')
  await verifyMargins()
  await page.getByRole('button', { name: 'Augmenter le zoom', exact: true }).click()
  await verifyMargins()
  await page.getByRole('button', { name: 'Page', exact: true }).click()
  await page.locator('[data-section=page-format]>summary').click()
  await page.getByLabel('Marges (mm)', { exact: true }).fill('20')
  await verifyMargins()
  await page.getByRole('combobox', { name: 'Format A4', exact: true }).click()
  await page.getByRole('option', { name: 'A4 paysage', exact: true }).click()
  await expect(page.locator('.studio-page-dimension-width')).toHaveText('297 mm')
  await expect(page.locator('.studio-page-dimension-height')).toHaveText('210 mm')
  await page.getByRole('button', { name: 'Adapter la page à l’écran', exact: true }).click()
  await verifyMargins()
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expect(page.locator('.studio-block[data-selected=true] table')).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-studio-margins.png', fullPage: true })
})

test('Studio : ouvrir les sections ne comprime pas les titres du panneau', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 800 })
  await login(page)
  await page.goto('/settings/documents/new')
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  const panel = page.locator('.studio-properties'), heading = panel.locator(':scope>.h-section-heading')
  const closedHeight = (await heading.boundingBox())!.height
  for (const section of await panel.locator('.studio-section').all()) await section.locator('summary').click()
  await expect.poll(async () => (await heading.boundingBox())!.height).toBeGreaterThanOrEqual(closedHeight - 1)
  for (const section of await panel.locator('.studio-section').all()) {
    expect(await section.evaluate((element) => {
      const bounds = element.getBoundingClientRect()
      return [...element.children].every((child) => child.getBoundingClientRect().bottom <= bounds.bottom + 1)
    })).toBe(true)
  }
  await expect(panel).toHaveCSS('overflow-y', 'auto')
  await page.screenshot({ path: '/private/tmp/horizon-studio-open-sections.png', fullPage: true })
  await panel.evaluate((element) => { element.scrollTop = element.scrollHeight })
  await expect(panel.locator('[data-section=appearance]')).toBeInViewport()
  await page.getByRole('button', { name: 'Page', exact: true }).click()
  for (const section of await panel.locator('.studio-section').all()) await section.locator('summary').click()
  await expect(panel.locator('[data-section=page-background]')).toBeVisible()
})

test('Documents : Chromium imprime en A4 avec saut explicite et tableau paginé', async ({ page }) => {
  const hooks = resolve('pocketbase/pb_hooks')
  const validator = runInNewContext(readFileSync(`${hooks}/lib/document-layout.js`, 'utf8') + '\nmodule.exports', { module: { exports: {} }, BadRequestError: Error })
  const render = runInNewContext(readFileSync(`${hooks}/lib/document-renderer.js`, 'utf8') + '\nmodule.exports', { module: { exports: {} }, __hooks: hooks, require: () => validator, $os: { readFile: (path: string) => readFileSync(path, 'utf8') } }) as (layout: ReturnType<typeof defaultLayout>, context: { fields: Record<string, string>; lines: Record<string, string | number>[] }) => { body: string; header: string; footer: string }
  const layout = defaultLayout(), first = newBlock('text', 300), last = newBlock('text', 300)
  const logo = newBlock('image', 160)
  logo.zone = 'header'; logo.y = 0; logo.height = 60
  logo.image = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 160; canvas.height = 60; const ctx = canvas.getContext('2d')!; ctx.fillStyle = '#7B3FC7'; ctx.fillRect(0, 0, 160, 40); ctx.fillStyle = '#F52F96'; ctx.fillRect(0, 40, 160, 20); return canvas.toDataURL() })
  layout.background = { color: '#FFFFFF', opacity: 1, image: '', fit: 'cover' }
  first.text = 'Première page'; last.text = 'Après le saut'
  layout.blocks = [logo, first, newBlock('pageBreak', 300), last]
  async function pdf(lines: Record<string, string | number>[] = []) {
    const rendered = render(layout, { fields: { 'quote.currency': 'EUR' }, lines })
    for (const zone of [rendered.header, rendered.footer]) {
      await page.setContent(zone)
      const background = page.locator('.document-paper-background')
      await expect(background.locator('..')).toHaveCSS('overflow', 'hidden')
    }
    await page.setContent(rendered.body)
    await page.evaluate(() => document.fonts.ready)
    const bytes = await page.pdf({ format: 'A4', landscape: layout.orientation === 'landscape', printBackground: true, displayHeaderFooter: true, headerTemplate: rendered.header, footerTemplate: rendered.footer, margin: { left: `${layout.margin}mm`, right: `${layout.margin}mm`, top: `${layout.margin + layout.headerHeight * 25.4 / 96}mm`, bottom: `${layout.margin + layout.footerHeight * 25.4 / 96}mm` } })
    writeFileSync(test.info().outputPath(lines.length ? 'table.pdf' : 'logo-background.pdf'), bytes)
    return bytes.toString('latin1')
  }
  const explicit = await pdf()
  expect(explicit.match(/\/Type \/Page\b/g)).toHaveLength(2)
  expect(explicit).toMatch(/\/MediaBox \[0 0 595[.\d]* 842[.\d]*\]/)
  const table = newBlock('table', printableWidth(layout)); layout.blocks = [table]
  const long = await pdf(Array.from({ length: 140 }, (_, i) => ({ kind: 'item', description: `Ligne ${i + 1}`, quantity: 1, unit: 'u', unit_price: 10, line_total: 10 })))
  expect((long.match(/\/Type \/Page\b/g) || []).length).toBeGreaterThan(2)
})

test('HTML paginé : tableau long, saut explicite, zones répétées et isolation', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  const token = await page.evaluate(() => sessionStorage.getItem('horizon.auth.token')!)
  const headers = { Authorization: token }, root = 'http://127.0.0.1:18090/api/'
  async function post(path: string, data: unknown) { const response = await page.request.post(root + path, { headers, data }); expect(response.status()).toBe(200); return response.json() }
  const auth = await post('collections/core_users/auth-refresh', {})
  const company = await post('collections/contacts_companies/records', { name: 'Pagination HTML', active: true })
  const stages = await (await page.request.get(root + 'collections/crm_stages/records?filter=active%3Dtrue&sort=sort_order', { headers })).json()
  const opportunity = await post('horizon/crm/save', { creation_key: crypto.randomUUID(), input: { title: 'Pagination', company: company.id, contact: '', owner: auth.record.id, stage: stages.items[0].id, estimated_value: 1000, estimated_cost: 0, currency: 'EUR', probability: 30, expected_date: '', description: '', status: 'open' } })
  const lines = Array.from({ length: 140 }, (_, i) => ({ kind: i < 3 ? ['section', 'subsection', 'subsection3'][i] : i % 17 === 0 ? 'note' : 'item', description: `Article pagination ${String(i + 1).padStart(3, '0')}${i % 11 === 0 ? '\nDescription sur plusieurs lignes' : ''}`, quantity: 1, unit: 'u', unit_price: 10, unit_cost: 5 }))
  const quote = await post('horizon/sales/quotes/save', { creation_key: crypto.randomUUID(), input: { opportunity: opportunity.id, title: 'Devis multipage', quote_date: '2026-10-08', valid_until: '2026-11-07', lines } })
  const model = defaultLayout(), header = newBlock('text', 300), after = newBlock('text', 500)
  header.zone = 'header'; header.text = 'En-tête répété Horizon'; after.text = 'Après le saut obligatoire'
  const logo = newBlock('image', 160)
  logo.zone = 'header'; logo.y = 0; logo.height = 60
  logo.image = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 160; canvas.height = 60; const ctx = canvas.getContext('2d')!; ctx.fillStyle = '#7B3FC7'; ctx.fillRect(0, 0, 160, 40); ctx.fillStyle = '#F52F96'; ctx.fillRect(0, 40, 160, 20); return canvas.toDataURL() })
  const bodyImage = { ...logo, id: crypto.randomUUID(), zone: 'body' as const, y: 12 }
  header.x = 180
  const left = newBlock('text', 300), right = newBlock('text', 300)
  left.text = 'Bloc à gauche'; right.text = 'Bloc à droite'; right.sameLine = true; right.x = 330
  model.blocks = [logo, header, bodyImage, left, right, newBlock('table', printableWidth(model)), newBlock('pageBreak', printableWidth(model)), after, ...model.blocks.filter((block) => block.zone === 'footer')]
  model.background = { color: '#E8EDF4', opacity: 0.2, image: logo.image, fit: 'cover' }
  const draft = await post('horizon/documents/templates/save', { name: 'HTML multipage recette', content_json: model })
  await post('horizon/documents/templates/publish', { id: draft.id, updated: draft.updated })
  await page.goto(`/sales/quotes/${quote.id}`)
  await page.getByRole('button', { name: 'PDF', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Aperçu du devis', exact: true })
  await dialog.getByRole('combobox', { name: 'Modèle du devis', exact: true }).click()
  await page.getByRole('option', { name: 'HTML multipage recette · v1', exact: true }).click()
  const iframe = dialog.locator('iframe[title="Aperçu du devis enregistré"]'), frame = page.frameLocator('iframe[title="Aperçu du devis enregistré"]')
  await expect(iframe).toHaveCSS('visibility', 'visible')
  await expect(iframe).toBeVisible({ timeout: 15000 })
  await expect(frame.locator('html')).toHaveAttribute('data-paginated', 'true')
  const count = await frame.locator('.pagedjs_page').count()
  expect(count).toBeGreaterThan(3)
  await expect(frame.locator('.document-repeated-header')).toHaveCount(count)
  await expect(frame.locator('.document-repeated-header img')).toHaveCount(count)
  expect(await frame.locator('.document-repeated-header img').first().evaluate((image) => (image as HTMLImageElement).naturalWidth)).toBe(160)
  await expect(frame.locator('.document-repeated-footer')).toHaveCount(count)
  await expect(frame.locator('.document-repeated-footer').last()).toHaveText(`Page ${count} / ${count}`)
  await expect(frame.locator('.lines tbody tr')).toHaveCount(140)
  for (const table of await frame.locator('table.lines').all()) await expect(table.locator('thead')).toHaveCount(1)
  const lastPage = frame.locator('.pagedjs_page').last()
  await expect(lastPage).toContainText('Après le saut obligatoire')
  await expect(lastPage.locator('table.lines')).toHaveCount(0)
  const frameHandle = (await iframe.elementHandle())!, contentFrame = (await frameHandle.contentFrame())!
  const dimensions = await contentFrame.evaluate(() => {
    const page = document.querySelector<HTMLElement>('.pagedjs_page')!, bounds = page.getBoundingClientRect()
    let isolated = false
    try { void window.parent.document } catch { isolated = true }
    return { width: bounds.width, height: bounds.height, isolated }
  })
  expect(dimensions.width).toBeCloseTo(210 * 96 / 25.4, 0)
  expect(dimensions.height).toBeCloseTo(297 * 96 / 25.4, 0)
  expect(dimensions.isolated).toBe(true)
  await expect(dialog.locator('.document-preview-format')).toContainText('A4 · Portrait')
  await expect(dialog.locator('.document-preview-format')).toContainText('210 × 297 mm')
  await expect(dialog.locator('.document-preview-body .document-preview-page-count')).toHaveText(`${count} pages`)
  await expect(dialog.locator('.document-preview-body').getByRole('group', { name: 'Zoom HTML' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Augmenter le zoom HTML' }).click()
  await expect(frame.locator('#document-pages')).toHaveCSS('zoom', '1.1')
  await dialog.getByRole('button', { name: 'Réduire le zoom HTML' }).click()
  await expect(frame.locator('#document-pages')).toHaveCSS('zoom', '1')
  await dialog.getByRole('button', { name: 'Ajuster à la fenêtre' }).click()
  await expect.poll(async () => (await frame.locator('.pagedjs_page').first().boundingBox())!.height).toBeLessThan((await iframe.boundingBox())!.height)
  await expect(dialog.getByRole('button', { name: 'Ajuster à la fenêtre' })).toHaveAttribute('aria-pressed', 'true')
  await dialog.getByRole('button', { name: 'Augmenter le zoom HTML' }).click()
  await dialog.getByRole('button', { name: 'Réduire le zoom HTML' }).click()
  await expect(frame.locator('#document-pages')).toHaveCSS('zoom', '1')
  const leftBounds = (await frame.getByText('Bloc à gauche', { exact: true }).boundingBox())!, rightBounds = (await frame.getByText('Bloc à droite', { exact: true }).boundingBox())!
  expect(rightBounds.y).toBeCloseTo(leftBounds.y, 0)
  expect(rightBounds.x - leftBounds.x).toBeCloseTo(330, 0)
  const overflow = await contentFrame.evaluate(() => [...document.querySelectorAll('.pagedjs_area')].some((area) => [...area.querySelectorAll('tbody tr')].some((row) => row.getBoundingClientRect().bottom > area.getBoundingClientRect().bottom + 1)))
  expect(overflow).toBe(false)
  await page.screenshot({ path: '/private/tmp/horizon-html-paginated.png' })
  await contentFrame.evaluate(() => document.querySelectorAll('.pagedjs_page')[1]!.scrollIntoView())
  await page.screenshot({ path: '/private/tmp/horizon-html-paginated-second-page.png' })
  model.orientation = 'landscape'
  const landscape = await post('horizon/documents/templates/save', { name: 'HTML paysage recette', content_json: model })
  await post('horizon/documents/templates/publish', { id: landscape.id, updated: landscape.updated })
  await dialog.getByRole('button', { name: 'Fermer', exact: true }).click()
  await page.getByRole('button', { name: 'PDF', exact: true }).click()
  await dialog.getByRole('combobox', { name: 'Modèle du devis', exact: true }).click()
  await page.getByRole('option', { name: 'HTML paysage recette · v1', exact: true }).click()
  await expect(iframe).toBeVisible({ timeout: 15000 })
  const landscapeBounds = (await frame.locator('.pagedjs_page').first().boundingBox())!
  expect(landscapeBounds.width).toBeCloseTo(297 * 96 / 25.4, 0)
  expect(landscapeBounds.height).toBeCloseTo(210 * 96 / 25.4, 0)
  await page.screenshot({ path: '/private/tmp/horizon-html-paginated-landscape.png' })
  // Reopening HTML starts a fresh isolated engine, rather than retaining a failed frame.
  const previousFrame = await iframe.getAttribute('srcdoc')
  await dialog.getByRole('button', { name: 'Aperçu HTML', exact: true }).click()
  await expect(iframe).not.toHaveAttribute('srcdoc', previousFrame!)
  await expect(frame.locator('html')).toHaveAttribute('data-paginated', 'true')
  await page.getByRole('button', { name: 'Fermer', exact: true }).click()
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await page.getByRole('button', { name: 'PDF', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await dialog.getByRole('combobox', { name: 'Modèle du devis', exact: true }).click()
  await page.getByRole('option', { name: 'HTML paysage recette · v1', exact: true }).click()
  await dialog.getByRole('button', { name: 'Ajuster à la fenêtre', exact: true }).click()
  await expect(frame.locator('html')).toHaveAttribute('data-paginated', 'true')
  const compactBounds = (await dialog.boundingBox())!
  expect(compactBounds.y).toBeGreaterThanOrEqual(16)
  expect(compactBounds.y + compactBounds.height).toBeLessThanOrEqual(784)
  await page.screenshot({ path: '/private/tmp/horizon-document-preview-dark-compact.png' })
})


test('Documents : formats de noms PDF configurables dans les paramètres', async ({ page }) => {
  await login(page)
  await page.goto('/settings/documents?tab=files')
  await expect(page.getByRole('tab', { name: 'Noms des PDF', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('textbox', { name: 'Nom PDF Devis', exact: true }).fill('Offre_{number}_{company}')
  await page.getByRole('textbox', { name: 'Nom PDF Commande client', exact: true }).fill('BDC_{number}')
  await expect(page.getByText('Offre_00001-1_CVS.pdf', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Nom PDF Devis', exact: true })).toHaveValue('Offre_{number}_{company}')
  await expect(page.getByRole('textbox', { name: 'Nom PDF Commande client', exact: true })).toHaveValue('BDC_{number}')
  await expect(page.getByRole('heading', { name: 'Noms des PDF', exact: true })).toHaveCount(0)
  const pattern = page.getByRole('textbox', { name: 'Nom PDF Devis', exact: true })
  await pattern.fill('Devis_{number}_')
  await pattern.press('End')
  await page.getByRole('combobox', { name: 'Insérer un champ', exact: true }).click()
  await page.getByRole('option', { name: 'Client · Nom', exact: true }).click()
  await expect(pattern).toHaveValue('Devis_{number}_{client}')
  await expect(pattern).toBeFocused()
  await pattern.press('End')
  await pattern.press('_')
  await page.getByRole('combobox', { name: 'Insérer un champ', exact: true }).click()
  await page.getByRole('option', { name: 'Opportunité · Titre', exact: true }).click()
  await expect(pattern).toHaveValue('Devis_{number}_{client}_{opportunity}')
  await expect(page.getByText('Devis_00001-1_CVS_Studio broadcast.pdf', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(pattern).toHaveValue('Devis_{number}_{client}_{opportunity}')
  await page.screenshot({ path: '/private/tmp/horizon-document-filenames.png' })
})

test('Modèles : suppression confirmée depuis la liste', async ({ page }) => {
  await login(page)
  await page.goto('/settings/documents/new')
  await page.getByLabel('Nom du modèle', { exact: true }).fill('Modèle à supprimer')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/settings\/documents\/(?!new)/)
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Supprimer le modèle', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Archiver le modèle', exact: true })).toHaveCount(0)
  await page.goto('/settings/documents')
  await page.getByRole('row').filter({ has: page.getByRole('link', { name: 'Modèle à supprimer', exact: true }) }).getByRole('button', { name: 'Supprimer le modèle', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Supprimer le modèle', exact: true })
  await expect(page).toHaveURL('/settings/documents')
  await expect(dialog).toContainText('Modèle à supprimer')
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: 'Supprimer le modèle', exact: true }).click()
  await dialog.getByRole('button', { name: 'Supprimer', exact: true }).click()
  await expect(page).toHaveURL('/settings/documents')
  await expect(page.getByRole('link', { name: 'Modèle à supprimer', exact: true })).toHaveCount(0)
})

test('Modèles : archivage confirmé depuis la liste', async ({ page }) => {
  await login(page)
  await page.goto('/settings/documents/new')
  await page.getByLabel('Nom du modèle', { exact: true }).fill('Modèle à archiver')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/settings\/documents\/(?!new)/)
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Publier', exact: true }).click()
  await page.getByRole('dialog', { name: 'Publier le modèle' }).getByRole('button', { name: 'Confirmer', exact: true }).click()
  await expect(page.locator('.studio-model-status')).toContainText('Publié')
  await page.goto('/settings/documents')
  const row = page.getByRole('row').filter({ has: page.getByRole('link', { name: 'Modèle à archiver', exact: true }) })
  await expect(row.getByRole('button', { name: 'Supprimer le modèle', exact: true })).toHaveCount(0)
  await row.getByRole('button', { name: 'Archiver le modèle', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL('/settings/documents')
  await page.getByRole('dialog', { name: 'Archiver le modèle', exact: true }).getByRole('button', { name: 'Archiver', exact: true }).click()
  await expect(row).toContainText('Archivé')
  await expect(row).toContainText('v1')
  await expect(row.getByRole('button', { name: 'Archiver le modèle', exact: true })).toHaveCount(0)
  await page.screenshot({ path: '/private/tmp/horizon-template-list-actions.png' })
})

test('Paramètres : tableaux partagés compacts et compteurs harmonisés', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await login(page)
  for (const path of ['/settings/references', '/settings/sequences', '/settings/crm?tab=stages', '/settings/crm?tab=markets', '/settings/crm?tab=appointment-tags', '/settings/users', '/settings/users?tab=tags', '/settings/ventes?tab=columns', '/settings/ventes?tab=terms', '/settings/documents?tab=files']) {
    await page.goto(path)
    await expect(page.locator('.settings-table-count').first()).toBeVisible()
    const table = page.locator('.settings-reference-table .reference-table').first()
    await expect(table).toBeVisible()
    await expect(table.locator('th').first()).toHaveCSS('border-right-width', '1px')
    await expect(table.locator('th').first()).toHaveCSS('border-right-style', 'solid')
    for (const cell of await table.locator('.settings-state-cell, .settings-action-cell').all()) await expect(cell).toHaveCSS('text-align', 'center')
    for (const button of await table.locator('.settings-action-cell .h-button').all()) await expect(button).toHaveCSS('height', '28px')
    const firstRow = table.locator('tbody tr').first()
    if (await firstRow.count() && !path.endsWith('/users')) expect((await firstRow.boundingBox())!.height).toBeLessThanOrEqual(40)
  }
  await page.screenshot({ path: '/private/tmp/horizon-settings-shared-table.png' })
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await page.setViewportSize({ width: 900, height: 800 })
  await page.goto('/settings/references')
  await expect(page.locator('.settings-table-count')).toBeVisible()
  const table = page.locator('.settings-reference-table .reference-table')
  await expect(table.locator('th').first()).toHaveCSS('border-right-width', '1px')
  const count = (await page.locator('.settings-table-count').boundingBox())!
  expect(count.x + count.width).toBeLessThanOrEqual(900)
  await page.getByRole('button', { name: /^Modifier / }).first().click()
  await expect(page.getByLabel('Code', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Code', { exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Annuler', exact: true }).click()
  await expect(page.getByLabel('Code', { exact: true })).not.toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-settings-shared-table-dark.png' })
})
