import { test, expect } from '@playwright/test'
import { defaultLayout, newBlock, printableWidth } from '../../src/modules/documents/schemas/templates'
async function login(page: import('@playwright/test').Page, email = 'erp-admin@local.invalid') {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail', { exact: true }).fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill('Local-Horizon-test-only-2026!')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
}
async function expandTools(page: import('@playwright/test').Page) {
  await expect(page.locator('.studio-library')).toBeVisible()
  for (const section of await page.locator('.studio-section').all()) {
    if (await section.isVisible() && await section.getAttribute('open') === null) { await section.locator('summary').click(); await expect(section).toHaveAttribute('open', '') }
  }
}
test('Studio : création, position au pixel, titres, publication et relecture', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 })
  await login(page)
  await page.goto('/settings/documents')
  await page.getByRole('link', { name: 'Nouveau modèle' }).click()
  await expandTools(page)
  await page.getByLabel('Nom du modèle', { exact: true }).fill('Modèle studio recette')
  await page.getByRole('button', { name: 'Sélectionner Champ lié' }).first().click()
  await expandTools(page)
  await page.getByLabel('Largeur (px)', { exact: true }).fill('500')
  await page.getByLabel('X (px)', { exact: true }).fill('20')
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expandTools(page)
  await page.getByLabel('Taille du texte (px)', { exact: true }).first().fill('16')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/settings\/documents\/(?!new)/)
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Publier', exact: true }).click()
  await page.getByRole('dialog', { name: 'Publier le modèle' }).getByRole('button', { name: 'Confirmer', exact: true }).click()
  await expect(page.locator('.page-header')).toContainText('Version publiée 1')
  await page.reload()
  await page.getByRole('button', { name: 'Sélectionner Champ lié' }).first().click()
  await expandTools(page)
  await expect(page.getByLabel('X (px)', { exact: true })).toHaveValue('20')
  await expect(page.getByLabel('Largeur (px)', { exact: true })).toHaveValue('500')
  await page.screenshot({ path: '/private/tmp/horizon-document-studio.png', fullPage: true })
  // Drag coordinates stay in layout pixels despite the 75% zoom.
  const handle = page.getByRole('button', { name: 'Déplacer le bloc', exact: true }), box = (await handle.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 15, box.y + box.height / 2 + 3, { steps: 3 }); await page.mouse.up()
  await expect(page.getByLabel('X (px)', { exact: true })).toHaveValue('40')
  await page.getByRole('button', { name: 'Annuler les modifications', exact: true }).click()
  await expect(page.getByLabel('X (px)', { exact: true })).toHaveValue('20')
  await expandTools(page)
  const library = page.locator('.studio-library').getByRole('button', { name: 'Texte', exact: true })
  const source = (await library.boundingBox())!, target = (await page.locator('.studio-canvas-scroll').boundingBox())!
  await page.mouse.move(source.x + 25, source.y + 12); await page.mouse.down()
  await page.mouse.move(target.x + 80, target.y + 180, { steps: 8 }); await page.mouse.up()
  await expect(page.getByRole('button', { name: 'Sélectionner Texte', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expandTools(page)
  await page.getByRole('checkbox', { name: 'Remise %', exact: true }).check()
  await page.getByLabel('Largeur Description', { exact: true }).fill('65')
  await expect(page.locator('.studio-column-fields').getByText('100 %', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
})
test('Studio : blocs côte à côte, logo, provenance des champs et typographie', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 })
  await login(page)
  await page.goto('/settings/documents/new')
  await expandTools(page)
  await page.getByRole('button', { name: 'Sélectionner Champ lié' }).nth(1).click()
  await expandTools(page)
  await page.getByRole('combobox', { name: 'Disposition du bloc', exact: true }).click()
  await page.getByRole('option', { name: 'Même ligne que le bloc précédent', exact: true }).click()
  const row = page.locator('.studio-flow-row').first()
  await expect(row.locator('.studio-block')).toHaveCount(2)
  const first = (await row.locator('.studio-block').first().boundingBox())!, second = (await row.locator('.studio-block').last().boundingBox())!
  expect(Math.abs(first.y - second.y)).toBeLessThan(1)
  expect(second.x).toBeGreaterThan(first.x + first.width)
  await page.getByRole('combobox', { name: 'Champ lié', exact: true }).click()
  await page.getByRole('option', { name: 'Adresse complète', exact: true }).click()
  await page.getByRole('button', { name: 'Gras', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Gras', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('combobox', { name: 'Police du texte', exact: true }).click()
  await page.getByRole('option', { name: 'Noto Serif', exact: true }).click()
  await page.getByRole('button', { name: 'Augmenter le zoom', exact: true }).click()
  await expect(page.locator('.studio-zoom output')).toHaveText('85 %')
  await page.getByRole('button', { name: 'Réduire le zoom', exact: true }).click()
  await expect(page.locator('.studio-zoom output')).toHaveText('75 %')
  await page.locator('.studio-library').getByRole('button', { name: 'Logo / image', exact: true }).click()
  await expandTools(page)
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Importer un logo', exact: true }).click()
  const png = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 300; canvas.height = 150; const context = canvas.getContext('2d')!; context.fillStyle = '#7B3FC7'; context.fillRect(0, 0, 300, 150); return canvas.toDataURL('image/png').split(',')[1]! })
  await (await chooser).setFiles({ name: 'logo.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') })
  await expect(page.getByAltText('Logo importé', { exact: true })).toBeVisible()
  await expect(page.getByAltText('Logo du modèle', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Largeur (px)', { exact: true })).toHaveValue('300')
  await expect(page.getByLabel('Hauteur min. (px)', { exact: true })).toHaveValue('150')
  await page.getByLabel('Largeur (px)', { exact: true }).fill('200')
  await expect(page.getByLabel('Hauteur min. (px)', { exact: true })).toHaveValue('100')
  const resize = (await page.getByRole('button', { name: 'Redimensionner le bloc', exact: true }).boundingBox())!
  await page.mouse.move(resize.x + resize.width / 2, resize.y + resize.height / 2); await page.mouse.down(); await page.mouse.move(resize.x + resize.width / 2 + 75, resize.y + resize.height / 2, { steps: 5 }); await page.mouse.up()
  await expect(page.getByLabel('Largeur (px)', { exact: true })).toHaveValue('300')
  await expect(page.getByLabel('Hauteur min. (px)', { exact: true })).toHaveValue('150')
  const picture = (await page.getByAltText('Logo du modèle', { exact: true }).boundingBox())!
  const imageBlock = (await page.getByRole('button', { name: 'Sélectionner Logo / image', exact: true }).boundingBox())!
  expect(imageBlock.width / imageBlock.height).toBeCloseTo(2, 1)
  expect(picture.width / picture.height).toBeCloseTo(2, 1)
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expandTools(page)
  await expect(page.getByRole('combobox', { name: 'Source du tableau', exact: true })).toHaveText('Ventes · Lignes du devis')
  await page.screenshot({ path: '/private/tmp/horizon-studio-D02.png', fullPage: true })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.locator('.studio-flow-row').first().locator('.studio-block')).toHaveCount(2)
  await expect(page.getByAltText('Logo du modèle', { exact: true })).toBeVisible()
})
test('Studio : texte enrichi visible, duplication locale, ancrage, poignée et zoom adapté', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 })
  await login(page)
  await page.goto('/settings/documents/new')
  await expandTools(page)
  await page.locator('.studio-library').getByRole('button', { name: 'Texte', exact: true }).click()
  await expandTools(page)
  const editor = page.getByRole('textbox', { name: 'Texte du bloc', exact: true })
  await editor.fill('Texte bien formaté')
  await editor.press('ControlOrMeta+A')
  await page.getByRole('button', { name: 'Gras', exact: true }).click()
  await expect(page.locator('.studio-block strong').filter({ hasText: 'Texte bien formaté' })).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Gras', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: 'Dupliquer le bloc', exact: true }).click()
  const textBlocks = page.getByRole('button', { name: 'Sélectionner Texte', exact: true })
  await expect(textBlocks).toHaveCount(2)
  const original = (await textBlocks.first().boundingBox())!, duplicate = (await textBlocks.last().boundingBox())!
  expect(duplicate.y).toBeGreaterThan(original.y)
  await page.getByLabel('Largeur (px)', { exact: true }).fill('200')
  await page.getByRole('button', { name: 'Coller à droite', exact: true }).click()
  await expect(page.getByLabel('X (px)', { exact: true })).toHaveValue('503')
  await page.getByRole('button', { name: 'Coller en haut', exact: true }).click()
  await expect(page.locator('.studio-body-zone .studio-block').first()).toContainText('Texte bien formaté')
  const grip = page.getByRole('button', { name: 'Déplacer le bloc', exact: true }), from = (await grip.boundingBox())!
  const target = (await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).boundingBox())!
  await page.mouse.move(from.x + 10, from.y + 10); await page.mouse.down()
  await page.mouse.move(from.x - 10, target.y + target.height + 8, { steps: 8 }); await page.mouse.up()
  const ordered = await page.locator('.studio-body-zone .studio-block').allTextContents()
  expect(ordered.findIndex((text) => text.includes('Texte bien formaté'))).toBeGreaterThan(ordered.findIndex((text) => text.includes('Lignes du devis')))
  await page.getByRole('button', { name: 'Adapter la page à l’écran', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Adapter la page à l’écran', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(async () => (await page.locator('.studio-page').boundingBox())!.height).toBeLessThan((await page.locator('.studio-canvas-scroll').boundingBox())!.height)
  const sheet = (await page.locator('.studio-page').boundingBox())!, stage = (await page.locator('.studio-canvas-scroll').boundingBox())!
  expect(sheet.width).toBeLessThan(stage.width)
  expect(sheet.height).toBeLessThan(stage.height)
  await page.screenshot({ path: '/private/tmp/horizon-studio-D03.png', fullPage: true })
  await page.getByRole('button', { name: 'Retirer ce bloc', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Supprimer ce bloc', exact: true })).toBeVisible()
})
test('Studio : bibliothèque générique, anciens textes gras et trois niveaux de titres', async ({ page }) => {
  await login(page)
  const token = await page.evaluate(() => sessionStorage.getItem('horizon.auth.token')!)
  const model = defaultLayout(), text = newBlock('text', printableWidth(model)); text.text = 'Ancien texte gras'; text.style.bold = true; model.blocks.push(text)
  model.blocks.push(newBlock('totals', printableWidth(model)), newBlock('terms', printableWidth(model)))
  const response = await page.request.post('http://127.0.0.1:18090/api/horizon/documents/templates/save', { headers: { Authorization: token }, data: { name: 'Texte ancien et titres', content_json: model } })
  expect(response.status()).toBe(200)
  const record = await response.json()
  await page.goto(`/settings/documents/${record.id}`)
  await expandTools(page)
  const library = page.locator('.studio-library')
  await expect(library.getByRole('button', { name: 'Tableau', exact: true })).toBeVisible()
  await expect(library.getByRole('button', { name: 'Totaux', exact: true })).toHaveCount(0)
  await expect(library.getByRole('button', { name: 'Conditions de vente', exact: true })).toHaveCount(0)
  await expect(page.getByText('Titre niveau 1', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Sélectionner Texte', exact: true }).click()
  await expandTools(page)
  const editor = page.getByRole('textbox', { name: 'Texte du bloc', exact: true })
  await expect(page.locator('.studio-block strong').filter({ hasText: 'Ancien texte gras' })).toHaveCount(1)
  await editor.press('ControlOrMeta+A')
  await page.getByRole('button', { name: 'Gras', exact: true }).click()
  await expect(page.locator('.studio-block strong').filter({ hasText: 'Ancien texte gras' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Gras', exact: true })).toHaveAttribute('aria-pressed', 'false')
  for (const level of [1, 2, 3]) {
    await page.getByRole('combobox', { name: 'Style de paragraphe', exact: true }).click()
    await page.getByRole('option', { name: `Titre ${level}`, exact: true }).click()
    await expect(page.locator(`.studio-block h${level}`)).toHaveText('Ancien texte gras')
  }
  await page.getByRole('combobox', { name: 'Style de paragraphe', exact: true }).click()
  await page.getByRole('option', { name: 'Texte normal', exact: true }).click()
  await expect(page.locator('.studio-block p')).toHaveText('Ancien texte gras')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D04.png', fullPage: true })
  await page.reload()
  await expect(page.locator('.studio-block strong').filter({ hasText: 'Ancien texte gras' })).toHaveCount(0)
  const saved = await page.request.get(`http://127.0.0.1:18090/api/horizon/documents/templates/${record.id}`, { headers: { Authorization: token } })
  expect(saved.status()).toBe(200)
  expect((await saved.json()).content_json.blocks.every((block: { kind: string }) => block.kind !== 'totals' && block.kind !== 'terms')).toBe(true)
})
test('Devis : aperçu réel, modèle publié et téléchargement PDF', async ({ page }) => {
  await login(page)
  const token = await page.evaluate(() => sessionStorage.getItem('horizon.auth.token')!)
  const headers = { Authorization: token }, root = 'http://127.0.0.1:18090/api/'
  async function post(path: string, data: unknown) { const response = await page.request.post(root + path, { headers, data }); expect(response.status()).toBe(200); return response.json() }
  const auth = await post('collections/core_users/auth-refresh', {})
  const company = await post('collections/contacts_companies/records', { name: 'Client PDF réel', active: true })
  const stages = await (await page.request.get(root + 'collections/crm_stages/records?filter=active%3Dtrue&sort=sort_order', { headers })).json()
  const opportunity = await post('horizon/crm/save', { creation_key: crypto.randomUUID(), input: { title: 'Affaire PDF', company: company.id, contact: '', owner: auth.record.id, stage: stages.items[0].id, estimated_value: 1000, estimated_cost: 0, currency: 'EUR', probability: 30, expected_date: '', description: '', status: 'open' } })
  const quote = await post('horizon/sales/quotes/save', { creation_key: crypto.randomUUID(), input: { opportunity: opportunity.id, title: 'Proposition PDF', quote_date: '2026-10-08', valid_until: '2026-11-07', lines: [{ kind: 'section', description: 'Équipements', show_total: true }, { kind: 'item', description: 'Prestation visible dans le document', quantity: 2, unit: 'u', unit_price: 125, unit_cost: 50 }] } })
  const model = defaultLayout(); model.background = { color: '#E8EDF4', image: '', opacity: 0.35, fit: 'contain' }; const header = newBlock('text', 180); header.zone = 'header'; header.x = printableWidth(model) - 180; header.y = 8; header.text = 'CVS en tête'; header.style.font = 'Open Sans'; header.style.size = 18; header.style.bold = true; model.blocks.push(header)
  const draft = await post('horizon/documents/templates/save', { name: 'Modèle PDF recette', content_json: model })
  await post('horizon/documents/templates/publish', { id: draft.id, updated: draft.updated })
  await page.goto(`/sales/quotes/${quote.id}`)
  await page.getByRole('button', { name: 'PDF', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Aperçu du devis', exact: true })
  await dialog.getByRole('combobox', { name: 'Modèle du devis', exact: true }).click()
  await page.getByRole('option', { name: 'Modèle PDF recette · v1', exact: true }).click()
  await dialog.getByRole('button', { name: 'Aperçu HTML', exact: true }).click()
  await expect(page.frameLocator('iframe[title="Aperçu du devis enregistré"]').getByText('Prestation visible dans le document')).toBeVisible()
  await expect(page.frameLocator('iframe[title="Aperçu du devis enregistré"]').locator(`[data-block-id="${model.blocks.find((block) => block.field === 'quote.total')!.id}"]`)).toHaveText('Total TTC : 300,00 €')
  const frame = page.frameLocator('iframe[title="Aperçu du devis enregistré"]')
  await expect(frame.locator('.document-paper-background')).toHaveCSS('opacity', '0.35')
  await expect(frame.locator(`[data-block-id="${model.blocks[0]!.id}"]`)).toHaveCSS('opacity', '1')
  await expect(frame.locator(`[data-block-id="${header.id}"]`)).toHaveCSS('position', 'absolute')
  await expect(frame.locator(`[data-block-id="${header.id}"]`)).toHaveCSS('left', `${header.x}px`)
  await expect(frame.locator(`[data-block-id="${header.id}"]`)).toHaveCSS('top', '8px')
  await expect(frame.locator(`[data-block-id="${model.blocks[0]!.id}"]`)).toHaveCSS('font-size', '24px')
  await expect(frame.locator(`[data-block-id="${model.blocks[0]!.id}"]`)).toHaveCSS('color', 'rgb(123, 63, 199)')
  await expect(frame.getByText('Équipements', { exact: true }).locator('..')).toHaveCSS('color', 'rgb(123, 63, 199)')
  await page.screenshot({ path: '/private/tmp/horizon-document-preview.png', fullPage: true })
  // PDF transport is covered against a local converter in the backend suite.
  // Here assert the browser can download the binary response without JSON decoding.
  await page.route('**/api/horizon/documents/preview', (route) => route.fulfill({ status: 200, contentType: 'application/pdf', body: '%PDF-1.7\nlocal browser test\n%%EOF' }))
  const download = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'PDF', exact: true }).click()
  expect((await download).suggestedFilename()).toBe('devis.pdf')
  await page.unroute('**/api/horizon/documents/preview')
  await page.goto(`/settings/documents/${draft.id}`)
  await expandTools(page)
  await page.getByRole('button', { name: 'Aperçu / PDF', exact: true }).click()
  await page.getByRole('combobox', { name: 'Devis de l’aperçu', exact: true }).click()
  await page.getByRole('option', { name: `${quote.quote_number} · Client PDF réel · Proposition PDF`, exact: true }).click()
  await page.getByRole('button', { name: 'Ouvrir la fiche : Devis de l’aperçu', exact: true }).click()
  const sourceDialog = page.getByRole('dialog', { name: 'Fiche devis', exact: true })
  await expect(sourceDialog.getByLabel('Titre du devis', { exact: true })).toHaveValue('Proposition PDF')
  await sourceDialog.getByLabel('Titre du devis', { exact: true }).fill('Proposition PDF modifiée')
  await sourceDialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(sourceDialog).toHaveCount(0)
  await expect(page).toHaveURL(`/settings/documents/${draft.id}`)
  await expect(page.getByRole('dialog', { name: 'Aperçu du devis', exact: true })).toBeVisible()
})
test('Studio : un utilisateur métier ne peut pas administrer les modèles', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.goto('/settings/documents/new')
  await expect(page.getByText('La gestion des modèles est réservée aux administrateurs et superusers habilités.')).toBeVisible()
})

test('Studio : fonds, panneaux ajustables et texte à hauteur évolutive', async ({ page }) => {
  await login(page)
  const token = await page.evaluate(() => sessionStorage.getItem('horizon.auth.token')!)
  const response = await page.request.post('http://127.0.0.1:18090/api/horizon/documents/templates/save', { headers: { Authorization: token }, data: { name: 'Fond et panneaux', content_json: defaultLayout() } })
  expect(response.status()).toBe(200)
  const record = await response.json()
  await page.goto(`/settings/documents/${record.id}`)
  await expandTools(page)
  await page.getByLabel('Couleur du fond', { exact: true }).fill('#e8edf4')
  await page.getByRole('spinbutton', { name: 'Opacité du fond de page (%)', exact: true }).fill('35')
  const backdrop = page.locator('.studio-paper-background')
  await expect(backdrop).toHaveCSS('opacity', '0.35')
  const backgroundFile = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Ajouter une image', exact: true }).click()
  const png = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 16; canvas.height = 8; const context = canvas.getContext('2d')!; context.fillStyle = '#7b3fc7'; context.fillRect(0, 0, 16, 8); return canvas.toDataURL().split(',')[1]! })
  await (await backgroundFile).setFiles({ name: 'fond.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') })
  await expect(backdrop.locator('img')).toHaveCSS('object-fit', 'contain')
  await page.getByRole('combobox', { name: 'Ajustement de l’image de fond', exact: true }).click()
  await page.getByRole('option', { name: 'Remplir la page', exact: true }).click()
  await expect(backdrop.locator('img')).toHaveCSS('object-fit', 'cover')
  for (const [name, offset] of [['Largeur de la bibliothèque', 30], ['Largeur des propriétés', -45]] as const) {
    const separator = page.getByRole('separator', { name, exact: true })
    const before = Number(await separator.getAttribute('aria-valuenow')), bounds = (await separator.boundingBox())!
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + 100)
    await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + offset, bounds.y + 100); await page.mouse.up()
    expect(Number(await separator.getAttribute('aria-valuenow'))).toBeGreaterThan(before)
  }
  const widths = await page.locator('.studio-workspace').evaluate((element) => ({ left: element.style.getPropertyValue('--studio-library-width'), right: element.style.getPropertyValue('--studio-properties-width') }))
  await page.locator('.studio-library').getByRole('button', { name: 'Texte', exact: true }).click()
  await expandTools(page)
  const editor = page.getByRole('textbox', { name: 'Texte du bloc', exact: true })
  await editor.fill('Court')
  const initialHeight = (await editor.boundingBox())!.height
  expect(initialHeight).toBeLessThan(75)
  await editor.fill('Un\nDeux\nTrois\nQuatre\nCinq\nSix')
  expect((await editor.boundingBox())!.height).toBeGreaterThan(initialHeight)
  await page.getByLabel('Couleur du fond du bloc', { exact: true }).fill('#7b3fc7')
  await page.getByRole('spinbutton', { name: 'Opacité du fond (%)', exact: true }).fill('50')
  await expect(page.locator('.studio-block[data-selected=true]')).toHaveCSS('background-color', 'rgba(123, 63, 199, 0.5)')
  await expect(page.locator('.studio-block[data-selected=true]')).toHaveCSS('opacity', '1')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Adapter la page à l’écran', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D05.png', fullPage: true })
  await page.reload()
  await expect(backdrop).toHaveCSS('opacity', '0.35')
  await expect(backdrop.locator('img')).toHaveCSS('object-fit', 'cover')
  expect(await page.locator('.studio-workspace').evaluate((element) => ({ left: element.style.getPropertyValue('--studio-library-width'), right: element.style.getPropertyValue('--studio-properties-width') }))).toEqual(widths)
  const saved = await page.request.get(`http://127.0.0.1:18090/api/horizon/documents/templates/${record.id}`, { headers: { Authorization: token } })
  expect((await saved.json()).content_json.background.opacity).toBe(0.35)
  await page.getByRole('separator', { name: 'Largeur des propriétés', exact: true }).press('Home')
  await expect(page.getByRole('separator', { name: 'Largeur des propriétés', exact: true })).toHaveAttribute('aria-valuenow', '340')
  await page.getByRole('button', { name: 'Retirer le fond de page', exact: true }).click()
  await expect(backdrop).toHaveCount(0)
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('.studio-page')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.screenshot({ path: '/private/tmp/horizon-studio-D05-dark.png', fullPage: true })
  await page.setViewportSize({ width: 900, height: 900 })
  await expect(page.getByRole('separator', { name: 'Largeur des propriétés', exact: true })).toBeHidden()
  await expect(page.getByRole('button', { name: 'Page', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-studio-D05-responsive.png', fullPage: true })
})

test('Studio : groupes repliables, couleurs compactes et opacité au clavier', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  const token = await page.evaluate(() => sessionStorage.getItem('horizon.auth.token')!)
  const response = await page.request.post('http://127.0.0.1:18090/api/horizon/documents/templates/save', { headers: { Authorization: token }, data: { name: 'Groupes du studio', content_json: defaultLayout() } })
  expect(response.status()).toBe(200)
  await page.goto(`/settings/documents/${(await response.json()).id}`)
  await expandTools(page)
  const library = page.locator('details[data-section=library]'), layers = page.locator('details[data-section=layers]')
  const pageBackground = page.locator('details[data-section=page-background]')
  await page.getByRole('textbox', { name: 'Code hexadécimal : Couleur du fond', exact: true }).fill('#eff2f7')
  await expect(page.getByLabel('Couleur du fond', { exact: true })).toHaveValue('#eff2f7')
  const slider = page.getByRole('slider', { name: 'Opacité du fond de page', exact: true })
  await page.getByRole('spinbutton', { name: 'Opacité du fond de page (%)', exact: true }).fill('35'); await slider.press('ArrowRight')
  await expect(page.getByRole('spinbutton', { name: 'Opacité du fond de page (%)', exact: true })).toHaveValue('36')
  await pageBackground.locator('summary').click()
  await expect(slider).toBeHidden()
  await pageBackground.locator('summary').click()
  await expect(slider).toHaveValue('36')
  await page.locator('details[data-section=page-format]').locator('summary').click()
  await library.getByRole('button', { name: 'Texte', exact: true }).click()
  await expandTools(page)
  const editor = page.getByRole('textbox', { name: 'Texte du bloc', exact: true })
  await editor.fill('Contenu conservé quand on replie')
  const appearance = page.locator('details[data-section=appearance]'), content = page.locator('details[data-section=text-content]')
  const hex = page.getByRole('textbox', { name: 'Code hexadécimal : Couleur du texte', exact: true })
  await hex.fill('#7b3fc7')
  await expect(page.locator('.studio-block[data-selected=true]')).toHaveCSS('color', 'rgb(123, 63, 199)')
  await hex.fill('#1'); await expect(hex).toHaveAttribute('aria-invalid', 'true')
  await appearance.locator('summary').click()
  await expect(hex).toBeHidden()
  await content.locator('summary').click(); await expect(editor).toBeHidden()
  await content.locator('summary').click(); await expect(editor).toHaveText('Contenu conservé quand on replie')
  await library.locator('summary').click(); await expect(library.getByRole('button', { name: 'Texte', exact: true })).toBeHidden()
  await expect(layers.locator('.studio-layer')).toHaveCount(10)
  await layers.locator('summary').click(); await expect(layers.locator('.studio-layer').first()).toBeHidden()
  await layers.locator('summary').click()
  await page.getByRole('button', { name: 'Adapter la page à l’écran', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D06.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(library.getByRole('button', { name: 'Texte', exact: true })).toBeHidden()
  await expect(layers.locator('.studio-layer')).toHaveCount(10)
  await expect(page.locator('details[data-section=page-format]')).not.toHaveAttribute('open', '')
  await page.getByRole('button', { name: 'Sélectionner Texte', exact: true }).click()
  await expect(hex).toBeHidden()
  await appearance.locator('summary').click()
  await expect(hex).toHaveValue('#7B3FC7')
  await expect(editor).toHaveText('Contenu conservé quand on replie')
  await page.getByRole('button', { name: 'Page', exact: true }).click()
  await expect(page.locator('details[data-section=page-format]')).not.toHaveAttribute('open', '')
  await page.getByRole('button', { name: 'Bloc', exact: true }).click()
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D06-dark.png', fullPage: true, animations: 'disabled' })
})


test('Studio : sections fermées, titres réservés au tableau et statut à droite', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  await page.goto('/settings/documents/new')
  await expect(page.locator('.studio-section')).not.toHaveCount(0)
  await expect(page.locator('.studio-section[open]')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Titres', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Sélectionner Champ lié' }).first().click()
  await expect(page.locator('[data-section=table-headings]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  const titles = page.locator('[data-section=table-headings]')
  await expect(titles).not.toHaveAttribute('open', '')
  await titles.locator('summary').click()
  await titles.getByLabel('Taille du texte (px)', { exact: true }).fill('17')
  await expect(page.locator('.studio-model-status')).toContainText('Brouillon')
  await expect(page.locator('.studio-model-status').getByRole('button', { name: 'Publier', exact: true })).toBeVisible()
  const ribbon = (await page.locator('.page-header').boundingBox())!
  const name = (await page.getByLabel('Nom du modèle', { exact: true }).boundingBox())!
  expect(Math.abs(name.x + name.width / 2 - (ribbon.x + ribbon.width / 2))).toBeLessThan(2)
  await page.getByLabel('Nom du modèle', { exact: true }).fill('Tableaux indépendants')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/settings\/documents\/(?!new)/)
  await expect(page.locator('.studio-model-status').getByRole('button', { name: 'Archiver le modèle', exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expect(titles.getByLabel('Taille du texte (px)', { exact: true })).toHaveValue('17')
  await page.screenshot({ path: '/private/tmp/horizon-studio-D07.png', fullPage: true })
  await page.setViewportSize({ width: 1000, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-studio-D07-responsive.png', fullPage: true })
})

test('Studio : colonnes sur une ligne, largeur, ordre et bandeau compact sombre', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  await page.goto('/settings/documents/new')
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  const data = page.locator('[data-section=table-data]')
  await data.locator('summary').click()
  const row = data.locator('.studio-column-row').filter({ has: page.getByRole('checkbox', { name: 'Description', exact: true }) })
  const checkbox = (await row.getByRole('checkbox').boundingBox())!
  const name = (await row.getByLabel('Libellé Description', { exact: true }).boundingBox())!
  const width = (await row.getByLabel('Largeur Description', { exact: true }).boundingBox())!
  const arrows = (await row.locator('.studio-column-order').boundingBox())!
  for (const box of [name, width, arrows]) expect(Math.abs(box.y + box.height / 2 - checkbox.y - checkbox.height / 2)).toBeLessThan(2)
  expect(checkbox.x).toBeLessThan(name.x)
  expect(name.x + name.width).toBeLessThan(width.x)
  expect(width.x + width.width).toBeLessThan(arrows.x)
  expect((await row.boundingBox())!.height).toBeLessThan(39)
  await row.getByLabel('Libellé Description', { exact: true }).fill('Désignation')
  await row.getByLabel('Largeur Description', { exact: true }).fill('60')
  await expect(data.locator('.studio-column-total')).toContainText('100 %')
  await row.getByRole('button', { name: 'Reculer Description', exact: true }).click()
  await expect(data.locator('.studio-column-row').first().getByRole('checkbox')).toHaveAccessibleName('Marque')
  await data.getByRole('checkbox', { name: 'Remise %', exact: true }).check()
  await expect(data.getByLabel('Largeur Remise %', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/settings\/documents\/(?!new)/)
  await page.getByRole('button', { name: 'Sélectionner Tableau', exact: true }).click()
  await expect(data.getByLabel('Libellé Description', { exact: true })).toHaveValue('Désignation')
  await expect(page.locator('.studio-model-status').getByRole('button', { name: 'Publier', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D08-dark.png', fullPage: true })
  await page.getByRole('button', { name: 'Passer en mode clair', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-studio-D08-light.png', fullPage: true })
  const resizer = page.getByRole('separator', { name: 'Largeur des propriétés', exact: true })
  await resizer.focus(); await resizer.press('ArrowLeft')
  await page.setViewportSize({ width: 1200, height: 900 })
  await page.screenshot({ path: '/private/tmp/horizon-studio-D08-narrow.png', fullPage: true })
  await expect.poll(async () => (await page.locator('.studio-workspace').boundingBox())!.x + (await page.locator('.studio-workspace').boundingBox())!.width).toBeLessThanOrEqual(1200)
})
