import { expect, test } from '@playwright/test'

const testPassword = 'Local-Horizon-test-only-2026!'

test('connexion réelle, retour à la page demandée, déconnexion et purge du token de session', async ({ page }) => {
  await page.goto('/contacts')
  await expect(page).toHaveURL('/login')
  await page.getByLabel('Adresse e-mail').fill('reader@local.invalid')
  await page.getByLabel('Mot de passe').fill(testPassword)
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/contacts')
  await expect(page.getByText('Utilisateur test', { exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('link', { name: 'CRM', exact: true }).click()
  await expect(page).toHaveURL('/crm')
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
  expect(await page.context().cookies()).toEqual([])
  await page.getByRole('button', { name: 'Se déconnecter' }).click()
  await expect(page).toHaveURL('/login')
  expect(await page.evaluate(() => sessionStorage.getItem('horizon.auth.token'))).toBeNull()
  await page.goBack()
  await expect(page).toHaveURL('/login')
})

test('erreurs de saisie et mauvais mot de passe sans fuite technique', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page.getByText('Saisissez une adresse e-mail valide.')).toBeVisible()
  await page.getByLabel('Adresse e-mail').fill('reader@local.invalid')
  await page.getByLabel('Mot de passe').fill('wrong')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Connexion refusée. Vérifiez vos identifiants ou contactez votre administrateur.')
  await expect(page.getByLabel('Mot de passe')).toHaveValue('')
  await expect(page).toHaveURL('/login')
})

test('session conservée après rechargement et connexion responsive', async ({ page }) => {
  await page.goto('/login')
  await page.screenshot({ path: '/private/tmp/horizon-login-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-login-mobile.png', fullPage: true })
  await page.getByLabel('Adresse e-mail').fill('reader@local.invalid')
  await page.getByLabel('Mot de passe').fill(testPassword)
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 1440, height: 900 })
  await expect(page).toHaveURL('/')
  await page.getByRole('button', { name: 'Se déconnecter' }).click()
  await page.reload()
  await expect(page).toHaveURL('/login')
})

test('aucune page protégée si le serveur refuse la restauration', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail').fill('reader@local.invalid')
  await page.getByLabel('Mot de passe').fill(testPassword)
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
  await page.route('**/api/collections/core_users/auth-refresh*', (route) => route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ status: 403, message: 'Forbidden', data: {} }) }))
  await page.reload()
  await expect(page).toHaveURL('/login')
  await expect(page.getByRole('alert')).toHaveText('Votre session n’est plus autorisée. Veuillez vous reconnecter.')
  await expect(page.getByText('Utilisateur test', { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => sessionStorage.getItem('horizon.auth.token'))).toBeNull()
})

test('restauration attendue avant affichage et onglet indépendant', async ({ page, context }) => {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail').fill('reader@local.invalid')
  await page.getByLabel('Mot de passe').fill(testPassword)
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
  const other = await context.newPage()
  await other.goto('/contacts')
  await expect(other).toHaveURL('/login')
  await other.close()
  let release: (() => void) | undefined
  const gate = new Promise<void>((resolve) => { release = resolve })
  await page.route('**/api/collections/core_users/auth-refresh*', async (route) => { await gate; await route.continue() })
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('status')).toHaveText('Vérification de votre session…')
  await expect(page.getByText('Utilisateur test', { exact: true })).toHaveCount(0)
  release?.()
  await expect(page.getByText('Utilisateur test', { exact: true })).toBeVisible()
})
