import { test, expect, type Page } from '@playwright/test'
async function login(page: Page, email: string) {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail', { exact: true }).fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill('Local-Horizon-test-only-2026!')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
}
test('menu logo : destinations sidebar, clavier et responsive', async ({ page }) => {
  await login(page, 'erp-admin@local.invalid')
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/inventory')
  const sidebar = page.getByRole('navigation', { name: 'Navigation principale', exact: true })
  await expect(sidebar).toBeVisible()
  const destinations = await sidebar.locator('a.sidebar-link:not(.sidebar-submenu-link)').evaluateAll((links) => links.map((link) => link.getAttribute('href')).sort())
  const logo = page.getByRole('button', { name: 'Ouvrir les modules Horizon', exact: true })
  await logo.click()
  const dialog = page.getByRole('dialog', { name: 'Modules Horizon', exact: true })
  await expect(dialog).toBeVisible()
  await expect(page).toHaveURL(/\/inventory$/)
  await expect(page.locator('.module-launcher-overlay')).toHaveCSS('backdrop-filter', 'blur(5px)')
  const tile = (await dialog.getByRole('link', { name: 'Dashboard', exact: true }).boundingBox())!
  expect(Math.abs(tile.width - tile.height)).toBeLessThan(1)
  await expect(dialog).toHaveCSS('color', 'rgb(237, 243, 251)')
  expect(await dialog.locator('a').evaluateAll((links) => links.map((link) => link.getAttribute('href')).sort())).toEqual(destinations)
  for (const label of ['Ressources humaines', 'Finance', 'Administration']) await expect(dialog.getByRole('heading', { name: label, exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-module-launcher.png' })
  await expect(dialog.getByRole('link', { name: 'Clients', exact: true })).toHaveCount(0)
  await dialog.getByRole('link', { name: 'Contacts', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page).toHaveURL(/\/contacts$/)
  await page.getByRole('button', { name: 'Réduire la navigation', exact: true }).click()
  await logo.click()
  await dialog.getByRole('link', { name: 'Ventes', exact: true }).click()
  await expect(page).toHaveURL(/\/sales(?:\/quotes)?$/)
  await expect(dialog).not.toBeVisible()
  await logo.click()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(logo).toBeFocused()
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await logo.click()
  await expect(dialog).toBeVisible()
  const bounds = (await dialog.boundingBox())!
  expect(bounds.x).toBeGreaterThanOrEqual(64)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(390)
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-module-launcher-mobile-dark.png' })
  await dialog.getByRole('link', { name: 'Dashboard', exact: true }).click()
  await expect(page).toHaveURL('/')
})
test('menu logo : mêmes restrictions que la sidebar', async ({ page }) => {
  await login(page, 'writer@local.invalid')
  await page.getByRole('button', { name: 'Ouvrir les modules Horizon', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Modules Horizon', exact: true })
  await expect(dialog.getByRole('link', { name: 'Contacts', exact: true })).toBeVisible()
  for (const label of ['Paramètres', 'Stock', 'Comptabilité']) await expect(dialog.getByRole('link', { name: label, exact: true })).toHaveCount(0)
  await dialog.getByRole('link', { name: 'Contacts', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts$/)
})
