import { test, expect, type Page, type Locator } from '@playwright/test'
async function expectWorkspaceCentered(page: Page, dialog: Locator) {
  const workspace = (await page.locator('.app-workspace').boundingBox())!
  const popup = (await dialog.boundingBox())!
  expect(popup.x).toBeGreaterThan(workspace.x)
  expect(popup.x + popup.width).toBeLessThan(workspace.x + workspace.width)
  expect(Math.abs(popup.x + popup.width / 2 - workspace.x - workspace.width / 2)).toBeLessThan(1)
}
async function login(page: Page, email = 'crm@local.invalid') {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail', { exact: true }).fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill('Local-Horizon-test-only-2026!')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
}
test('création et édition liées : même fiche en popup, brouillon CRM conservé', async ({ page }) => {
  await login(page)
  await page.goto('/crm/opportunities/new')
  await page.getByLabel('Titre', { exact: true }).fill('Brouillon conservé')
  await page.getByLabel('Montant estimé', { exact: true }).fill('12345')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('combobox', { name: 'Rechercher : Société', exact: true }).fill('Client Popup Horizon')
  await page.screenshot({ path: '/private/tmp/horizon-record-picker-create.png' })
  await page.getByRole('button', { name: /Créer une société/ }).click()
  const company = page.getByRole('dialog', { name: 'Créer une société', exact: true })
  await expect(company.getByLabel('Nom usuel', { exact: true })).toHaveValue('Client Popup Horizon')
  await expect(company.getByRole('button', { name: 'Fermer', exact: true })).toHaveCount(1)
  await expectWorkspaceCentered(page, company)
  expect((await company.boundingBox())!.width).toBe(1000)
  await page.screenshot({ path: '/private/tmp/horizon-record-popup-expanded.png' })
  await expect(page).toHaveURL('/crm/opportunities/new')
  await company.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(company).not.toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Client Popup Horizon')
  const picker = page.locator('.h-record-picker').filter({ has: page.getByRole('combobox', { name: 'Société', exact: true }) })
  const triggerBox = (await picker.getByRole('combobox').boundingBox())!
  const clearBox = (await picker.getByRole('button', { name: 'Effacer : Société', exact: true }).boundingBox())!
  const inspectBox = (await picker.getByRole('button', { name: 'Ouvrir la fiche : Société', exact: true }).boundingBox())!
  const chevronBox = (await picker.locator('.h-combobox-chevron').boundingBox())!
  const centerY = (box: { y: number; height: number }) => box.y + box.height / 2
  expect(Math.abs(centerY(clearBox) - centerY(triggerBox))).toBeLessThan(1)
  expect(Math.abs(centerY(chevronBox) - centerY(triggerBox))).toBeLessThan(1)
  expect(Math.abs(centerY(inspectBox) - centerY(triggerBox))).toBeLessThan(1)
  expect(clearBox.x + clearBox.width).toBeLessThan(chevronBox.x)
  expect(Math.abs(inspectBox.x - triggerBox.x - triggerBox.width)).toBeLessThan(1)
  await page.screenshot({ path: '/private/tmp/horizon-record-picker-alignment.png' })
  await expect(page.getByLabel('Titre', { exact: true })).toHaveValue('Brouillon conservé')
  await expect(page.getByLabel('Montant estimé', { exact: true })).toHaveValue('12345.00')
  await page.getByRole('button', { name: 'Ouvrir la fiche : Société', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Fiche société', exact: true })
  const feed = editor.getByRole('region', { name: 'Fil d’activité', exact: true })
  await feed.scrollIntoViewIfNeeded()
  const feedBox = (await feed.boundingBox())!
  const body = editor.locator('.record-workspace-body')
  const bodyBox = (await body.boundingBox())!
  expect(Math.abs(feedBox.x - bodyBox.x)).toBeLessThan(1)
  expect(Math.abs(feedBox.width - await body.evaluate((element) => element.clientWidth))).toBeLessThan(1)
  await expect(feed).toHaveCSS('background-color', 'rgb(229, 235, 243)')
  await page.screenshot({ path: '/private/tmp/horizon-record-popup-discussion.png' })
  await editor.getByLabel('Nom usuel', { exact: true }).fill('Client Popup Modifié')
  await editor.getByRole('button', { name: 'Fermer', exact: true }).click()
  const warning = page.getByRole('alertdialog', { name: 'Fermer sans enregistrer ?' })
  await expect(warning).toBeVisible()
  await warning.getByRole('button', { name: 'Continuer la saisie', exact: true }).click()
  await editor.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Client Popup Modifié')
  await page.getByRole('combobox', { name: 'Contact', exact: true }).click()
  await page.getByRole('combobox', { name: 'Rechercher : Contact', exact: true }).fill('Popup Contact')
  await page.getByRole('button', { name: /Créer un contact/ }).click()
  const person = page.getByRole('dialog', { name: 'Créer un contact', exact: true })
  await expect(person.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Client Popup Modifié')
  await person.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(person).not.toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Contact', exact: true })).toHaveText('Popup Contact')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/crm\/opportunities\/(?!new)/)
  await expect(page.getByLabel('Titre', { exact: true })).toHaveValue('Brouillon conservé')
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Client Popup Modifié')
  await expect(page.getByRole('combobox', { name: 'Contact', exact: true })).toHaveText('Popup Contact')
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await page.getByRole('button', { name: 'Ouvrir la fiche : Contact', exact: true }).click()
  const contactEditor = page.getByRole('dialog', { name: 'Fiche contact', exact: true })
  await contactEditor.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('combobox', { name: 'Rechercher : Société', exact: true }).fill('Client imbriqué CRM')
  await page.getByRole('button', { name: /Créer une société/ }).click()
  await expect(company.getByLabel('Nom usuel', { exact: true })).toHaveValue('Client imbriqué CRM')
  await page.screenshot({ path: '/private/tmp/horizon-record-popup-dark.png' })
  await company.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(company).not.toBeVisible()
  await expect(contactEditor.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Client imbriqué CRM')
  await contactEditor.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(contactEditor).not.toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Client imbriqué CRM')
  await expect(page.getByLabel('Montant estimé', { exact: true })).toHaveValue('12345.00')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Client imbriqué CRM')
  await expect(page.getByRole('combobox', { name: 'Contact', exact: true })).toHaveText('Popup Contact')
})

test('créations imbriquées : société depuis contact, retour et annulation protégée', async ({ page }) => {
  await login(page)
  await page.goto('/contacts/people/new')
  await page.getByLabel('Nom', { exact: true }).fill('Parent non enregistré')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('combobox', { name: 'Rechercher : Société', exact: true }).fill('Société imbriquée')
  await page.getByRole('button', { name: /Créer une société/ }).click()
  const company = page.getByRole('dialog', { name: 'Créer une société', exact: true })
  await company.getByRole('button', { name: 'Fermer', exact: true }).click()
  const warning = page.getByRole('alertdialog', { name: 'Fermer sans enregistrer ?' })
  await warning.getByRole('button', { name: 'Abandonner les changements', exact: true }).click()
  await expect(company).not.toBeVisible()
  await expect(page.getByLabel('Nom', { exact: true })).toHaveValue('Parent non enregistré')
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Choisir…')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('button', { name: /Créer une société/ }).click()
  await company.getByLabel('Nom usuel', { exact: true }).fill('Société créée depuis contact')
  await page.setViewportSize({ width: 390, height: 844 })
  await expectWorkspaceCentered(page, company)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-record-popup-mobile.png' })
  await company.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(company).not.toBeVisible()
  await expect(page.getByLabel('Nom', { exact: true })).toHaveValue('Parent non enregistré')
  await expect(page.getByRole('combobox', { name: 'Société', exact: true })).toHaveText('Société créée depuis contact')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/people\/(?!new)/)
})

test('popups imbriqués et consultation en lecture seule', async ({ page }) => {
  await login(page)
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel', { exact: true }).fill('Client Nested Readonly')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/companies\/(?!new)/)
  await expect(page.locator('.page-breadcrumb-record-actions').getByRole('button', { name: 'Enregistrer', exact: true })).toBeVisible()
  await expect(page.locator('.page-breadcrumb-record-actions').getByRole('button', { name: 'Actions de la fiche', exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-contact-top-actions.png' })
  const companyId = new URL(page.url()).pathname.split('/').at(-1)!
  await page.goto(`/contacts/people/new?company=${companyId}`)
  await page.getByRole('button', { name: 'Réduire la navigation', exact: true }).click()
  await page.getByLabel('Nom', { exact: true }).fill('Brouillon extérieur')
  let release: (() => void) | undefined
  const gate = new Promise<void>((resolve) => { release = resolve })
  await page.route('**/api/collections/contacts_addresses/records*', async (route) => { await gate; await route.continue() })
  await page.getByRole('button', { name: 'Ouvrir la fiche : Société', exact: true }).click()
  const company = page.getByRole('dialog', { name: 'Fiche société', exact: true })
  const loading = company.getByRole('status', { name: 'Chargement de la fiche…' })
  await expect(loading).toHaveText('')
  await expect(company.getByText('Chargement de la fiche…', { exact: true })).toHaveCount(0)
  const ring = loading.locator('.h-loading-ring')
  expect(await ring.evaluate((element) => element.getAnimations().some((animation) => animation.effect?.getTiming().delay === 200))).toBe(true)
  await expect(ring).toHaveCSS('opacity', '1')
  await page.screenshot({ path: '/private/tmp/horizon-record-popup-loading.png' })
  release?.()
  await expect(loading).toHaveCount(0)
  await page.unroute('**/api/collections/contacts_addresses/records*')
  await expectWorkspaceCentered(page, company)
  await page.screenshot({ path: '/private/tmp/horizon-record-popup-collapsed.png' })
  await company.getByRole('tab', { name: /^Contacts(?: \d+)?$/ }).click()
  await company.getByRole('link', { name: 'Ajouter un contact', exact: true }).click()
  const person = page.getByRole('dialog', { name: 'Créer un contact', exact: true })
  await person.getByLabel('Nom', { exact: true }).fill('Contact créé imbriqué')
  await person.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(person).not.toBeVisible()
  await expect(company.getByRole('link', { name: 'Contact créé imbriqué', exact: true })).toBeVisible()
  await company.getByRole('button', { name: 'Fermer', exact: true }).click()
  await expect(page.getByLabel('Nom', { exact: true })).toHaveValue('Brouillon extérieur')
  await expect(page).toHaveURL(`/contacts/people/new?company=${companyId}`)
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/people\/(?!new)/)
  const contactUrl = page.url()
  await page.getByRole('button', { name: 'Menu utilisateur', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Se déconnecter', exact: true }).click()
  await login(page, 'crm-reader@local.invalid')
  await page.goto(contactUrl)
  await page.getByRole('button', { name: 'Ouvrir la fiche : Société', exact: true }).click()
  await expect(company.getByLabel('Nom usuel', { exact: true })).toBeDisabled()
  await expect(company.getByRole('button', { name: 'Enregistrer', exact: true })).toHaveCount(0)
  await page.screenshot({ path: '/private/tmp/horizon-record-popup-readonly.png' })
  await company.getByRole('button', { name: 'Fermer', exact: true }).click()
  const inspect = page.getByRole('button', { name: 'Ouvrir la fiche : Société', exact: true })
  await expect(inspect).toBeFocused()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Shift+Tab')
  await expect(inspect).toBeFocused()
  await expect(inspect).toHaveCSS('outline-style', 'none')
  const focusedGroup = page.locator('.h-combobox-with-actions').filter({ has: inspect })
  expect(await focusedGroup.evaluate((element) => element.matches(':has(:focus-visible)'))).toBe(true)
  await expect(focusedGroup).toHaveCSS('border-color', 'rgb(113, 137, 171)')
  await page.screenshot({ path: '/private/tmp/horizon-record-picker-focus.png' })
})

test('sauvegarde de fiche : onglet conservé à la création et après modification', async ({ page }) => {
  await login(page)
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel', { exact: true }).fill('Client onglet conservé')
  const notes = page.getByRole('tab', { name: 'Notes', exact: true })
  await notes.click()
  await page.getByRole('textbox', { name: 'Notes', exact: true }).fill('Première note')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/contacts\/companies\/(?!new)/)
  await expect(notes).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('textbox', { name: 'Notes', exact: true })).toHaveValue('Première note')
  const companyId = new URL(page.url()).pathname.split('/').at(-1)!
  await page.getByRole('textbox', { name: 'Notes', exact: true }).fill('Note modifiée')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await expect(notes).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('textbox', { name: 'Notes', exact: true })).toHaveValue('Note modifiée')
  await page.goto(`/crm/opportunities/new?company=${companyId}`)
  await page.getByLabel('Titre', { exact: true }).fill('Affaire onglet conservé')
  const descriptionTab = page.getByRole('tab', { name: 'Description', exact: true })
  await descriptionTab.click()
  const description = page.getByRole('textbox', { name: 'Contexte et besoins', exact: true })
  await description.fill('Première description')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/crm\/opportunities\/(?!new)/)
  await expect(descriptionTab).toHaveAttribute('aria-selected', 'true')
  await description.fill('Description modifiée')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await expect(descriptionTab).toHaveAttribute('aria-selected', 'true')
  await expect(description).toHaveText('Description modifiée')
})
