import { test, expect, type Page } from '@playwright/test'
async function login(page: Page, email = 'erp-admin@local.invalid') {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail', { exact: true }).fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill('Local-Horizon-test-only-2026!')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
}
test('Devis : opportunité obligatoire, codes successifs, smart button et revenu après annulation', async ({ page }) => {
  await login(page)
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel', { exact: true }).fill('Client devis Horizon')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/contacts\/companies\/(?!new)/)
  await page.goto('/crm/opportunities/new')
  await page.getByLabel('Titre', { exact: true }).fill('Affaire devis Horizon')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client devis Horizon', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/crm\/opportunities\/(?!new)/)
  const opportunityUrl = page.url(), id = new URL(opportunityUrl).pathname.split('/').at(-1)!
  await expect(page.locator('#crm-number')).toHaveValue(/^\d+$/)
  const opportunityNumber = await page.locator('#crm-number').inputValue()
  expect(opportunityNumber).toMatch(/^\d+$/)
  await expect(page.getByRole('navigation', { name: 'Documents de l’opportunité' }).getByRole('link', { name: /Devis.*0/ })).toBeVisible()
  await page.getByRole('link', { name: 'Nouveau devis', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Opportunité du devis', exact: true })).toContainText('Affaire devis Horizon')
  await page.getByLabel('Titre du devis', { exact: true }).fill('Première proposition')
  await page.getByRole('button', { name: 'Ajouter une ligne', exact: true }).click()
  await page.getByLabel('Description ligne 1', { exact: true }).fill('Installation')
  await page.getByLabel('Quantité ligne 1', { exact: true }).fill('2')
  await page.getByLabel('Prix unitaire ligne 1', { exact: true }).fill('100.25')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/sales\/quotes\/(?!new)/)
  await expect(page.getByRole('heading', { name: `Devis ${opportunityNumber}-1`, exact: true })).toBeVisible()
  await expect(page.locator('.quote-total-ht')).toContainText('200,50 €')
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  const firstQuoteUrl = page.url()
  await page.screenshot({ path: '/private/tmp/horizon-sales-quote.png', fullPage: true })
  await page.goto(opportunityUrl)
  await expect(page.locator('.crm-sales-revenue')).toContainText('200,50 €')
  await page.getByRole('navigation', { name: 'Documents de l’opportunité' }).getByRole('link', { name: /Devis.*1/ }).click()
  await expect(page).toHaveURL(firstQuoteUrl)
  await expect(page.getByLabel('Titre du devis', { exact: true })).toHaveValue('Première proposition')
  await page.goto(opportunityUrl)
  await page.getByRole('link', { name: 'Nouveau devis', exact: true }).click()
  await page.getByLabel('Titre du devis', { exact: true }).fill('Variante abandonnée')
  await page.getByRole('button', { name: 'Ajouter une ligne', exact: true }).click()
  await page.getByLabel('Description ligne 1', { exact: true }).fill('Variante')
  await page.getByLabel('Prix unitaire ligne 1', { exact: true }).fill('50')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: `Devis ${opportunityNumber}-2`, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Actions de la fiche', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Annuler le devis', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Annuler le devis', exact: true })
  await dialog.getByLabel('Motif d’annulation', { exact: true }).fill('Variante non retenue')
  await dialog.getByRole('button', { name: 'Confirmer l’annulation', exact: true }).click()
  await expect(page.locator('.contact-page-heading')).toContainText('Annulé')
  await page.goto(opportunityUrl)
  await expect(page.locator('.crm-sales-revenue')).toContainText('200,50 €')
  await page.getByRole('navigation', { name: 'Documents de l’opportunité' }).getByRole('link', { name: /Devis.*2/ }).click()
  await expect(page).toHaveURL(new RegExp(`opportunity=${id}`))
  await expect(page.getByRole('row').filter({ hasText: 'Première proposition' })).toBeVisible()
  await expect(page.getByRole('row').filter({ hasText: 'Variante abandonnée' })).toBeVisible()
  await page.goto(opportunityUrl)
  await page.screenshot({ path: '/private/tmp/horizon-opportunity-sales-links.png' })
  await page.goto('/sales/quotes')
  await expect(page.getByRole('searchbox', { name: 'Rechercher un devis', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Nouveau devis', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Opportunité du devis', exact: true })).toContainText('Choisir…')
  await page.getByLabel('Titre du devis', { exact: true }).fill('Troisième proposition')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Choisissez une opportunité.')
  await page.getByRole('combobox', { name: 'Opportunité du devis', exact: true }).click()
  await page.getByRole('option', { name: /Affaire devis Horizon/ }).click()
  await page.getByLabel('Titre du devis', { exact: true }).fill('Troisième proposition')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('heading', { name: `Devis ${opportunityNumber}-3`, exact: true })).toBeVisible()
  const thirdQuoteUrl = page.url()
  const openCopy = async () => {
    await page.getByRole('button', { name: 'Actions de la fiche', exact: true }).click()
    await page.getByRole('menuitem', { name: 'Copier un devis', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Copier un devis', exact: true })
    await dialog.getByRole('textbox', { name: 'Rechercher un devis à copier' }).fill(`${opportunityNumber}-1`)
    await dialog.getByRole('button', { name: `Copier le devis ${opportunityNumber}-1`, exact: true }).click()
    await expect(dialog.getByRole('button', { name: 'Copier le devis', exact: true })).toBeDisabled()
    await dialog.getByRole('textbox', { name: 'Confirmation de copie' }).fill('COPIER')
    await page.screenshot({ path: '/private/tmp/horizon-copy-quote.png' })
    await dialog.getByRole('button', { name: 'Copier le devis', exact: true }).click()
    await expect(dialog).toHaveCount(0)
  }
  await openCopy()
  await expect(page.getByLabel('Titre du devis', { exact: true })).toHaveValue('Première proposition')
  await expect(page.getByLabel('Description ligne 1', { exact: true })).toHaveValue('Installation')
  await expect(page.getByLabel('Prix unitaire ligne 1', { exact: true })).toHaveValue(/100,25\s*€/)
  await expect(page).toHaveURL(thirdQuoteUrl)
  await page.getByRole('button', { name: 'Annuler les modifications', exact: true }).click()
  await expect(page.getByLabel('Titre du devis', { exact: true })).toHaveValue('Troisième proposition')
  await expect(page.getByLabel('Description ligne 1', { exact: true })).toHaveCount(0)
  await openCopy()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('heading', { name: `Devis ${opportunityNumber}-3`, exact: true })).toBeVisible()
  await expect(page.getByLabel('Description ligne 1', { exact: true })).toHaveValue('Installation')
  await page.goto(`/sales/quotes/new?opportunity=${id}`)
  await page.getByRole('button', { name: 'Actions de la fiche', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: 'Copier un devis', exact: true })).toBeVisible()
  for (const action of ['Annuler le devis', 'Archiver', 'Supprimer']) await expect(page.getByRole('menuitem', { name: action, exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await openCopy()
  await expect(page.getByLabel('Description ligne 1', { exact: true })).toHaveValue('Installation')
  await expect(page.getByRole('combobox', { name: 'Opportunité du devis', exact: true })).toContainText('Affaire devis Horizon')
  await page.getByRole('button', { name: 'Annuler les modifications', exact: true }).click()
  await page.goto('/sales/quotes/new')
  await page.getByLabel('Titre du devis', { exact: true }).fill('Devis conservé pendant la création')
  await page.getByRole('combobox', { name: 'Opportunité du devis', exact: true }).click()
  await page.getByRole('combobox', { name: 'Rechercher : Opportunité du devis', exact: true }).fill('Nouvelle affaire depuis le devis')
  await page.getByRole('button', { name: /Créer une opportunité/ }).click()
  const opportunityDialog = page.getByRole('dialog', { name: 'Nouvelle opportunité', exact: true })
  await expect(opportunityDialog.getByLabel('Titre', { exact: true })).toHaveValue('Nouvelle affaire depuis le devis')
  await opportunityDialog.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client devis Horizon', exact: true }).click()
  await opportunityDialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(opportunityDialog).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Opportunité du devis', exact: true })).toContainText('Nouvelle affaire depuis le devis')
  await expect(page.getByLabel('Titre du devis', { exact: true })).toHaveValue('Devis conservé pendant la création')
  await expect(page).toHaveURL(/sales\/quotes\/new$/)
  await page.goto(thirdQuoteUrl)
  await expect(page.getByRole('heading', { name: `Devis ${opportunityNumber}-3`, exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-sales-quote-mobile.png', fullPage: true })
  await page.goto(`/sales/quotes?opportunity=${id}`)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  const pagination = page.getByRole('navigation', { name: 'Pagination des devis' })
  const count = await pagination.locator('.record-navigator-count').boundingBox()
  const previous = await pagination.getByRole('button', { name: 'Page précédente', exact: true }).boundingBox()
  expect(count!.x + count!.width).toBeLessThanOrEqual(previous!.x)
  const summary = page.getByRole('region', { name: 'Synthèse des devis' })
  await expect(summary.getByRole('link')).toHaveCount(4)
  await expect(summary.getByRole('link', { name: 'Filtrer les devis : Brouillon', exact: true }).locator('strong')).toHaveText('2')
  await expect(summary.getByRole('link', { name: 'Filtrer les devis : Devis', exact: true }).locator('strong')).toHaveText('0')
  for (const [label, status] of [['Brouillon', 'draft'], ['Devis', 'validated'], ['Envoyé', 'sent'], ['Commandé', 'accepted']] as const) {
    await summary.getByRole('link', { name: `Filtrer les devis : ${label}`, exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`status=${status}`))
    expect(new URL(page.url()).searchParams.get('opportunity')).toBe(id)
    await expect(summary.getByRole('link', { name: 'Filtrer les devis : Brouillon', exact: true }).locator('strong')).toHaveText('2')
  }
  await page.reload()
  await expect(summary.getByRole('link', { name: 'Filtrer les devis : Brouillon', exact: true }).locator('strong')).toHaveText('2')
  await page.screenshot({ path: '/private/tmp/horizon-sales-list-dark.png' })
})
test('Devis : droits sales requis et lien caché pour un lecteur CRM seul', async ({ page }) => {
  await login(page, 'crm-reader@local.invalid')
  await page.goto('/sales/quotes')
  await expect(page.getByText('Vous ne disposez pas de la permission de consulter les devis.', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Nouveau devis', exact: true })).toHaveCount(0)
})

test('Devis : sections, options, actions de lignes, popup opportunité et fil partagé', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await login(page)
  await page.goto('/settings/ventes')
  const settingsTableStyle = async () => page.locator('.settings-reference-table').evaluate((node) => {
    const container = getComputedStyle(node), header = getComputedStyle(node.querySelector('th')!)
    return { border: container.border, radius: container.borderRadius, header: header.backgroundColor, headerSize: header.fontSize }
  })
  const columnsStyle = await settingsTableStyle()
  for (const tab of ['Colonnes des devis', 'Valeurs par défaut', 'Conditions de vente']) {
    await page.getByRole('tab', { name: tab, exact: true }).click()
    const panel = page.getByRole('tabpanel')
    const saveButton = panel.getByRole('button', { name: 'Enregistrer', exact: true })
    await expect(saveButton).toBeDisabled()
    await expect(panel.locator('.h-section-heading-actions').getByRole('button', { name: 'Enregistrer', exact: true })).toBeVisible()
    const titleStyle = await panel.locator('.h-section-heading h2').evaluate((node) => {
      const style = getComputedStyle(node)
      return { size: style.fontSize, lineHeight: style.lineHeight, weight: style.fontWeight }
    })
    expect(titleStyle).toEqual({ size: '13px', lineHeight: '18px', weight: '600' })
    if (tab === 'Valeurs par défaut') {
      const fields = panel.locator('.contact-fields')
      const validity = fields.getByLabel('Validité des nouveaux devis (jours)', { exact: true })
      const taxRate = fields.getByLabel('TVA par défaut (%)', { exact: true })
      await expect(validity).toHaveValue('30')
      await expect(taxRate).toHaveValue('20')
      const first = (await validity.boundingBox())!, second = (await taxRate.boundingBox())!
      expect(first.y).toEqual(second.y)
      expect(first.width).toEqual(second.width)
      await page.screenshot({ path: '/private/tmp/horizon-settings-defaults.png' })
      await page.setViewportSize({ width: 390, height: 844 })
      expect((await taxRate.boundingBox())!.y).toBeGreaterThan((await validity.boundingBox())!.y)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await page.screenshot({ path: '/private/tmp/horizon-settings-defaults-mobile.png' })
      await page.setViewportSize({ width: 1600, height: 1000 })
    }
    if (tab !== 'Valeurs par défaut') {
      const saveBox = (await saveButton.boundingBox())!, tableBox = (await panel.getByRole('table').boundingBox())!
      expect(saveBox.y + saveBox.height).toBeLessThan(tableBox.y)
      expect(saveBox.x + saveBox.width).toBeGreaterThan(tableBox.x + tableBox.width - 2)
    }
  }
  expect(await settingsTableStyle()).toEqual(columnsStyle)
  await page.getByRole('button', { name: 'Ajouter des conditions', exact: true }).click()
  const termsDialog = page.getByRole('dialog', { name: 'Conditions générales de vente', exact: true })
  await termsDialog.getByLabel('Intitulé', { exact: true }).fill('Conditions de test')
  await termsDialog.getByLabel('Contenu', { exact: true }).fill('Livraison sur site. Conditions approuvées pour la recette.')
  const termsGeometry = await termsDialog.evaluate((node) => {
    const inputs = [...node.querySelectorAll('input[type="text"], textarea')].map((input) => input.getBoundingClientRect())
    const footer = node.querySelector('.dialog-form-footer')!.getBoundingClientRect()
    return { aligned: Math.abs(inputs[0]!.x - inputs[1]!.x) < 1 && Math.abs(inputs[0]!.width - inputs[1]!.width) < 1, separated: footer.y > inputs[1]!.bottom }
  })
  expect(termsGeometry).toEqual({ aligned: true, separated: true })
  await page.screenshot({ path: '/private/tmp/horizon-settings-cgv-dialog.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  const mobileTerms = await termsDialog.boundingBox()
  expect(mobileTerms!.x).toBeGreaterThanOrEqual(0)
  expect(mobileTerms!.x + mobileTerms!.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: '/private/tmp/horizon-settings-cgv-dialog-mobile.png' })
  await page.setViewportSize({ width: 1600, height: 1000 })

  await termsDialog.getByRole('button', { name: 'Appliquer', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await expect(page.getByRole('tab', { name: 'Conditions de vente', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.screenshot({ path: '/private/tmp/horizon-settings-cgv-table.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-settings-cgv-table-mobile.png' })
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel', { exact: true }).fill('Client grille devis')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/contacts\/companies\/(?!new)/)
  await page.goto('/crm/opportunities/new')
  await page.getByLabel('Titre', { exact: true }).fill('Affaire grille devis')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client grille devis', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/crm\/opportunities\/(?!new)/)
  await page.getByRole('link', { name: 'Nouveau devis', exact: true }).click()
  await page.getByLabel('Titre du devis', { exact: true }).fill('Devis structuré')
  const date = await page.getByLabel('Date du devis', { exact: true }).inputValue()
  const validity = new Date(`${date}T12:00:00Z`); validity.setUTCDate(validity.getUTCDate() + 30)
  await expect(page.getByLabel('Valable jusqu’au', { exact: true })).toHaveValue(validity.toISOString().slice(0, 10))
  await page.getByRole('button', { name: 'Ouvrir la fiche : Opportunité du devis', exact: true }).click()
  const popup = page.getByRole('dialog', { name: 'Fiche opportunité', exact: true })
  await popup.getByLabel('Titre', { exact: true }).fill('Affaire grille corrigée')
  await popup.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(popup).not.toBeVisible()
  await expect(page.getByLabel('Titre du devis', { exact: true })).toHaveValue('Devis structuré')
  await expect(page.getByRole('combobox', { name: 'Opportunité du devis', exact: true })).toContainText('Affaire grille corrigée')
  await page.getByRole('button', { name: 'Titre niveau 1', exact: true }).click()
  await expect(page.getByLabel('Description ligne 1', { exact: true })).toBeFocused()
  await page.getByLabel('Description ligne 1', { exact: true }).fill('Vidéo')
  await page.getByRole('button', { name: 'Ajouter une ligne', exact: true }).click()
  await expect(page.getByLabel('Description ligne 2', { exact: true })).toBeFocused()
  await page.getByLabel('Description ligne 2', { exact: true }).fill('Caméra de production professionnelle avec installation, accessoires et mise en service détaillée sur plusieurs lignes pour garder toute la description lisible.')
  await page.getByRole('combobox', { name: 'Unité ligne 2', exact: true }).click()
  await page.getByRole('option', { name: 'h · Heure', exact: true }).click()
  await page.getByLabel('Marque ligne 2', { exact: true }).fill('Sony')
  await page.getByLabel('Référence ligne 2', { exact: true }).fill('CAM-001')
  await page.getByLabel('Quantité ligne 2', { exact: true }).fill('2')
  await page.getByLabel('Coût ligne 2', { exact: true }).fill('60')
  await page.getByLabel('Prix unitaire ligne 2', { exact: true }).fill('100')
  await page.getByLabel('Remise ligne 2', { exact: true }).fill('10')
  await page.getByRole('button', { name: 'Titre niveau 2', exact: true }).click()
  await expect(page.getByLabel('Description ligne 3', { exact: true })).toBeFocused()
  await page.getByLabel('Description ligne 3', { exact: true }).fill('Accessoires')
  await page.getByRole('button', { name: 'Ajouter une ligne', exact: true }).click()
  await page.getByLabel('Description ligne 4', { exact: true }).fill('Accessoire optionnel')
  await page.getByLabel('Prix unitaire ligne 4', { exact: true }).fill('50')
  await page.getByRole('checkbox', { name: 'Option ligne 4', exact: true }).check()
  await page.getByRole('button', { name: 'Afficher le total de la section 1', exact: true }).click()
  await page.getByRole('button', { name: 'Afficher le total de la section 3', exact: true }).click()
  await page.getByRole('button', { name: 'Note', exact: true }).click()
  await expect(page.getByLabel('Description ligne 5', { exact: true })).toBeFocused()
  await page.getByLabel('Description ligne 5', { exact: true }).fill('Installation comprise')
  await page.getByRole('button', { name: 'Dupliquer ligne 2', exact: true }).click()
  expect(await page.evaluate(() => document.activeElement?.getAttribute('aria-label'))).not.toMatch(/^Marque ligne/)
  await expect(page.getByLabel('Marque ligne 3', { exact: true })).toHaveValue('Sony')
  await page.getByRole('checkbox', { name: 'Option ligne 3', exact: true }).check()
  const handle = page.getByRole('button', { name: 'Déplacer ligne 3', exact: true })
  await handle.scrollIntoViewIfNeeded()
  const from = (await handle.boundingBox())!, to = (await page.getByRole('button', { name: 'Déplacer ligne 4', exact: true }).boundingBox())!
  await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2)
  await page.mouse.down()
  await page.mouse.move(from.x + from.width / 2, to.y + to.height / 2 + 5, { steps: 15 })
  await page.mouse.up()
  await expect(page.getByLabel('Description ligne 3', { exact: true })).toHaveCount(1)
  await expect(page.getByLabel('Description ligne 3', { exact: true })).toHaveValue('Accessoires')
  await expect(page.locator('.quote-total-ht')).toContainText('180,00 €')
  await expect(page.locator('.sales-quote-options-total')).toContainText('230,00 €')
  await page.getByRole('button', { name: 'Déplacer ligne 4', exact: true }).focus()
  await page.keyboard.press('Space')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Escape')
  await expect(page.getByLabel('Description ligne 3', { exact: true })).toHaveValue('Accessoires')
  await page.getByRole('button', { name: 'Supprimer ligne 6', exact: true }).click()
  const confirmation = page.getByRole('alertdialog', { name: 'Confirmer la suppression', exact: true })
  await expect(page.getByLabel('Description ligne 6', { exact: true })).toBeVisible()
  await confirmation.getByRole('button', { name: 'Annuler', exact: true }).click()
  await expect(page.getByLabel('Description ligne 6', { exact: true })).toHaveValue('Installation comprise')
  await page.getByRole('button', { name: 'Supprimer ligne 6', exact: true }).click()
  await expect(confirmation.getByRole('textbox')).toHaveCount(0)
  await confirmation.getByRole('button', { name: 'Supprimer', exact: true }).click()
  await expect(page.getByLabel('Description ligne 6', { exact: true })).toHaveCount(0)
  await expect(page).toHaveURL(/sales\/quotes\/new/)
  await page.getByRole('combobox', { name: 'Conditions générales de vente', exact: true }).click()
  await page.getByRole('option', { name: 'Conditions de test', exact: true }).click()
  await expect(page.locator('.quote-terms-content')).toContainText('Livraison sur site.')
  const notes = page.getByLabel('Notes du devis', { exact: true })
  await expect(notes).toBeHidden()
  await page.getByRole('button', { name: 'Afficher les notes', exact: true }).click()
  await notes.fill('Prévoir la livraison sur site')
  await page.getByRole('button', { name: 'Masquer les notes', exact: true }).click()
  await expect(notes).toBeHidden()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/sales\/quotes\/(?!new)/)
  await expect(page.getByRole('link', { name: 'Retour à la liste', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.quote-terms-content')).toContainText('Conditions approuvées pour la recette.')
  await expect(page.getByRole('combobox', { name: 'Unité ligne 2', exact: true })).toContainText('h')
  await expect(page.locator('.sales-quote-options-total')).toContainText('230,00 €')
  await expect(page.getByLabel('Marque ligne 2', { exact: true })).toHaveValue('Sony')
  await expect(page.getByLabel('Description ligne 3', { exact: true })).toHaveValue('Accessoires')
  await expect(notes).toBeHidden()
  await page.getByRole('checkbox', { name: 'Option ligne 3', exact: true }).check()
  await expect(page.getByRole('checkbox', { name: 'Option ligne 1', exact: true })).not.toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Option ligne 2', exact: true })).not.toBeChecked()
  await expect(page.locator('.quote-row--section .quote-section-amount')).not.toContainText('Options')
  await expect(page.locator('.quote-row--subsection .quote-section-amount')).toHaveText(/\(230,00\s*€\)/)
  await expect(page.locator('.quote-row--subsection .quote-section-amount small')).toHaveCount(0)
  expect((await page.locator('.quote-row--subsection').boundingBox())!.height).toBeLessThanOrEqual(34)
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('checkbox', { name: 'Option ligne 1', exact: true })).not.toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Option ligne 3', exact: true })).toBeChecked()
  await page.getByRole('checkbox', { name: 'Option ligne 3', exact: true }).uncheck()
  await page.getByRole('checkbox', { name: 'Option ligne 4', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Option ligne 5', exact: true }).check()
  await page.getByRole('button', { name: 'Afficher les notes', exact: true }).click()
  await expect(notes).toHaveValue('Prévoir la livraison sur site')
  await page.getByRole('button', { name: 'Masquer les notes', exact: true }).click()
  for (const kind of ['section', 'subsection']) {
    const cells = page.locator(`.quote-row--${kind}`).first().locator('td')
    await expect(cells).toHaveCount(14)
    await expect(cells.nth(5)).toHaveCSS('border-right-width', '1px')
  }
  const headers = await page.locator('.quote-edit-table th > span').allTextContents()
  expect(headers.slice(6, 9)).toEqual(['Coût€', 'Marge%', 'PUV€'])
  await expect(page.getByRole('columnheader', { name: 'Unité', exact: true })).toContainText('u.')
  await expect(page.locator('.quote-edit-table .h-amount-currency')).toHaveCount(0)
  await expect(page.getByLabel('Coût ligne 2', { exact: true })).toHaveCSS('text-align', 'right')
  await expect(page.getByLabel('Prix unitaire ligne 2', { exact: true })).toHaveCSS('text-align', 'right')
  await expect(page.locator('.quote-row--item .quote-line-total').first()).toHaveCSS('text-align', 'right')
  await expect(page.getByRole('columnheader', { name: 'Coût', exact: true })).toHaveCSS('text-align', 'center')
  expect(await page.getByRole('button', { name: 'Masquer le total de la section 1', exact: true }).evaluate((node) => node.closest('td')?.classList.contains('quote-line-total'))).toBe(true)
  expect(await page.locator('.quote-summary strong').evaluateAll((nodes) => nodes.every((node) => getComputedStyle(node).fontSize === '13px'))).toBe(true)
  const titlePositions = await page.locator('.quote-row--section .quote-line-description, .quote-row--subsection .quote-line-description').evaluateAll((nodes) => nodes.map((node) => node.getBoundingClientRect().x))
  expect(Math.abs(titlePositions[0]! - titlePositions[1]!)).toBeLessThan(1)
  await page.getByRole('button', { name: 'Replier toutes les sections', exact: true }).click()
  await expect(page.getByLabel('Description ligne 2', { exact: true })).toHaveCount(0)
  await expect(page.locator('.quote-total-ht')).toContainText('180,00 €')
  await page.getByRole('button', { name: 'Déplier toutes les sections', exact: true }).click()
  await expect(page.getByLabel('Description ligne 2', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Dupliquer ligne 1', exact: true }).click()
  const duplication = page.getByRole('dialog', { name: 'Dupliquer le titre', exact: true })
  await page.screenshot({ path: '/private/tmp/horizon-quote-duplicate-dialog.png' })
  await duplication.getByRole('button', { name: 'Fermer', exact: true }).click()
  await expect(page.locator('.quote-edit-table tbody tr')).toHaveCount(5)
  await page.getByRole('button', { name: 'Dupliquer ligne 1', exact: true }).click()
  await duplication.getByRole('button', { name: 'Titre et contenu', exact: true }).click()
  await expect(page.locator('.quote-edit-table tbody tr')).toHaveCount(10)
  await expect(page.getByLabel('Description ligne 6', { exact: true })).toHaveValue('Vidéo')
  await expect(page.getByLabel('Marque ligne 7', { exact: true })).toHaveValue('Sony')
  await expect(page.locator('.quote-total-ht')).toContainText('360,00 €')
  await page.getByRole('button', { name: 'Annuler les modifications', exact: true }).click()
  await expect(page.locator('.quote-edit-table tbody tr')).toHaveCount(5)
  await expect(page.locator('.quote-total-ht')).toContainText('180,00 €')
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Dupliquer ligne 1', exact: true }).click()
  await duplication.getByRole('button', { name: 'Titre seul', exact: true }).click()
  await expect(page.locator('.quote-edit-table tbody tr')).toHaveCount(6)
  await expect(page.getByLabel('Description ligne 2', { exact: true })).toHaveValue('Vidéo')
  await page.getByRole('button', { name: 'Annuler les modifications', exact: true }).click()
  await page.getByLabel('Prix unitaire ligne 2', { exact: true }).fill('999')
  await page.getByRole('button', { name: 'Annuler les modifications', exact: true }).click()
  await expect(page.getByLabel('Prix unitaire ligne 2', { exact: true })).toHaveValue(/100,00\s*€/)
  await expect(page.getByRole('columnheader', { name: 'Description', exact: true })).toHaveCSS('text-align', 'left')
  await expect(page.locator('.quote-profitability strong').first()).toHaveCSS('font-weight', '400')
  const noteAlignment = await page.locator('.quote-notes-panel').evaluate((node) => {
    const title = node.querySelector('h2')!.getBoundingClientRect(), button = node.querySelector('button')!.getBoundingClientRect()
    return Math.abs(title.y + title.height / 2 - button.y - button.height / 2)
  })
  expect(noteAlignment).toBeLessThan(1)
  const textarea = page.getByLabel('Description ligne 2', { exact: true })
  await expect(textarea).toHaveCSS('white-space', 'pre-wrap')
  expect(await textarea.evaluate((node) => node.getBoundingClientRect().height)).toBeGreaterThan(30)
  const feed = page.getByRole('region', { name: 'Fil d’activité', exact: true })
  await expect(feed).toContainText('Total HT')
  await feed.getByRole('textbox').fill('À relire avec le client')
  await feed.getByRole('button', { name: 'Publier', exact: true }).click()
  await expect(feed.getByText('À relire avec le client', { exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: '/private/tmp/horizon-quote-structured.png', fullPage: true })
  await page.setViewportSize({ width: 1920, height: 1080 })
  const table = (await page.locator('.quote-edit-table').boundingBox())!, container = (await page.locator('.sales-quote-lines .data-table-scroll').boundingBox())!
  expect(Math.abs(table.width - container.width)).toBeLessThan(3)
  await expect.poll(() => page.evaluate(() => {
    const quantity = document.querySelector('[aria-label="Quantité ligne 2"]')!.getBoundingClientRect(), duplicate = document.querySelector('[aria-label="Dupliquer ligne 2"]')!.getBoundingClientRect()
    return Math.abs(quantity.y + quantity.height / 2 - duplicate.y - duplicate.height / 2)
  })).toBeLessThan(2)
  await expect(page.getByRole('button', { name: 'Dupliquer ligne 2', exact: true })).toHaveAttribute('title', 'Dupliquer la ligne')
  await expect(page.getByRole('columnheader', { name: 'Option', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.querySelector('.quote-line-additions')!.getBoundingClientRect().top - document.querySelector('.quote-edit-table')!.getBoundingClientRect().bottom)).toBeGreaterThanOrEqual(0)
  await page.screenshot({ path: '/private/tmp/horizon-quote-grid-wide.png', fullPage: true })
  const header = page.getByRole('button', { name: 'Redimensionner Marque', exact: true })
  const oldWidth = await header.locator('..').evaluate((node) => node.getBoundingClientRect().width)
  const resize = (await header.boundingBox())!
  await page.mouse.move(resize.x + resize.width / 2, resize.y + resize.height / 2)
  await page.mouse.down()
  await page.mouse.move(resize.x + resize.width / 2 + 35, resize.y + resize.height / 2, { steps: 8 })
  await page.mouse.up()
  expect(await header.locator('..').evaluate((node) => node.getBoundingClientRect().width)).toBeGreaterThan(oldWidth + 20)
  await page.getByLabel('Coût ligne 2', { exact: true }).fill('100')
  await page.getByLabel('Marge ligne 2', { exact: true }).fill('25')
  await expect(page.getByLabel('Prix unitaire ligne 2', { exact: true })).toHaveValue(/125,00\s*€/)
  await page.getByLabel('Remise ligne 2', { exact: true }).fill('0')
  await expect(page.locator('.quote-total-ht')).toContainText('250,00 €')
  await expect(page.locator('.quote-total-tax')).toContainText('50,00 €')
  await expect(page.locator('.quote-total-ttc')).toContainText('300,00 €')
  await page.getByLabel('Coût ligne 2', { exact: true }).fill('120')
  await expect(page.getByLabel('Prix unitaire ligne 2', { exact: true })).toHaveValue(/150,00\s*€/)
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByLabel('Prix unitaire ligne 2', { exact: true })).toHaveValue(/150,00\s*€/)
  expect(await page.getByRole('button', { name: 'Redimensionner Marque', exact: true }).locator('..').evaluate((node) => node.getBoundingClientRect().width)).toBeGreaterThan(oldWidth + 20)
  await expect(page.locator('.quote-cost-total')).toContainText('240,00 €')
  await page.getByRole('checkbox', { name: 'Option ligne 1', exact: true }).check()
  await expect(page.locator('.quote-total-ht')).toContainText('0,00 €')
  await expect(page.locator('.sales-quote-options-total')).toContainText('530,00 €')
  await expect(page.getByRole('checkbox', { name: 'Option ligne 2', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('checkbox', { name: 'Option ligne 1', exact: true })).toBeChecked()
  await expect(page.locator('.quote-total-tax')).toContainText('0,00 €')
  await page.getByRole('checkbox', { name: 'Option ligne 1', exact: true }).uncheck()
  await expect(page.locator('.quote-total-ht')).toContainText('530,00 €')
  await page.getByRole('checkbox', { name: 'Option ligne 4', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Option ligne 5', exact: true }).check()
  await expect(page.locator('.quote-total-ht')).toContainText('300,00 €')
  await expect(page.getByRole('spinbutton', { name: 'Remise globale (%)', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Ajouter une remise globale', exact: true }).click()
  const assertDiscountBelowHT = async () => {
    const ht = (await page.locator('.quote-total-ht').boundingBox())!, row = (await page.locator('.quote-footer-discount').boundingBox())!
    expect(row.y).toBeGreaterThanOrEqual(ht.y + ht.height - 1)
    expect(await page.locator('.quote-total-ht').evaluate((node) => node.nextElementSibling?.classList.contains('quote-footer-discount'))).toBe(true)
  }
  await assertDiscountBelowHT()
  await page.getByRole('spinbutton', { name: 'Remise globale (%)', exact: true }).fill('10')
  await expect(page.locator('.quote-total-ht')).toContainText('270,00 €')
  await expect(page.locator('.quote-total-tax')).toContainText('54,00 €')
  await expect(page.locator('.quote-total-ttc')).toContainText('324,00 €')
  await expect(page.locator('.quote-margin-total')).toContainText('30,00 €')
  await expect(page.locator('.quote-margin-percent')).toContainText('12,50 %')
  await expect(page.locator('.quote-cost-total')).toContainText('240,00 €')
  await expect(page.getByLabel('Remise globale (montant)', { exact: true })).toHaveValue(/30,00\s*€/)
  await page.getByLabel('Remise globale (montant)', { exact: true }).fill('15,00 €')
  await expect(page.locator('.quote-total-ht')).toContainText('285,00 €')
  await expect(page.getByRole('spinbutton', { name: 'Remise globale (%)', exact: true })).toHaveValue('5')
  await page.getByLabel('Remise globale (montant)', { exact: true }).fill('14,33 €')
  await expect(page.getByRole('spinbutton', { name: 'Remise globale (%)', exact: true })).toHaveValue('4.7767')
  expect(await page.getByRole('spinbutton', { name: 'Remise globale (%)', exact: true }).evaluate((node) => (node as HTMLInputElement).checkValidity())).toBe(true)
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByLabel('Remise globale (montant)', { exact: true })).toHaveValue(/14,33\s*€/)
  await expect(page.locator('.quote-total-ht')).toContainText('285,67 €')
  await page.getByRole('spinbutton', { name: 'Remise globale (%)', exact: true }).fill('10')
  await expect(page.locator('.sales-quote-options-total')).toContainText('230,00 €')
  await page.getByRole('button', { name: 'Retirer la remise globale', exact: true }).click()
  await expect(page.getByLabel('Remise globale (montant)', { exact: true })).toHaveCount(0)
  await expect(page.locator('.quote-total-ht')).toContainText('300,00 €')
  await page.getByRole('button', { name: 'Ajouter une remise globale', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Remise globale (%)', exact: true }).fill('10')
  await expect(page.locator('.sales-quote-options-total')).toContainText('230,00 €')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('spinbutton', { name: 'Remise globale (%)', exact: true })).toHaveValue('10')
  await expect(page.locator('.quote-margin-total')).toContainText('30,00 €')
  const footerInputs = await page.locator('.quote-discount-inputs input').evaluateAll((nodes) => nodes.map((node) => node.getBoundingClientRect().toJSON()))
  expect(footerInputs[0]!.y).toEqual(footerInputs[1]!.y)
  expect(footerInputs[0]!.height).toEqual(footerInputs[1]!.height)
  await page.evaluate(() => window.scrollTo(0, document.querySelector('.quote-summary')!.getBoundingClientRect().top + window.scrollY - 300))
  await page.screenshot({ path: '/private/tmp/horizon-quote-footer-discount.png' })
  await page.getByRole('spinbutton', { name: 'Remise globale (%)', exact: true }).fill('0')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Replier la section 1', exact: true }).click()
  await expect(page.getByLabel('Description ligne 2', { exact: true })).toHaveCount(0)
  await expect(page.locator('.quote-total-ht')).toContainText('300,00 €')
  await page.getByRole('button', { name: 'Déplier la section 1', exact: true }).click()
  await expect(page.getByLabel('Description ligne 2', { exact: true })).toHaveValue('Caméra de production professionnelle avec installation, accessoires et mise en service détaillée sur plusieurs lignes pour garder toute la description lisible.')
  await page.getByRole('button', { name: 'Titre niveau 3', exact: true }).click()
  await expect(page.getByLabel('Description ligne 6', { exact: true })).toBeFocused()
  await page.getByLabel('Description ligne 6', { exact: true }).fill('Installation détaillée')
  const level3Background = await page.getByRole('button', { name: 'Titre niveau 3', exact: true }).evaluate((node) => getComputedStyle(node).backgroundColor)
  await expect(page.locator('.quote-row--subsection3')).toHaveCSS('background-color', level3Background)
  expect(level3Background).not.toBe('rgb(255, 255, 255)')
  await expect(page.locator('.quote-row--subsection3 td')).toHaveCount(14)
  await expect(page.locator('.quote-row--subsection3 td').nth(5)).toHaveCSS('border-right-width', '1px')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await expect(page.getByLabel('Taux de TVA du devis', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Replier toutes les sections', exact: true }).click()
  await expect(page.getByLabel('Description ligne 2', { exact: true })).toHaveCount(0)
  for (let index = 7; index <= 24; index++) {
    await page.getByRole('button', { name: 'Note', exact: true }).click()
    await expect(page.getByLabel(`Description ligne ${index}`, { exact: true })).toBeFocused()
    await page.getByLabel(`Description ligne ${index}`, { exact: true }).fill(`Précision technique ${index}`)
  }
  await expect(page.getByLabel('Description ligne 2', { exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, document.querySelector('.quote-edit-table')!.getBoundingClientRect().top + window.scrollY + 180))
  await expect.poll(async () => (await page.getByRole('columnheader', { name: '#', exact: true }).boundingBox())!.y).toBeGreaterThanOrEqual(93)
  expect((await page.getByRole('columnheader', { name: '#', exact: true }).boundingBox())!.y).toBeLessThan(100)
  await page.screenshot({ path: '/private/tmp/horizon-quote-sticky-header.png' })
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  const quoteUrl = page.url()
  await page.goto('/settings/ventes')
  await page.getByLabel('Largeur Description', { exact: true }).fill('180')
  const settingsResponse = await Promise.all([page.waitForResponse((response) => response.url().endsWith('/horizon/sales/settings') && response.request().method() === 'POST'), page.getByRole('button', { name: 'Enregistrer', exact: true }).click()])
  expect(settingsResponse[0].status()).toBe(200)
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.goto(quoteUrl)
  expect(await page.locator('.quote-edit-table col').nth(1).evaluate((node) => node.getBoundingClientRect().width)).toBeGreaterThanOrEqual(120)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-quote-structured-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-quote-structured-dark.png', fullPage: true })
  await page.goto('/settings/ventes')
  await page.getByLabel('Largeur Description', { exact: true }).fill('280')
  const restored = await Promise.all([page.waitForResponse((response) => response.url().endsWith('/horizon/sales/settings') && response.request().method() === 'POST'), page.getByRole('button', { name: 'Enregistrer', exact: true }).click()])
  expect(restored[0].status()).toBe(200)
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('tab', { name: 'Valeurs par défaut', exact: true }).click()
  await expect(page.getByLabel('TVA par défaut (%)', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-settings-defaults-dark.png' })
  await page.getByRole('tab', { name: 'Conditions de vente', exact: true }).click()
  await expect(page.getByRole('columnheader', { name: 'Intitulé', exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-settings-cgv-table-dark.png' })
  await page.getByRole('button', { name: 'Configurer Conditions de test', exact: true }).click()
  await expect(termsDialog.getByLabel('Contenu', { exact: true })).toHaveValue('Livraison sur site. Conditions approuvées pour la recette.')
  await page.screenshot({ path: '/private/tmp/horizon-settings-cgv-dialog-dark.png' })
  await termsDialog.getByRole('button', { name: 'Fermer', exact: true }).click()
})


test('Devis : frise, commercial, confirmation et retours de statut', async ({ page }) => {
  await login(page)
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel', { exact: true }).fill('Client cycle devis')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/contacts\/companies\/(?!new)/)
  await page.goto('/crm/opportunities/new')
  await page.getByLabel('Titre', { exact: true }).fill('Affaire cycle devis')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client cycle devis', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/crm\/opportunities\/(?!new)/)
  await page.getByRole('link', { name: 'Nouveau devis', exact: true }).click()
  await page.getByLabel('Titre du devis', { exact: true }).fill('Proposition cycle')
  await expect(page.getByRole('combobox', { name: 'Commercial du devis' })).not.toContainText('Choisir')
  await page.getByRole('button', { name: 'Ajouter une ligne', exact: true }).click()
  await page.getByLabel('Description ligne 1', { exact: true }).fill('Installation')
  await page.getByLabel('Prix unitaire ligne 1', { exact: true }).fill('100')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/sales\/quotes\/(?!new)/)
  await expect(page.getByRole('button', { name: 'Confirmer', exact: true })).toHaveCount(0)
  const actionBounds = await Promise.all(['Finaliser Devis', 'Aperçu'].map((name) => page.getByRole('button', { name, exact: true }).boundingBox()))
  expect(actionBounds.every((box) => box?.height === 30)).toBe(true)
  const trailBounds = (await page.locator('.page-breadcrumb-trail').boundingBox())!
  expect(actionBounds[0]!.x - (trailBounds.x + trailBounds.width)).toBeGreaterThanOrEqual(36)
  expect(actionBounds[0]!.x - (trailBounds.x + trailBounds.width)).toBeLessThanOrEqual(44)
  const saveBounds = (await page.getByRole('button', { name: 'Enregistrer', exact: true }).boundingBox())!
  expect(saveBounds.x).toBeGreaterThan(actionBounds[1]!.x + actionBounds[1]!.width + 60)
  await expect(page.locator('.page-breadcrumb-controls').getByRole('button', { name: 'Enregistrer', exact: true })).toBeVisible()
  await expect(page.locator('.page-breadcrumb-controls').getByRole('button', { name: 'Actions de la fiche', exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-breadcrumb-actions.png' })
  await page.getByRole('button', { name: 'Finaliser Devis', exact: true }).click()
  await page.getByRole('dialog', { name: 'Finaliser le devis' }).getByRole('button', { name: 'Confirmer', exact: true }).click()
  await expect(page.locator('.quote-progress [aria-current="step"]')).toContainText('Devis')
  await expect(page.getByLabel('Description ligne 1', { exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Confirmer', exact: true })).toBeVisible()
  expect((await page.getByRole('button', { name: 'Confirmer', exact: true }).boundingBox())?.height).toBe(30)
  await page.getByRole('button', { name: 'Remettre en brouillon' }).click()
  await page.getByRole('dialog', { name: 'Remettre en brouillon' }).getByRole('button', { name: 'Confirmer', exact: true }).click()
  await expect(page.getByLabel('Description ligne 1', { exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Confirmer', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Finaliser Devis', exact: true }).click()
  await page.getByRole('dialog', { name: 'Finaliser le devis' }).getByRole('button', { name: 'Confirmer', exact: true }).click()
  await expect(page.locator('.quote-progress [aria-current="step"]')).toContainText('Devis')
  await page.getByRole('button', { name: 'Confirmer', exact: true }).click()
  const confirmation = page.getByRole('dialog', { name: 'Confirmer la commande client' })
  await expect(confirmation).toContainText('Attente Commande')
  await confirmation.getByRole('button', { name: 'Confirmer la commande', exact: true }).click()
  await expect(page.locator('.quote-customer-order')).toContainText('Attente Commande')
  await expect(page.locator('.quote-progress [aria-current="step"]')).toContainText('Commande client')
  await page.screenshot({ path: '/private/tmp/horizon-quote-lifecycle.png', fullPage: true })
  await page.getByRole('button', { name: 'Revenir en devis' }).click()
  await page.getByRole('dialog', { name: 'Revenir en devis' }).getByRole('button', { name: 'Confirmer', exact: true }).click()
  await expect(page.locator('.quote-progress [aria-current="step"]')).toContainText('Devis')
  await expect(page.locator('.quote-customer-order')).toHaveCount(0)
  await page.getByRole('button', { name: 'Confirmer', exact: true }).click()
  await confirmation.getByLabel('Numéro de commande client', { exact: true }).fill('PO-Horizon-42')
  await confirmation.getByLabel('Pièce de commande client', { exact: true }).setInputFiles({ name: 'commande.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZlVgAAAAASUVORK5CYII=', 'base64') })
  await confirmation.getByRole('button', { name: 'Confirmer la commande', exact: true }).click()
  await expect(page.locator('.quote-customer-order')).toContainText('PO-Horizon-42')
  await page.locator('.quote-customer-order').getByRole('button', { name: 'Aperçu commande.png' }).click()
  const preview = page.getByRole('dialog', { name: 'commande.png' })
  await expect(preview.getByRole('img', { name: 'commande.png' })).toBeVisible()
  await preview.getByRole('button', { name: 'Fermer', exact: true }).click()
  await expect(page.locator('.activity-attachments').getByRole('button', { name: 'Aperçu commande.png' })).toBeVisible()
  await page.getByRole('button', { name: 'Revenir en devis' }).click()
  await page.getByRole('dialog', { name: 'Revenir en devis' }).getByRole('button', { name: 'Confirmer', exact: true }).click()
  await expect(page.locator('.quote-progress [aria-current="step"]')).toContainText('Devis')
  await page.getByRole('button', { name: 'Actions de la fiche', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: 'Supprimer', exact: true })).toHaveCount(0)
  await page.getByRole('menuitem', { name: 'Annuler le devis', exact: true }).click()
  const cancel = page.getByRole('dialog', { name: 'Annuler le devis', exact: true })
  await cancel.getByLabel('Motif d’annulation', { exact: true }).fill('Abandon client')
  await cancel.getByRole('button', { name: 'Confirmer l’annulation' }).click()
  await expect(page.locator('.contact-page-heading')).toContainText('Annulé')
})
