import { test, expect, type Page } from '@playwright/test'
async function login(page: Page, email = 'crm@local.invalid') {
  await page.goto('/login')
  await page.getByLabel('Adresse e-mail', { exact: true }).fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill('Local-Horizon-test-only-2026!')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL('/')
}
const today = new Date().toISOString().slice(0, 10)
test('AO : dossier, visites et soutenances multiples, dépôt protégé et calendrier partagé', async ({ page }) => {
  await login(page)
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel', { exact: true }).fill('Client AO Horizon')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/companies\/(?!new)/)
  await page.goto('/crm')
  await page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('link', { name: 'Appels d’offres', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Appels d’offres', exact: true })).toBeVisible()
  await expect(page.getByRole('searchbox', { name: 'Rechercher dans les appels d’offres', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Nouvel appel d’offres', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Nouvel appel d’offres', exact: true })).toBeVisible()
  await page.getByLabel('Titre', { exact: true }).fill('AO Studio Horizon')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client AO Horizon', exact: true }).click()
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await page.getByLabel('Référence AO', { exact: true }).fill('AO-HORIZON-2026')
  await page.getByLabel('Publication', { exact: true }).fill(today)
  await page.getByLabel('Date et heure de remise', { exact: true }).fill(`${today}T18:00`)
  await expect(page.getByRole('button', { name: 'Ajouter : Tags AO', exact: true })).toHaveCount(0)
  await page.locator('.tender-dossier').getByLabel('Visite obligatoire', { exact: true }).check()
  await expect(page.locator('.tender-dossier').getByLabel('Visite obligatoire', { exact: true })).toBeChecked()
  await expect(page.getByRole('combobox', { name: 'Préparation de la réponse', exact: true })).toHaveText('À analyser')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/crm\/tenders\/(?!new)/)
  await expect(page.locator('.tender-dossier').getByLabel('Visite obligatoire', { exact: true })).toBeChecked()
  const href = page.url()
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  for (const kind of ['Visite', 'Soutenance', 'Visite']) {
    await page.getByRole('button', { name: 'Ajouter un rendez-vous', exact: true }).click()
    const dialog = page.getByRole('dialog')
    await dialog.getByRole('combobox', { name: 'Type de rendez-vous', exact: true }).click()
    await page.getByRole('option', { name: kind, exact: true }).click()
    await dialog.getByLabel('Date et heure', { exact: true }).fill(`${today}T10:00`)
    await expect(dialog.getByLabel('Fin', { exact: true })).toHaveCount(0)
    await dialog.getByLabel('Lieu ou lien de visioconférence', { exact: true }).fill('Paris / salle de réunion')
    if (kind === 'Soutenance') await page.screenshot({ path: '/private/tmp/horizon-ao-appointment.png' })
    await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
    await expect(dialog).toHaveCount(0)
  }
  await expect(page.getByRole('heading', { name: /Visites et soutenances/ })).toContainText('(3)')
  await page.getByLabel('Message du fil', { exact: true }).fill('Réponse et preuve de dépôt')
  await page.locator('input[type=file]').setInputFiles({ name: 'preuve.txt', mimeType: 'text/plain', buffer: Buffer.from('Réponse envoyée sur la plateforme') })
  await page.getByRole('button', { name: 'Publier', exact: true }).click()
  await expect(page.getByRole('link', { name: /preuve.txt/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Enregistrer un dépôt', exact: true })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Préparation de la réponse', exact: true }).click()
  await page.getByRole('option', { name: 'En préparation', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer un dépôt', exact: true }).click()
  const deposit = page.getByRole('dialog')
  await deposit.getByRole('checkbox', { name: 'preuve.txt', exact: true }).check()
  await deposit.getByRole('button', { name: 'Enregistrer le dépôt', exact: true }).click()
  await expect(deposit).toHaveCount(0)
  await expect(page.locator('.tender-submission-history')).toContainText('Version 1')
  await page.screenshot({ path: '/private/tmp/horizon-ao-record.png', fullPage: true })
  await page.goto('/crm?area=ao&view=calendar')
  await expect(page.locator('.business-calendar').getByRole('link', { name: /^Soutenance/ }).first()).toBeVisible()
  await expect(page.locator('.business-calendar')).toContainText('AO Studio Horizon')
  await page.goto('/calendar')
  await expect(page.locator('.business-calendar')).toContainText('AO Studio Horizon')
  await page.screenshot({ path: '/private/tmp/horizon-ao-calendar.png', fullPage: true })
  await page.goto('/crm?area=ao&view=list')
  await expect(page.getByRole('columnheader', { name: 'Remise', exact: true })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'État', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Ouvrir l’opportunité AO Studio Horizon', exact: true }).click()
  await expect(page).toHaveURL(href)
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await expect(page.locator('.tender-submission-history')).toContainText('Version 1')
  await page.getByRole('button', { name: 'Menu utilisateur', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Se déconnecter', exact: true }).click()
  await login(page, 'crm-reader@local.invalid')
  await page.goto(href)
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ajouter un rendez-vous', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Enregistrer un dépôt', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Référence AO', { exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Menu utilisateur', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Se déconnecter', exact: true }).click()
  await login(page, 'erp-admin@local.invalid')
  await page.goto('/settings/crm?tab=appointment-tags')
  await expect(page.getByRole('tab', { name: 'Tags AO', exact: true })).toHaveCount(0)
  await expect(page.getByRole('cell', { name: 'Visite', exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Modifier Visite', exact: true }).click()
  const colorDialog = page.getByRole('dialog', { name: 'Couleur · Visite', exact: true })
  await colorDialog.getByRole('radio', { name: 'Violet', exact: true }).check()
  await colorDialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(colorDialog).not.toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-appointment-tag-settings.png' })
  await page.goto(href)
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await expect(page.locator('.tender-appointments .h-tag').filter({ hasText: /^Visite$/ }).first()).toHaveAttribute('data-tone', 'violet')
  await page.goto('/crm?area=ao&view=list')
  await page.getByRole('button', { name: 'Filtres de recherche', exact: true }).click()
  await page.getByRole('radio', { name: 'Société', exact: true }).click()
  await expect(page.getByRole('radio', { name: 'Société', exact: true })).toBeChecked()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('link', { name: 'Ouvrir l’opportunité AO Studio Horizon', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Client AO Horizon', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Planning', exact: true }).click()
  await expect(page.locator('.business-calendar')).toContainText('AO Studio Horizon')
  await page.getByRole('button', { name: 'Kanban', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Étape En préparation', exact: true }).getByRole('link', { name: 'AO Studio Horizon', exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-ao-kanban.png', fullPage: true })

})


test('AO : les modifications arrivent dans la liste d’un autre onglet sans refresh', async ({ page, context }) => {
  await login(page)
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel', { exact: true }).fill('Client AO Realtime')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/contacts\/companies\/(?!new)/)
  await page.goto('/crm/opportunities/new?type=tender')
  await page.getByLabel('Titre', { exact: true }).fill('AO Realtime Horizon')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client AO Realtime', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/\/crm\/tenders\/(?!new)/)
  const observer = await context.newPage()
  await login(observer, 'crm-reader@local.invalid')
  await observer.goto('/crm?area=ao&view=list')
  await expect(observer.getByRole('link', { name: 'Ouvrir l’opportunité AO Realtime Horizon', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await page.getByLabel('Référence AO', { exact: true }).fill('AO-REALTIME-UPDATED')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await expect(observer.getByRole('cell', { name: /AO-REALTIME-UPDATED/ })).toBeVisible()
  await observer.getByRole('searchbox', { name: 'Rechercher dans les appels d’offres', exact: true }).fill('AO-REALTIME-UPDATED')
  await expect(observer.getByRole('link', { name: 'Ouvrir l’opportunité AO Realtime Horizon', exact: true })).toBeVisible()
  await observer.close()
})


test('conversion Directe / AO : archivage du dossier, historique et réactivation', async ({ page }) => {
  await login(page)
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel', { exact: true }).fill('Client conversion AO')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/contacts\/companies\/(?!new)/)
  await page.goto('/crm/opportunities/new')
  await page.getByLabel('Titre', { exact: true }).fill('Conversion sans perte')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client conversion AO', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/crm\/opportunities\/(?!new)/)
  const href = page.url()
  const number = await page.getByLabel('Numéro', { exact: true }).inputValue()
  const type = page.getByRole('combobox', { name: 'Type d’opportunité', exact: true })
  await expect(type).toBeEnabled()
  await type.click()
  await page.getByRole('option', { name: 'Appel d’offres', exact: true }).click()
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await page.getByLabel('Référence AO', { exact: true }).fill('CONVERSION-AO')
  await page.getByLabel('Publication', { exact: true }).fill(today)
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ajouter un rendez-vous', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Ajouter un rendez-vous', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Date et heure', { exact: true }).fill(`${today}T10:00`)
  await dialog.getByLabel('Lieu ou lien de visioconférence', { exact: true }).fill('Visite conservée')
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('tab', { name: 'Informations', exact: true }).click()
  await type.click()
  await page.getByRole('option', { name: 'Directe', exact: true }).click()
  await expect(page.getByText(/le dossier AO sera archivé/)).toBeVisible()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.reload()
  await expect(type).toHaveText('Directe')
  await expect(page.getByRole('tab', { name: 'Dossier AO', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Numéro', { exact: true })).toHaveValue(number)
  await page.goto('/crm?area=ao&view=list')
  await expect(page.getByRole('link', { name: 'Ouvrir l’opportunité Conversion sans perte', exact: true })).toHaveCount(0)
  await page.goto('/calendar')
  await expect(page.locator('.business-calendar')).not.toContainText('Conversion sans perte')
  await page.goto(href)
  await type.click()
  await page.getByRole('option', { name: 'Appel d’offres', exact: true }).click()
  await expect(page.getByText(/le dossier AO existant sera réactivé/)).toBeVisible()
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await expect(page.getByLabel('Référence AO', { exact: true })).toHaveValue('CONVERSION-AO')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true })).toBeDisabled()
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await expect(page.getByText('Visite conservée', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Référence AO', { exact: true })).toHaveValue('CONVERSION-AO')
  await page.getByRole('tab', { name: 'Informations', exact: true }).click()
  await expect(page.getByLabel('Numéro', { exact: true })).toHaveValue(number)
  await expect(page).toHaveURL(href)
  await page.goto('/calendar')
  await expect(page.locator('.business-calendar')).toContainText('Conversion sans perte')
})


test('AO autonome : No go sans affaire, promotion depuis la liste et planning partagé', async ({ page }) => {
  await login(page)
  await page.goto('/contacts/companies/new')
  await page.getByLabel('Nom usuel', { exact: true }).fill('Client décision AO')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/contacts\/companies\/(?!new)/)
  await page.goto('/crm/tenders/new')
  await page.getByLabel('Titre', { exact: true }).fill('AO à décider')
  await page.getByRole('button', { name: 'Ajouter : Types de marché', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Corporate', exact: true }).check()
  await page.keyboard.press('Escape')
  await page.getByRole('combobox', { name: 'Société', exact: true }).click()
  await page.getByRole('option', { name: 'Client décision AO', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Étape commerciale', exact: true })).toHaveCount(0)
  await page.getByRole('tab', { name: 'Dossier AO', exact: true }).click()
  await page.getByLabel('Référence AO', { exact: true }).fill('AO-DECISION')
  await page.getByLabel('Publication', { exact: true }).fill(today)
  const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().slice(0, 10)
  await page.getByLabel('Date et heure de remise', { exact: true }).fill(`${tomorrow}T18:00`)
  await expect(page.locator('.tender-deadline-panel .h-deadline time')).toHaveText(/^\d{2}\/\d{2}\/\d{4}$/)
  const detailsBounds = await page.locator('.tender-dossier-details').boundingBox()
  const scheduleBounds = await page.locator('.tender-dossier-schedule').boundingBox()
  expect(scheduleBounds!.x).toBeGreaterThan(detailsBounds!.x + detailsBounds!.width)
  await expect(page.locator('.tender-dossier').getByLabel('Visite obligatoire', { exact: true }).locator('..')).toHaveCSS('flex-direction', 'row')
  await expect(page.getByRole('button', { name: 'Effacer : Préparation de la réponse', exact: true })).toHaveCount(0)
  await page.screenshot({ path: '/private/tmp/horizon-ao-deadline-form.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.getByLabel('Date et heure de remise', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/horizon-ao-deadline-form-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/horizon-ao-deadline-form-dark.png' })
  await page.getByRole('button', { name: 'Passer en mode clair', exact: true }).click()
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page).toHaveURL(/crm\/tenders\/(?!new)/)
  const href = page.url()
  await expect(page.getByRole('tab', { name: 'Dossier AO', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: 'Informations', exact: true }).click()
  await expect(page.getByLabel('Numéro', { exact: true })).toHaveValue('')
  await page.goto('/crm?area=ao&view=kanban&q=AO-DECISION')
  await expect(page.locator('.crm-card-footer .h-deadline')).toHaveAttribute('title', /^Remise/)
  await expect(page.locator('.crm-opportunity-card')).not.toContainText('%')
  await expect(page.locator('.crm-card-footer .h-deadline')).toHaveAttribute('data-state', 'urgent')
  await expect(page.locator('.crm-card-footer .h-deadline')).toHaveCSS('color', 'rgb(220, 38, 38)')
  await expect(page.locator('.crm-card-footer .h-deadline')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(page.locator('.crm-card-footer .h-deadline .lucide-calendar-days')).toHaveCount(1)
  await expect(page.locator('.crm-card-footer .crm-card-ao')).toHaveText('AO')
  await expect(page.locator('.crm-card-content .crm-card-ao')).toHaveCount(0)
  await expect(page.locator('.crm-card-content .crm-card-markets')).toHaveText('Corporate')
  await expect(page.locator('.crm-card-footer')).not.toContainText('Corporate')
  await expect(page.locator('.crm-card-footer .h-deadline time')).toHaveText(/^\d{2}\/\d{2}\/\d{4}$/)
  await page.screenshot({ path: '/private/tmp/horizon-ao-deadline-card.png', fullPage: true })
  await page.goto('/crm?area=ao&view=list&q=AO-DECISION')
  const preparation = page.getByRole('combobox', { name: 'Préparation de AO à décider', exact: true })
  await expect(page.getByRole('button', { name: 'Effacer : Préparation de AO à décider', exact: true })).toHaveCount(0)
  await expect(preparation).toBeVisible()
  await expect(preparation.locator('xpath=ancestor::tr').getByRole('cell').nth(7)).toHaveText(/^\d{2}\/\d{2}\/\d{4}$/)
  const controlBox = await preparation.boundingBox()
  const cellBox = await preparation.locator('xpath=ancestor::td').boundingBox()
  expect(controlBox!.height).toBe(28)
  expect(Math.abs(controlBox!.y + controlBox!.height / 2 - cellBox!.y - cellBox!.height / 2)).toBeLessThanOrEqual(1)
  await page.screenshot({ path: '/private/tmp/horizon-ao-list-controls.png' })
  await preparation.click()
  await page.getByRole('option', { name: 'No go', exact: true }).click()
  await expect(preparation).toHaveText('No go')
  await page.reload()
  await expect(preparation).toHaveText('No go')
  await page.goto('/crm?view=list&q=AO à décider')
  await expect(page.getByRole('link', { name: 'Ouvrir l’opportunité AO à décider', exact: true })).toHaveCount(0)
  await page.goto(href)
  await expect(page.getByLabel('Numéro', { exact: true })).toHaveValue('')
  await page.goto('/crm?area=ao&view=calendar&q=AO-DECISION')
  await expect(page.locator('.calendar-timeline-identity')).toContainText('AO à décider')
  for (const period of ['Semaine', 'Trimestre', 'Année', 'Mois']) {
    await page.getByRole('combobox', { name: 'Période du calendrier', exact: true }).click()
    await page.getByRole('option', { name: period, exact: true }).click()
    await expect(page.locator('.calendar-timeline-identity')).toContainText('AO à décider')
  }
  await page.screenshot({ path: '/private/tmp/horizon-ao-planning.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-ao-planning-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.goto('/crm?area=ao&view=list&q=AO-DECISION')
  await preparation.click()
  await page.getByRole('option', { name: 'En préparation', exact: true }).click()
  await expect(preparation).toHaveText('En préparation')
  await page.goto(href)
  await expect(page.getByLabel('Numéro', { exact: true })).not.toHaveValue('')
  const number = await page.getByLabel('Numéro', { exact: true }).inputValue()
  await page.reload()
  await expect(page.getByLabel('Numéro', { exact: true })).toHaveValue(number)
  await page.goto('/crm?view=list&q=AO à décider')
  await expect(page.getByRole('link', { name: 'Ouvrir l’opportunité AO à décider', exact: true })).toHaveCount(1)
})
