import { expect, test } from '@playwright/test'

test('le socle charge sans erreur ni requête PocketBase', async ({ page }) => {
  const errors: string[] = []
  const backendRequests: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('request', (request) => {
    if (request.url().includes('172.30.10.10:50190')) {
      backendRequests.push(request.url())
    }
  })

  await page.goto('/')
  await expect(page).toHaveTitle('Horizon — CVS Engineering')
  await expect(page.getByRole('heading', { name: 'Dashboard', level: 1 })).toBeVisible()
  expect(await page.locator('html').getAttribute('lang')).toBe('fr')
  expect(errors).toEqual([])
  expect(backendRequests).toEqual([])
})

test('une adresse inconnue permet de revenir à l’accueil', async ({ page }) => {
  await page.goto('/page-inconnue')
  await expect(page.getByRole('heading', { name: 'Page introuvable' })).toBeVisible()
  await page.getByRole('link', { name: 'Revenir à l’accueil' }).click()
  await expect(page).toHaveURL('/')
  await expect(page.getByRole('heading', { name: 'Dashboard', level: 1 })).toBeVisible()
})

test('la navigation et le fil d’Ariane restent cohérents en mode réduit', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Réduire la navigation' }).click()
  await expect(page.getByRole('button', { name: 'Développer la navigation' })).toHaveAttribute('aria-expanded', 'false')
  await page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('link', { name: 'Contacts', exact: true }).click()
  await expect(page).toHaveURL('/contacts')
  await expect(page.getByRole('heading', { name: 'Contacts', exact: true })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Fil d’Ariane' }).getByText('Contacts')).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('link', { name: 'Contacts', exact: true })).toHaveAttribute('aria-current', 'page')
})

test('la sidebar conserve le module actif dans ses onglets et fiches', async ({ page }) => {
  for (const path of ['/contacts', '/contacts/people', '/contacts/companies/new', '/contacts/people/new']) {
    await page.goto(path)
    const navigation = page.getByRole('navigation', { name: 'Navigation principale' })
    await expect(navigation.getByRole('link', { name: 'Contacts', exact: true })).toHaveAttribute('aria-current', 'page')
    await expect(navigation.locator('.sidebar-link--active')).toHaveCount(1)
    await expect(navigation.getByRole('link', { name: 'Dashboard', exact: true })).not.toHaveAttribute('aria-current')
  }
  await page.goto('/')
  const navigation = page.getByRole('navigation', { name: 'Navigation principale' })
  await expect(navigation.getByRole('link', { name: 'Dashboard', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(navigation.getByRole('link', { name: 'Contacts', exact: true })).not.toHaveAttribute('aria-current')
})

test('la recherche clavier filtre les espaces et ouvre le bon écran', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Rechercher un espace…' }).focus()
  await page.keyboard.press('Control+k')
  const dialog = page.getByRole('dialog', { name: 'Rechercher un espace', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('textbox')).toBeFocused()
  await dialog.getByRole('textbox').fill('depenses')
  await expect(dialog.getByRole('link')).toHaveCount(1)
  await dialog.getByRole('link').click()
  await expect(page).toHaveURL('/expenses')
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Dépenses', exact: true })).toBeVisible()
})

test('la recherche sans résultat se ferme avec Échap et restitue le focus', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'Rechercher un espace…' })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Rechercher un espace', exact: true })
  await dialog.getByRole('textbox').fill('inexistant')
  await expect(dialog.getByText('Aucun espace trouvé. Essayez un autre terme.')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
})

test('l’aide ouvre un dialogue accessible et se ferme', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Aide et raccourcis' }).click()
  const dialog = page.getByRole('dialog', { name: 'Bienvenue dans Horizon' })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Fermer' }).click()
  await expect(dialog).not.toBeVisible()
})

test('le layout reste lisible sur desktop et mobile sans débordement horizontal', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  for (const width of [1440, 900, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    const search = page.locator('.workspace-search')
    await expect(search).toBeVisible()
    const barBounds = await page.locator('.topbar').boundingBox()
    const searchBounds = await search.boundingBox()
    expect(Math.abs(searchBounds!.x + searchBounds!.width / 2 - barBounds!.x - barBounds!.width / 2)).toBeLessThan(1)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '/private/tmp/horizon-layout-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('heading', { name: 'Dashboard', level: 1 })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-layout-mobile.png', fullPage: true })
})

test('la top bar reste en haut pendant le défilement et le compte reste accessible', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 450 })
  await page.goto('/settings')
  await expect(page.getByRole('heading', { name: 'Paramètres', level: 1, exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight))
  expect(await page.evaluate(() => window.scrollY)).toBeGreaterThan(100)
  expect((await page.locator('.topbar').boundingBox())?.y).toBe(0)
  expect((await page.locator('.page-breadcrumb-row').boundingBox())?.y).toBe((await page.locator('.topbar').boundingBox())?.height)
  await page.getByRole('button', { name: 'Menu utilisateur' }).click()
  await expect(page.getByRole('menuitem', { name: 'Paramètres' })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 450 })
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight))
  expect((await page.locator('.topbar').boundingBox())?.y).toBe(0)
  expect((await page.locator('.page-breadcrumb-row').boundingBox())?.y).toBe((await page.locator('.topbar').boundingBox())?.height)
  await expect(page.getByRole('button', { name: 'Menu utilisateur' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('contexte automatique, choix global et retour au contexte de la nouvelle page', async ({ page }) => {
  await page.goto('/contacts?q=Acme')
  const scope = page.getByRole('button', { name: 'Choisir le contexte de recherche' })
  await expect(scope).toHaveText('Contacts')
  await scope.click()
  await page.getByRole('menuitemradio', { name: 'Tout Horizon' }).click()
  await expect(scope).toHaveText('Tout Horizon')
  await page.keyboard.press('Control+k')
  const dialog = page.getByRole('dialog', { name: 'Rechercher un espace', exact: true })
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Escape')
  await scope.click()
  await page.getByRole('menuitemradio', { name: 'Sociétés', exact: true }).click()
  await expect(page.getByRole('searchbox')).toHaveValue('Acme')
  await scope.click()
  await page.getByRole('menuitemradio', { name: 'Tout Horizon' }).click()
  await page.getByRole('navigation', { name: 'Référentiel Contacts' }).getByRole('link', { name: 'Personnes' }).click()
  await expect(scope).toHaveText('Personnes')
  await page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('link', { name: 'Paramètres', exact: true }).click()
  await expect(scope).toHaveText('Paramètres')
  await page.getByRole('searchbox', { name: 'Rechercher dans les paramètres' }).fill('introuvable 987')
  await expect(page.getByText('Aucune rubrique ne correspond à cette recherche.')).toBeVisible()
  await page.getByRole('button', { name: 'Effacer la recherche' }).click()
  await expect(page.getByText('Aucune rubrique ne correspond à cette recherche.')).not.toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await scope.click()
  await expect(page.getByRole('menuitemradio', { name: 'Tout Horizon' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})


test('thème clair / sombre : bascule, persistance et menus adaptés', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(14, 23, 38)')
  await expect(page.locator('.topbar')).toHaveCSS('background-color', 'rgb(22, 34, 54)')
  await page.getByRole('button', { name: 'Menu utilisateur', exact: true }).click()
  await expect(page.getByRole('menu')).toHaveCSS('background-color', 'rgb(22, 34, 54)')
  await page.keyboard.press('Escape')
  await page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('link', { name: 'Paramètres', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('heading', { name: 'Paramètres', level: 1, exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.screenshot({ path: '/private/tmp/horizon-dark-settings.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Passer en mode clair', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Menu utilisateur', exact: true })).toBeVisible()
  const search = await page.locator('.workspace-search').boundingBox()
  const bar = await page.locator('.topbar').boundingBox()
  expect(Math.abs(search!.x + search!.width / 2 - bar!.x - bar!.width / 2)).toBeLessThan(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/horizon-dark-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Passer en mode clair', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(245, 248, 253)')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
})

test('thème : préférence appliquée au démarrage et synchronisée entre onglets', async ({ page }) => {
  await page.addInitScript(() => { if (!localStorage.getItem('horizon.theme')) localStorage.setItem('horizon.theme', 'dark') })
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  const other = await page.context().newPage()
  await other.goto('/')
  await expect(other.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: 'Passer en mode clair', exact: true }).click()
  await expect(other.locator('html')).toHaveAttribute('data-theme', 'light')
  await other.close()
})

test('thème : bascule utilisable même si le stockage navigateur est bloqué', async ({ page }) => {
  await page.addInitScript(() => {
    Storage.prototype.getItem = () => { throw new DOMException('Storage disabled', 'SecurityError') }
    Storage.prototype.setItem = () => { throw new DOMException('Storage disabled', 'SecurityError') }
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Passer en mode sombre', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: 'Passer en mode clair', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
})
