import { ActivityPanel } from '../../../shared/activity/ActivityPanel'
import { useState, useEffect, useId } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useForm, useWatch } from 'react-hook-form'
import { useParams, useSearchParams, useNavigate, useLocation } from 'react-router'
import { Package, Tags, Calculator, Truck, Landmark, Undo2, ShoppingCart, Store, ArrowRight, Ruler, Barcode } from 'lucide-react'
import { useRecordSession } from '../../../shared/records/recordContext'
import { HPageBreadcrumb } from '../../../shared/ui/HPageBreadcrumb'
import { HRecordPageActions } from '../../../shared/ui/HRecordPageActions'
import { HRecordActions } from '../../../shared/ui/HRecordActions'
import { HRecordTabs } from '../../../shared/ui/HRecordTabs'
import { HSectionHeading } from '../../../shared/ui/HSectionHeading'
import { HSaveButton } from '../../../shared/ui/HSaveButton'
import { HButton } from '../../../shared/ui/HButton'
import { HAmountInput } from '../../../shared/ui/HAmountInput'
import { HInput } from '../../../shared/ui/HInput'
import { HFieldLabel } from '../../../shared/ui/HFieldLabel'
import { HCombobox } from '../../../shared/ui/HCombobox'
import { HBadge } from '../../../shared/ui/HBadge'
import { HLoadingIndicator } from '../../../shared/ui/HLoadingIndicator'
import { HEmptyState } from '../../../shared/ui/HEmptyState'
import { formatUnitAmount as formatAmount } from '../../../shared/formatters/money'
import { catalogService } from '../services/CatalogService'
import { useCatalogAccess } from '../hooks/useCatalogAccess'
import { productInputSchema, productDefaults, emptyFiles, type Product, type ProductInput, type CatalogChoices } from '../schemas/catalog'
import { LastPurchaseSummary } from '../components/LastPurchaseSummary'
import { ProductBusinessLinks } from '../components/ProductBusinessLinks'
import { ProductDuplication } from '../components/ProductDuplication'
import { ProductImages } from '../components/ProductImages'
import { BrandPicker } from '../components/BrandPicker'
import { SupplierPrices } from '../components/SupplierPrices'
import '../catalog.css'
const tabs = [{ value: 'general', label: 'Informations', panel: 'product-general' }, { value: 'purchases', label: 'Achats', panel: 'product-purchases' }, { value: 'policies', label: 'Logistique', panel: 'product-policies' }, { value: 'accounting', label: 'Comptabilité', panel: 'product-accounting' }]
export function ProductPage() {
  const embedded = useRecordSession(), { id: routeId = 'new' } = useParams(), access = useCatalogAccess(), [params, setParams] = useSearchParams(), [localTab, setLocalTab] = useState('general')
  const [localDuplicate, setLocalDuplicate] = useState<{ id: string; includeSuppliers: boolean }>()
  const duplicateId = localDuplicate?.id || (routeId === 'new' && !embedded ? params.get('duplicate') || '' : embedded?.initial?.duplicate || '')
  const includeSuppliers = localDuplicate?.includeSuppliers ?? (embedded ? embedded.initial?.suppliers === '1' : params.get('suppliers') === '1')
  const id = duplicateId ? 'new' : embedded?.id || (embedded ? 'new' : routeId), current = embedded ? localTab : params.get('tab'), tab = tabs.some((item) => item.value === current) ? current! : 'general'
  const record = useQuery({ queryKey: ['inventory', 'product', id], queryFn: () => catalogService.record(id), enabled: access.canRead && id !== 'new', retry: false })
  const choices = useQuery({ queryKey: ['inventory', 'choices'], queryFn: () => catalogService.choices(), enabled: access.canRead, retry: false })
  const duplicate = useQuery({ queryKey: ['inventory', 'duplicate', duplicateId, includeSuppliers], queryFn: () => catalogService.duplicateDraft(duplicateId, includeSuppliers), enabled: access.canWrite && Boolean(duplicateId), retry: false })
  if (duplicateId && !access.canWrite) return <HEmptyState icon={Package} title="Produit" description="Vous ne pouvez pas dupliquer un produit." />
  if (!access.canRead) return <HEmptyState icon={Package} title="Produit" description="Accès au catalogue refusé." />
  const error = record.error || choices.error || duplicate.error
  if (error) return <p role="alert" className="field-error">{error.message}<HButton onClick={() => { void record.refetch(); void choices.refetch(); if (duplicateId) void duplicate.refetch() }}>Réessayer</HButton></p>
  if (!choices.data || id !== 'new' && !record.data || duplicateId && !duplicate.data) return <HLoadingIndicator label="Chargement du produit" />
  return <ProductEditor key={`${id}:${duplicateId}:${includeSuppliers}:${record.data?.updated || ''}`} record={duplicateId ? undefined : record.data} duplicateDraft={duplicateId ? duplicate.data : undefined} onDuplicate={(source, suppliers) => setLocalDuplicate({ id: source, includeSuppliers: suppliers })} choices={choices.data} tab={tab} onTab={(value) => embedded ? setLocalTab(value) : setParams((current) => { const next = new URLSearchParams(current); next.set('tab', value); return next }, { replace: true })} />
}
function ProductEditor({ record, duplicateDraft, onDuplicate, choices, tab, onTab }: { record: Product | undefined; duplicateDraft: { input: ProductInput; files: ReturnType<typeof emptyFiles> } | undefined; onDuplicate: (id: string, includeSuppliers: boolean) => void; choices: CatalogChoices; tab: string; onTab: (value: string) => void }) {
  const embedded = useRecordSession(), access = useCatalogAccess(), navigate = useNavigate(), location = useLocation(), client = useQueryClient(), formId = useId()
  const [creationKey] = useState(() => crypto.randomUUID()), [files, setFiles] = useState(() => duplicateDraft?.files || emptyFiles()), [error, setError] = useState(''), [duplicating, setDuplicating] = useState(false)
  const initial = duplicateDraft?.input || (record ? productInputSchema.parse({ ...record, offers: record.offers.map((offer) => ({ ...offer, valid_from: offer.valid_from.slice(0, 10), valid_until: offer.valid_until.slice(0, 10) })) }) : productDefaults(choices, embedded?.initial?.search || ''))
  const form = useForm<ProductInput>({ defaultValues: initial }), values = useWatch({ control: form.control }), input = { ...initial, ...values } as ProductInput
  const dirty = Boolean(duplicateDraft) || JSON.stringify(input) !== JSON.stringify(initial) || Boolean(files.primary || files.images.length || files.removePrimary || files.removeImages.length), editable = access.canWrite && (!record || record.active)
  const listQuery = typeof location.state?.productListQuery === 'string' ? location.state.productListQuery : '', listHref = `/inventory${listQuery ? `?${listQuery}` : ''}`
  async function updated(saved: Product) { client.setQueryData(['inventory', 'product', saved.id], saved); await Promise.all([client.invalidateQueries({ queryKey: ['inventory', 'products'] }), client.invalidateQueries({ queryKey: ['inventory', 'choices'] }), client.invalidateQueries({ queryKey: ['activity', 'inventory_products'] })]); if (embedded) embedded.onSaved({ id: saved.id, label: `${saved.sku} · ${saved.name}` }); else if (!record) navigate(`/inventory/products/${saved.id}?tab=${tab}`, { replace: true, state: { productListQuery: listQuery } }) }
  const save = useMutation({ mutationFn: (input: ProductInput) => catalogService.save(input, creationKey, files, record), onSuccess: updated }), state = useMutation({ mutationFn: (active: boolean) => catalogService.state(record!, active), onSuccess: updated }), pending = save.isPending || state.isPending
  useEffect(() => { embedded?.report({ dirty, busy: pending }) }, [embedded, dirty, pending])
  const family = choices.categories.find((item) => item.id === input.category), favorite = input.offers.find((item) => item.is_preferred), unit = choices.units.find((item) => item.id === input.base_unit)?.code || 'u'
  const cost = favorite && !input.cost_override ? favorite.list_price * (1 - favorite.discount / 100) / favorite.purchase_quantity : input.reference_cost
  const coefficient = input.coefficient_override ? input.manual_coefficient : family?.coefficient || 1
  const price = cost * coefficient, warning = !input.cost_override && favorite && favorite.currency !== input.sale_currency ? 'La devise du fournisseur est différente. Aucune conversion automatique.' : !input.cost_override && favorite && (favorite.valid_from && favorite.valid_from > new Date().toISOString().slice(0, 10) || favorite.valid_until && favorite.valid_until < new Date().toISOString().slice(0, 10)) ? 'Le prix du fournisseur favori est hors validité.' : !family?.active ? 'Cette famille est archivée.' : !input.cost_override && record && record.pricing.product_supplier === favorite?.id ? record.pricing.warning : ''
  const set = (key: keyof ProductInput, value: ProductInput[keyof ProductInput]) => form.setValue(key, value, { shouldDirty: true })
  const options = (items: { id: string; label: string; active: boolean }[]) => items.map((item) => ({ value: item.id, label: item.label, disabled: !item.active && ![input.category, input.base_unit].includes(item.id) }))
  return <div className="contact-record catalog-record"><HPageBreadcrumb items={[{ label: 'Accueil', href: '/' }, { label: 'Produits', href: listHref }, { label: record?.sku || 'Nouveau produit' }]} />
    <div className="contact-record-toolbar"><div className="contact-title-group"><div className="contact-page-heading"><h1>{record?.name || 'Nouveau produit'}</h1>{record && <HBadge tone={record.active ? 'success' : 'neutral'}>{record.active ? 'Actif' : 'Archivé'}</HBadge>}</div></div><HRecordPageActions inline={Boolean(embedded)}><HButton variant="ghost" size="icon" title="Annuler les modifications" aria-label="Annuler les modifications" disabled={!dirty || pending} onClick={() => { form.reset(initial); setFiles(emptyFiles()); setError(''); save.reset() }}><Undo2 size={14} /></HButton><HSaveButton form={formId} hasChanges={dirty} pending={save.isPending} disabled={!editable || pending}>Enregistrer</HSaveButton>{record && access.canWrite && <HRecordActions active={record.active} itemName={record.name} disabled={dirty || pending} onDuplicate={() => setDuplicating(true)} onArchive={() => state.mutateAsync(false)} onRestore={() => state.mutate(true)} />}</HRecordPageActions></div>
    {duplicating && record && <ProductDuplication name={record.name} onClose={() => setDuplicating(false)} onDuplicate={(suppliers) => { setDuplicating(false); if (embedded) onDuplicate(record.id, suppliers); else navigate(`/inventory/products/new?duplicate=${record.id}&suppliers=${suppliers ? '1' : '0'}`, { state: { productListQuery: listQuery } }) }} />}
    {record && <ProductBusinessLinks id={record.id} name={record.name} inline={Boolean(embedded)} busy={dirty || pending} />}
    <form className="contact-record-sheet" id={formId} onSubmit={form.handleSubmit((value) => { const parsed = productInputSchema.safeParse(value); if (!parsed.success) { setError(parsed.error.issues[0]?.message || 'Vérifiez la fiche.'); return }; if (dirty && editable) { setError(''); save.mutate(parsed.data) } })}><fieldset className="access-fieldset" disabled={!editable || pending}>
      <section className="contact-panel catalog-identity"><ProductImages query={[input.manufacturer, input.sku, input.name].filter(Boolean).join(' ').slice(0, 160)} record={record} files={files} onChange={setFiles} disabled={!editable || pending} /><div className="catalog-identity-fields"><HSectionHeading title="Identité du produit" icon={Package} /><div className="contact-fields catalog-identity-grid">
        <label className="catalog-product-name"><HFieldLabel required>Nom du produit</HFieldLabel><HInput {...form.register('name')} maxLength={200} required placeholder="Désignation du produit ou service" /></label>
        <label><HFieldLabel required>Marque</HFieldLabel><BrandPicker value={input.brand} brands={choices.brands} disabled={!editable || pending} onChange={(brand, name) => { set('brand', brand); set('manufacturer', name) }} /></label>
        <label><HFieldLabel required>Référence</HFieldLabel><HInput {...form.register('sku')} autoFocus={Boolean(duplicateDraft)} required maxLength={80} /></label>
        <label><HFieldLabel required>Famille de produit</HFieldLabel><HCombobox label="Famille de produit" required clearable={false} showCodes={false} value={input.category} options={options(choices.categories)} onChange={(value) => set('category', value)} disabled={!editable || pending} /></label>
        <label><HFieldLabel required>Unité de base</HFieldLabel><HCombobox label="Unité de base" required clearable={false} showCodes={false} value={input.base_unit} options={options(choices.units.map((item) => ({ ...item, label: `${item.code} · ${item.label}` })))} onChange={(value) => set('base_unit', value)} disabled={!editable || pending || Boolean(record?.unit_locked)} /></label>
        <div className="catalog-usage contact-role-toggles"><label><input type="checkbox" {...form.register('sale_enabled')} /><Store size={13} aria-hidden="true" />Peut être vendu</label><label><input type="checkbox" {...form.register('purchase_enabled')} /><ShoppingCart size={13} aria-hidden="true" />Peut être acheté</label></div>
      </div></div></section></fieldset>
      <HRecordTabs label="Fiche produit" idPrefix="product-tab" value={tab} onChange={onTab} items={tabs} />
      <fieldset className="access-fieldset" disabled={!editable || pending}><section className={`contact-panel ${tab === 'general' ? 'catalog-general' : tab === 'policies' ? 'catalog-logistics' : ''}`} role="tabpanel" id={`product-${tab}`} aria-labelledby={`product-tab-${tab}`}>
        {tab === 'general' && <><div className="catalog-details"><HSectionHeading title="Informations produit" icon={Tags} /><div className="contact-fields"><label className="catalog-barcode-field"><HFieldLabel><Barcode size={14} aria-hidden="true" />Code-barres</HFieldLabel><HInput {...form.register('barcode')} maxLength={100} /></label><label><HFieldLabel>Groupe de variantes</HFieldLabel><HInput {...form.register('variant_group')} maxLength={120} placeholder="Ex. Famille de connecteurs BNC" /></label><label className="contact-field-wide"><HFieldLabel>Description pour les devis</HFieldLabel><textarea className="h-input" rows={3} maxLength={2000} {...form.register('description')} placeholder="Description proposée lors de l’ajout au devis" /></label></div></div>        <div className="catalog-pricing"><HSectionHeading title="Prix de vente" icon={Calculator} actions={<HCombobox label="Devise de vente" required clearable={false} showCodes={false} value={input.sale_currency} options={choices.currencies.map((item) => ({ value: item.code, label: item.code }))} onChange={(value) => set('sale_currency', value)} disabled={!editable || pending} />} />
          <div className="catalog-price-flow">
            <div className="catalog-price-step"><span className="catalog-price-label">Coût HT / {unit}</span><HAmountInput aria-label={`${favorite && !input.cost_override ? 'Coût du fournisseur favori' : 'Coût de référence'} / ${unit}`} inlineCurrency unitPrecision value={cost} currency={favorite && !input.cost_override ? favorite.currency : input.sale_currency} onChange={(value) => set('reference_cost', value)} disabled={Boolean(favorite && !input.cost_override) || !editable || pending} /><label className="catalog-cost-override contact-checkbox"><input type="checkbox" checked={input.cost_override} onChange={(event) => { if (event.target.checked) set('reference_cost', cost); set('cost_override', event.target.checked) }} />Utiliser un coût manuel</label><small>{favorite && !input.cost_override ? choices.suppliers.find((item) => item.id === favorite.supplier)?.name || 'Fournisseur favori' : 'Coût de référence'}</small></div>
            <span className="catalog-price-operator" aria-hidden="true">×</span>
            <div className="catalog-price-step"><div className="catalog-coefficient-label"><span className="catalog-price-label">Coefficient</span></div><HInput aria-label="Coefficient de vente" type="number" max={100} step={0.1} value={coefficient} disabled={!input.coefficient_override || !editable || pending} onChange={(event) => set('manual_coefficient', event.target.value === '' ? Number.NaN : Number(event.target.value))} /><label className="catalog-cost-override contact-checkbox"><input type="checkbox" checked={input.coefficient_override} onChange={(event) => { if (event.target.checked) set('manual_coefficient', coefficient); set('coefficient_override', event.target.checked) }} />Coefficient manuel</label><small>{input.coefficient_override ? 'Personnalisé pour ce produit' : `Famille · ${family?.label || '—'}`}</small></div>
            <span className="catalog-price-operator" aria-hidden="true"><ArrowRight size={15} /></span>
            <div className="catalog-price-result"><span className="catalog-price-label">Prix de vente HT / {unit}</span><strong className="catalog-sale-price">{!warning && Number.isFinite(price) ? formatAmount(price, input.sale_currency) : 'À vérifier'}</strong><small>{!warning && Number.isFinite(price) && price > 0 ? `Marge · ${((price - cost) / price * 100).toLocaleString('fr-FR', { maximumFractionDigits: 2 })} %` : 'Marge · —'}</small></div>
          </div>{warning && <p role="status" className="field-error">{warning}</p>}</div></>}
        {tab === 'purchases' && <><LastPurchaseSummary price={record?.last_purchase?.unit_cost ?? null} date={record?.last_purchase?.date || ''} currency={record?.last_purchase?.currency || input.sale_currency} unit={record?.last_purchase?.unit || unit} supplier={record?.last_purchase?.supplier_name || ''} description={record?.last_purchase ? 'Dernier achat enregistré.' : 'Aucun achat enregistré.'} /><HSectionHeading title="Fournisseurs" icon={Truck} /><SupplierPrices record={record} choices={choices} values={input.offers} onChange={(offers) => set('offers', offers)} unit={unit} currency={input.sale_currency} disabled={!editable || pending || !input.purchase_enabled} onReload={async () => { await client.invalidateQueries({ queryKey: ['inventory', 'choices'] }) }} />{record?.price_history.length ? <details className="catalog-history"><summary>Historique des prix d’achat ({record.price_history.length})</summary><div className="data-table-scroll"><table className="h-data-table"><thead><tr><th>Date</th><th>Référence fournisseur</th><th>Prix liste</th><th>Remise</th><th>Prix net</th></tr></thead><tbody>{record.price_history.map((item) => <tr key={item.id}><td>{new Date(item.effective_at).toLocaleDateString('fr-FR')}</td><td>{item.snapshot.supplier_sku}</td><td>{formatAmount(item.snapshot.list_price, item.currency)}</td><td>{item.snapshot.discount} %</td><td>{formatAmount(item.price, item.currency)}</td></tr>)}</tbody></table></div></details> : null}</>}
        {tab === 'policies' && <><div className="catalog-logistic-policy"><HSectionHeading title="Politiques logistiques" icon={Package} description="Gestion du stock, approvisionnement et traçabilité." /><div className="contact-fields catalog-policy-fields">{([['stock_policy', 'Gestion du stock', { none: 'Sans stock', stocked: 'Stocké', on_demand: 'À la demande' }], ['replenishment_policy', 'Approvisionnement', { manual: 'Manuel', on_demand: 'À la demande', min_max: 'Minimum / maximum' }], ['tracking', 'Traçabilité', { none: 'Sans suivi', lot: 'Par lot', serial: 'Par numéro de série' }]] as const).map(([key, label, entries]) => <label key={key}><HFieldLabel>{label}</HFieldLabel><HCombobox label={label} required clearable={false} showCodes={false} value={input[key]} options={Object.entries(entries).map(([value, label]) => ({ value, label }))} onChange={(value) => set(key, value as ProductInput[typeof key])} disabled={!editable || pending || input.kind === 'service' && key !== 'replenishment_policy'} /></label>)}</div></div><div className="catalog-logistic-details"><HSectionHeading title="Caractéristiques logistiques" description="Poids, encombrement et informations douanières." icon={Ruler} /><div className="contact-fields catalog-logistic-fields"><label><HFieldLabel>Poids (kg)</HFieldLabel><HInput type="number" min={0} step="any" {...form.register('weight_kg', { setValueAs: (value: string) => value === '' ? 0 : Number(value) })} /></label><label><HFieldLabel>Volume (m³)</HFieldLabel><HInput type="number" min={0} step="any" {...form.register('volume_m3', { setValueAs: (value: string) => value === '' ? 0 : Number(value) })} /></label><label><HFieldLabel>Code SH</HFieldLabel><HInput inputMode="numeric" maxLength={10} placeholder="Ex. 854442" {...form.register('hs_code')} /></label><label><HFieldLabel>Pays d’origine</HFieldLabel><HCombobox label="Pays d’origine" value={input.origin_country} options={choices.countries.map((country) => ({ value: country.code, label: country.label, disabled: !country.active && country.code !== input.origin_country }))} showCodes={false} onChange={(value) => set('origin_country', value)} disabled={!editable || pending} /></label></div></div></>}
        {tab === 'accounting' && <><HSectionHeading title="Comptabilité" icon={Landmark} /><p className="contact-muted">Les comptes de vente, d’achat et la TVA du produit seront configurés ici lors du raccordement comptable.</p></>}

      </section>
    </fieldset>{(error || save.error || state.error) && <p role="alert" className="field-error">{error || save.error?.message || state.error?.message}</p>}</form>{record && <ActivityPanel source={{ entity: 'inventory_products', id: record.id }} editable={access.canWrite && record.active && !pending} />}
  </div>
}
