migrate((app) => {
  const auth = '@request.auth.collectionName = "core_users" && @request.auth.active = true && @request.auth.role.active = true'
  const read = `${auth} && @request.auth.role.permissions ~ '"crm.read"'`
  const configure = `${auth} && (@request.auth.erp_profile = "admin" || @request.auth.erp_profile = "superuser") && @request.auth.role.permissions ~ '"settings.references"'`
  const text = (name, max, required = false) => ({ name, type: 'text', max, required })
  const rel = (name, collection, required = false, maxSelect = 1) => ({ name, type: 'relation', collectionId: app.findCollectionByNameOrId(collection).id, required, maxSelect, cascadeDelete: false })
  const dates = [{ name: 'created', type: 'autodate', onCreate: true }, { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true }]
  for (const name of ['crm_tender_statuses', 'crm_tender_tags']) {
    const collection = new Collection({ name, type: 'base', listRule: `(${read}) || (${configure})`, viewRule: `(${read}) || (${configure})`, createRule: configure, updateRule: configure, deleteRule: null, fields: [text('code', 35, true), text('label', 120, true), { name: 'tone', type: 'select', values: ['blue', 'violet', 'pink', 'green', 'amber', 'navy'], maxSelect: 1, required: true }, text('color', 7), { name: 'sort_order', type: 'number', min: 0, onlyInt: true }, { name: 'active', type: 'bool' }, ...dates], indexes: [`CREATE UNIQUE INDEX idx_${name}_code ON ${name} (code)`] })
    app.save(collection)
    const seeds = name === 'crm_tender_statuses' ? [['todo', 'À analyser', 'blue'], ['preparing', 'En préparation', 'violet'], ['review', 'À vérifier', 'amber'], ['ready', 'Prête', 'pink'], ['submitted', 'Déposée', 'green']] : []
    seeds.forEach(([code, label, tone], index) => { const record = new Record(collection); for (const [key, value] of Object.entries({ code, label, tone, sort_order: index * 10, active: true })) record.set(key, value); app.save(record) })
  }
  const opportunity = app.findCollectionByNameOrId('crm_opportunities'); opportunity.fields.getByName('type').values = ['direct', 'tender']; app.save(opportunity)
  app.save(new Collection({ name: 'crm_tenders', type: 'base', listRule: read, viewRule: read, createRule: null, updateRule: null, deleteRule: null, fields: [rel('opportunity', 'crm_opportunities', true), text('reference', 160), text('consultation_url', 1000), rel('status', 'crm_tender_statuses', true), { name: 'order', type: 'number', min: 0, onlyInt: true }, { name: 'publication_date', type: 'date' }, { name: 'submission_deadline', type: 'date' }, text('timezone', 80, true), { name: 'expected_result_date', type: 'date' }, { name: 'visit_required', type: 'bool' }, rel('tags', 'crm_tender_tags', false, 50), ...dates], indexes: ['CREATE UNIQUE INDEX idx_tender_opportunity ON crm_tenders (opportunity)'] }))
  app.save(new Collection({ name: 'crm_tender_appointments', type: 'base', listRule: read, viewRule: read, createRule: null, updateRule: null, deleteRule: null, fields: [rel('tender', 'crm_tenders', true), { name: 'kind', type: 'select', values: ['visit', 'hearing'], required: true, maxSelect: 1 }, { name: 'start', type: 'date', required: true }, { name: 'end', type: 'date' }, text('timezone', 80, true), text('location', 500), text('notes', 5000), rel('participants', 'hr_employees', false, 50), { name: 'status', type: 'select', values: ['planned', 'done', 'cancelled'], required: true, maxSelect: 1 }, ...dates] }))
  app.save(new Collection({ name: 'crm_tender_submissions', type: 'base', listRule: read, viewRule: read, createRule: null, updateRule: null, deleteRule: null, fields: [rel('tender', 'crm_tenders', true), { ...text('creation_key', 64, true), hidden: true }, { name: 'version', type: 'number', min: 1, onlyInt: true, required: true }, { name: 'submitted_at', type: 'date', required: true }, text('timezone', 80, true), rel('submitted_by', 'core_users', true), text('notes', 5000), { name: 'documents', type: 'json', maxSize: 50000 }, { name: 'created', type: 'autodate', onCreate: true }], indexes: ['CREATE UNIQUE INDEX idx_tender_submission_version ON crm_tender_submissions (tender, version)', 'CREATE UNIQUE INDEX idx_tender_submission_creation ON crm_tender_submissions (creation_key)'] }))
}, (app) => {
  for (const name of ['crm_tender_submissions', 'crm_tender_appointments', 'crm_tenders']) if (app.findRecordsByFilter(name, '', '', 1).length) throw new Error('Rollback AO refused: historical records exist.')
  for (const name of ['crm_tender_submissions', 'crm_tender_appointments', 'crm_tenders', 'crm_tender_tags', 'crm_tender_statuses']) app.delete(app.findCollectionByNameOrId(name))
  const collection = app.findCollectionByNameOrId('crm_opportunities'); collection.fields.getByName('type').values = ['direct']; app.save(collection)
})
