import { z } from 'zod'
export const productKinds = { equipment: 'Équipement', consumable: 'Fourniture', service: 'Service' } as const
export const categorySchema = z.object({ id: z.string(), updated: z.string(), code: z.string().min(1).max(40), label: z.string().min(1).max(120), coefficient: z.number().positive().max(100), active: z.boolean() })
export type Category = z.infer<typeof categorySchema>
export const brandSchema = z.object({ id: z.string(), name: z.string().min(1).max(160), active: z.boolean() })
export const offerInputSchema = z.object({ id: z.string().optional(), supplier: z.string().min(1, 'Choisissez un fournisseur.'), supplier_sku: z.string().max(160), list_price: z.number().min(0).max(1e9), discount: z.number().min(0).max(100), purchase_quantity: z.number().positive().max(1e6), currency: z.string().length(3), lead_time_days: z.number().int().min(0).max(3650), valid_from: z.string(), valid_until: z.string(), is_preferred: z.boolean() })
export const productInputSchema = z.object({ sku: z.string().trim().min(1, 'Référence obligatoire.').max(80), name: z.string().trim().min(1, 'Nom obligatoire.').max(200), description: z.string().max(2000), category: z.string().min(1, 'Choisissez une famille.'), kind: z.enum(['equipment', 'consumable', 'service']), sale_enabled: z.boolean(), purchase_enabled: z.boolean(), stock_policy: z.enum(['none', 'stocked', 'on_demand']), replenishment_policy: z.enum(['manual', 'on_demand', 'min_max']), tracking: z.enum(['none', 'lot', 'serial']), base_unit: z.string().min(1, 'Choisissez une unité.'), brand: z.string().min(1, 'Choisissez une marque.'), cost_override: z.boolean().default(false), coefficient_override: z.boolean().default(false), manual_coefficient: z.number().positive().max(100).default(1), weight_kg: z.number().min(0).max(1e9).default(0), volume_m3: z.number().min(0).max(1e9).default(0), hs_code: z.string().regex(/^([0-9]{6}|[0-9]{8}|[0-9]{10})?$/, 'Code SH : 6, 8 ou 10 chiffres.').default(''), origin_country: z.string().max(2).default(''), manufacturer: z.string().max(160), manufacturer_ref: z.string().max(160), barcode: z.string().max(100), variant_group: z.string().max(120), reference_cost: z.number().min(0).max(1e9), sale_currency: z.string().length(3), offers: z.array(offerInputSchema).max(30) })
export type ProductInput = z.infer<typeof productInputSchema>
export type OfferInput = z.infer<typeof offerInputSchema>
export const productSchema = productInputSchema.omit({ offers: true }).extend({ brand: z.string(), id: z.string(), collectionId: z.string(), updated: z.string(), active: z.boolean(), primary_image: z.string(), images: z.array(z.string()), category_label: z.string(), unit_code: z.string(), unit_locked: z.boolean(), image_url: z.string().optional(), image_urls: z.array(z.string()).optional(), pricing: z.object({ unit_cost: z.number(), unit_price: z.number().nullable(), coefficient: z.number(), margin_rate: z.number().nullable(), currency: z.string(), product_supplier: z.string(), supplier: z.string(), warning: z.string(), source: z.enum(['supplier', 'reference']) }), offers: z.array(offerInputSchema.extend({ id: z.string(), supplier_name: z.string(), unit_cost: z.number(), purchase_price: z.number() })).default([]), price_history: z.array(z.object({ id: z.string(), effective_at: z.string(), price: z.number(), currency: z.string(), snapshot: z.object({ supplier: z.string(), supplier_sku: z.string(), list_price: z.number(), discount: z.number(), purchase_quantity: z.number() }) })).default([]) })
export type Product = z.infer<typeof productSchema>
export const choicesSchema = z.object({ brands: z.array(brandSchema), countries: z.array(z.object({ code: z.string(), label: z.string(), active: z.boolean() })), categories: z.array(categorySchema), units: z.array(z.object({ id: z.string(), code: z.string(), label: z.string(), active: z.boolean() })), currencies: z.array(z.object({ code: z.string(), label: z.string() })), suppliers: z.array(z.object({ id: z.string(), name: z.string() })) })
export type CatalogChoices = z.infer<typeof choicesSchema>
export const productPageSchema = z.object({ items: z.array(productSchema), page: z.number(), totalItems: z.number(), totalPages: z.number() })
export const quoteProductSchema = z.object({ product: z.string(), product_supplier: z.string(), description: z.string(), brand: z.string(), reference: z.string(), unit: z.string(), unit_cost: z.number(), unit_price: z.number(), margin_percent: z.number() })
export type ProductFiles = { primary?: File | undefined; images: File[]; removePrimary: boolean; removeImages: string[] }
export const emptyFiles = (): ProductFiles => ({ images: [], removePrimary: false, removeImages: [] })
export function productDefaults(choices: CatalogChoices, name = ''): ProductInput { return { sku: '', name, description: '', category: choices.categories.find((item) => item.active)?.id || '', kind: 'equipment', sale_enabled: true, purchase_enabled: true, stock_policy: 'stocked', replenishment_policy: 'manual', tracking: 'none', base_unit: choices.units.find((item) => item.code === 'u' && item.active)?.id || '', brand: '', cost_override: false, coefficient_override: false, manual_coefficient: 1, weight_kg: 0, volume_m3: 0, hs_code: '', origin_country: '', manufacturer: '', manufacturer_ref: '', barcode: '', variant_group: '', reference_cost: 0, sale_currency: 'EUR', offers: [] } }
