import { z } from 'zod'
export const quoteStatus = z.enum(['draft', 'validated', 'sent', 'accepted', 'rejected', 'cancelled'])
export const quoteStatusTones = { draft: 'violet', validated: 'blue', sent: 'amber', accepted: 'green', rejected: 'navy', cancelled: 'navy' } as const
export const quoteStatusLabels = { draft: 'Brouillon', validated: 'Devis', sent: 'Envoyé', accepted: 'Commande client', rejected: 'Refusé', cancelled: 'Annulé' }
export const quoteLineInputSchema = z.object({ product: z.string().default(''), product_supplier: z.string().default(''), price_source: z.enum(['manual', 'margin']).default('manual'), margin_percent: z.number().min(-100).max(10000000000000).default(0), kind: z.enum(['item', 'section', 'subsection', 'subsection3', 'note']).default('item'), brand: z.string().max(160).default(''), reference: z.string().max(160).default(''), unit_cost: z.number().min(0).max(1000000000).default(0), discount: z.number().min(0).max(100).default(0), is_option: z.boolean().default(false), show_total: z.boolean().default(false), description: z.string().trim().min(1).max(2000), quantity: z.number().min(0).max(1000000), unit: z.string().max(40), unit_price: z.number().min(0).max(1000000000) })
export const quoteInputSchema = z.object({ discount: z.number().min(0).max(1000000000).default(0), discount_mode: z.enum(['percent', 'amount']).default('percent'), owner: z.string().default(''), terms_id: z.string().max(100).default(''), opportunity: z.string().min(1, 'Choisissez une opportunité.'), title: z.string().trim().min(1, 'Indiquez le titre du devis.').max(200), quote_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), valid_until: z.string(), notes: z.string().max(10000), lines: z.array(quoteLineInputSchema).max(200).refine((lines) => lines.every((line) => line.kind !== 'item' || line.quantity >= 0.001), 'La quantité des articles doit être positive.') })
export const quoteSchema = quoteInputSchema.omit({ quote_date: true, valid_until: true, lines: true }).extend({ terms_label: z.string(), terms_content: z.string(), id: z.string(), archived_at: z.string().default(''), sent_at: z.string().default(''), can_delete: z.boolean().default(false), quote_number: z.string(), quote_sequence: z.number(), analytic_account: z.string(), company: z.string(), contact: z.string(), owner: z.string(), owner_name: z.string().default(''), order: z.object({ id: z.string(), number: z.string(), customer_number: z.string(), event_id: z.string(), files: z.array(z.string()) }).nullable().default(null), currency: z.string(), status: quoteStatus, subtotal: z.number(), subtotal_before_discount: z.number(), discount_amount: z.number(), margin_percent: z.number(), options_total: z.number(), cost_total: z.number(), margin_amount: z.number(), tax: z.number(), tax_rate: z.number(), total: z.number(), quote_date: z.string(), valid_until: z.string(), lost_reason: z.string(), updated: z.string(), created: z.string(), company_name: z.string(), opportunity_name: z.string(), opportunity_number: z.string(), lines: z.array(quoteLineInputSchema.extend({ id: z.string(), catalog_snapshot: z.record(z.string(), z.unknown()).nullable().optional(), line_total: z.number(), section_total: z.number(), section_options_total: z.number() })) })
export const quotePageSchema = z.object({ items: z.array(quoteSchema), page: z.number(), totalItems: z.number(), totalPages: z.number() })
export const opportunityChoiceSchema = z.object({ id: z.string(), number: z.string(), title: z.string(), currency: z.string() })
export const relatedSalesSchema = z.object({ quoteCount: z.number(), orderCount: z.number(), revenue: z.array(z.object({ currency: z.string(), amount: z.number() })) })
export type Quote = z.infer<typeof quoteSchema>
export type QuoteInput = z.infer<typeof quoteInputSchema>
export type QuoteListOptions = { q: string; opportunity: string; company: string; status: string; sort: string; page: number }

export const quoteColumns = [
  ['position', '#', 52], ['description', 'Description', 280], ['brand', 'Marque', 100], ['reference', 'Référence', 110], ['quantity', 'Qté', 65], ['unit', 'Unité', 60], ['unit_cost', 'Coût', 110], ['margin_percent', 'Marge %', 75], ['unit_price', 'PUV', 110], ['discount', 'Remise %', 75], ['line_total', 'PTV', 110], ['purchase', 'Commande', 90], ['is_option', 'Option', 52], ['actions', 'Actions', 64],
] as const
export const salesSettingsSchema = z.object({ terms: z.array(z.object({ id: z.string(), label: z.string(), content: z.string(), active: z.boolean() })), units: z.array(z.object({ code: z.string(), label: z.string(), active: z.boolean() })), id: z.string(), updated: z.string(), validity_days: z.number().int().min(1).max(365), default_tax_rate: z.number().min(0).max(100), column_widths: z.record(z.string(), z.number().int().min(40).max(800)) })
export type SalesSettings = z.infer<typeof salesSettingsSchema>
export type QuoteLineInput = z.infer<typeof quoteLineInputSchema>
export const emptyQuoteLine = (kind: QuoteLineInput['kind'] = 'item'): QuoteLineInput => ({ kind, product: '', product_supplier: '', price_source: 'manual', margin_percent: 0, description: '', brand: '', reference: '', quantity: kind === 'item' ? 1 : 0, unit: kind === 'item' ? 'u' : '', unit_cost: 0, unit_price: 0, discount: 0, is_option: false, show_total: false })
