routerAdd('GET', '/api/horizon/documents/templates', (event) => require(`${__hooks}/lib/documents.js`).list(event), $apis.requireAuth('core_users'))
routerAdd('GET', '/api/horizon/documents/templates/{id}', (event) => require(`${__hooks}/lib/documents.js`).record(event), $apis.requireAuth('core_users'))
routerAdd('POST', '/api/horizon/documents/templates/save', (event) => require(`${__hooks}/lib/documents.js`).save(event), $apis.requireAuth('core_users'))
routerAdd('POST', '/api/horizon/documents/templates/publish', (event) => require(`${__hooks}/lib/documents.js`).publish(event), $apis.requireAuth('core_users'))
routerAdd('POST', '/api/horizon/documents/templates/delete', (event) => require(`${__hooks}/lib/documents.js`).delete(event), $apis.requireAuth('core_users'))
routerAdd('POST', '/api/horizon/documents/templates/archive', (event) => require(`${__hooks}/lib/documents.js`).archive(event), $apis.requireAuth('core_users'))
routerAdd('POST', '/api/horizon/documents/preview', (event) => require(`${__hooks}/lib/documents.js`).preview(event), $apis.requireAuth('core_users'))
routerAdd('GET', '/api/horizon/documents/file-settings', (event) => require(`${__hooks}/lib/document-file-settings.js`).read(event), $apis.requireAuth('core_users'))
routerAdd('POST', '/api/horizon/documents/file-settings', (event) => require(`${__hooks}/lib/document-file-settings.js`).save(event), $apis.requireAuth('core_users'))
onRecordUpdate(() => { throw new BadRequestError('Une version publiée est immuable.') }, 'documents_template_versions')
onRecordDelete(() => { throw new BadRequestError('Une version publiée doit être conservée.') }, 'documents_template_versions')
onRecordDelete((event) => {
  if (event.record.getString('current_version') || event.app.findRecordsByFilter('documents_template_versions', 'template = {:id}', '', 1, 0, { id: event.record.id }).length) throw new BadRequestError('Archivez le modèle pour conserver ses versions publiées.')
  event.next()
}, 'documents_templates')
