routerAdd('GET', '/api/horizon/inventory/products', (event) => require(`${__hooks}/lib/catalog.js`).list(event), $apis.requireAuth('core_users'))
routerAdd('GET', '/api/horizon/inventory/products/{id}', (event) => require(`${__hooks}/lib/catalog.js`).record(event), $apis.requireAuth('core_users'))
routerAdd('POST', '/api/horizon/inventory/products/save', (event) => require(`${__hooks}/lib/catalog.js`).save(event), $apis.requireAuth('core_users'))
routerAdd('POST', '/api/horizon/inventory/products/state', (event) => require(`${__hooks}/lib/catalog.js`).state(event), $apis.requireAuth('core_users'))
routerAdd('GET', '/api/horizon/inventory/choices', (event) => require(`${__hooks}/lib/catalog.js`).choices(event), $apis.requireAuth('core_users'))
routerAdd('GET', '/api/horizon/inventory/categories', (event) => require(`${__hooks}/lib/catalog.js`).categories(event), $apis.requireAuth('core_users'))
routerAdd('POST', '/api/horizon/inventory/categories/save', (event) => require(`${__hooks}/lib/catalog.js`).saveCategory(event), $apis.requireAuth('core_users'))
routerAdd('POST', '/api/horizon/inventory/quote-line', (event) => require(`${__hooks}/lib/catalog.js`).quoteLine(event), $apis.requireAuth('core_users'))
onRecordDelete(() => { throw new BadRequestError('Archivez le produit pour conserver ses liens métier.') }, 'inventory_products')
onRecordDelete(() => { throw new BadRequestError('Les offres fournisseurs sont archivées, pas supprimées.') }, 'inventory_product_suppliers')
onRecordUpdate(() => { throw new BadRequestError('L’historique des prix est immuable.') }, 'inventory_supplier_price_history')
onRecordDelete(() => { throw new BadRequestError('L’historique des prix doit être conservé.') }, 'inventory_supplier_price_history')

routerAdd('POST', '/api/horizon/inventory/brands/create', (event) => require(`${__hooks}/lib/catalog.js`).createBrand(event), $apis.requireAuth('core_users'))
onRecordDelete(() => { throw new BadRequestError('Les marques liées au catalogue doivent être conservées.') }, 'inventory_brands')

routerAdd('GET', '/api/horizon/inventory/products/{id}/quotes', (event) => require(`${__hooks}/lib/sales.js`).productQuotes(event), $apis.requireAuth('core_users'))
